packages: []

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - unplugin-swc@1.5.10
  - '@revisium/revo-run@0.1.0-alpha.2'

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
