
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Project: 'Project',
  Repository: 'Repository',
  ReviewThread: 'ReviewThread',
  ReviewMessage: 'ReviewMessage',
  Branch: 'Branch',
  Revision: 'Revision',
  Table: 'Table',
  Row: 'Row',
  FileBlob: 'FileBlob',
  ProjectFileUsage: 'ProjectFileUsage',
  TableMigration: 'TableMigration',
  DbosWorkflowStatus: 'DbosWorkflowStatus',
  DbosOperationOutput: 'DbosOperationOutput'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ProjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  kind: 'kind',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const RepositoryScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  name: 'name',
  remoteUrl: 'remoteUrl',
  localPath: 'localPath',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RepositoryScalarFieldEnum = (typeof RepositoryScalarFieldEnum)[keyof typeof RepositoryScalarFieldEnum]


export const ReviewThreadScalarFieldEnum = {
  id: 'id',
  scopeKey: 'scopeKey',
  subjectKey: 'subjectKey',
  contextKey: 'contextKey',
  context: 'context',
  version: 'version',
  createdAt: 'createdAt',
  resolvedAt: 'resolvedAt',
  resolvedBy: 'resolvedBy'
} as const

export type ReviewThreadScalarFieldEnum = (typeof ReviewThreadScalarFieldEnum)[keyof typeof ReviewThreadScalarFieldEnum]


export const ReviewMessageScalarFieldEnum = {
  id: 'id',
  threadId: 'threadId',
  authorId: 'authorId',
  body: 'body',
  version: 'version',
  createdAt: 'createdAt',
  editedAt: 'editedAt',
  deletedAt: 'deletedAt',
  deletedBy: 'deletedBy'
} as const

export type ReviewMessageScalarFieldEnum = (typeof ReviewMessageScalarFieldEnum)[keyof typeof ReviewMessageScalarFieldEnum]


export const BranchScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  isRoot: 'isRoot',
  name: 'name',
  projectId: 'projectId'
} as const

export type BranchScalarFieldEnum = (typeof BranchScalarFieldEnum)[keyof typeof BranchScalarFieldEnum]


export const RevisionScalarFieldEnum = {
  id: 'id',
  sequence: 'sequence',
  createdAt: 'createdAt',
  comment: 'comment',
  isHead: 'isHead',
  isDraft: 'isDraft',
  isStart: 'isStart',
  hasChanges: 'hasChanges',
  branchId: 'branchId',
  parentId: 'parentId'
} as const

export type RevisionScalarFieldEnum = (typeof RevisionScalarFieldEnum)[keyof typeof RevisionScalarFieldEnum]


export const TableScalarFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  readonly: 'readonly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  system: 'system'
} as const

export type TableScalarFieldEnum = (typeof TableScalarFieldEnum)[keyof typeof TableScalarFieldEnum]


export const RowScalarFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  readonly: 'readonly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  publishedAt: 'publishedAt',
  data: 'data',
  meta: 'meta',
  hash: 'hash',
  schemaHash: 'schemaHash'
} as const

export type RowScalarFieldEnum = (typeof RowScalarFieldEnum)[keyof typeof RowScalarFieldEnum]


export const FileBlobScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  deletedAt: 'deletedAt',
  projectId: 'projectId',
  hash: 'hash',
  size: 'size'
} as const

export type FileBlobScalarFieldEnum = (typeof FileBlobScalarFieldEnum)[keyof typeof FileBlobScalarFieldEnum]


export const ProjectFileUsageScalarFieldEnum = {
  projectId: 'projectId',
  fileBytes: 'fileBytes',
  updatedAt: 'updatedAt'
} as const

export type ProjectFileUsageScalarFieldEnum = (typeof ProjectFileUsageScalarFieldEnum)[keyof typeof ProjectFileUsageScalarFieldEnum]


export const TableMigrationScalarFieldEnum = {
  id: 'id',
  revisionId: 'revisionId',
  tableId: 'tableId',
  sourceTableVersionId: 'sourceTableVersionId',
  shadowTableVersionId: 'shadowTableVersionId',
  status: 'status',
  phase: 'phase',
  patches: 'patches',
  previousSchema: 'previousSchema',
  previousSchemaHash: 'previousSchemaHash',
  targetSchemaHash: 'targetSchemaHash',
  totalRows: 'totalRows',
  copiedRows: 'copiedRows',
  lastCopiedRowId: 'lastCopiedRowId',
  batchSize: 'batchSize',
  currentBatch: 'currentBatch',
  totalBatches: 'totalBatches',
  createdAt: 'createdAt',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  lastProgressAt: 'lastProgressAt',
  lockedBy: 'lockedBy',
  lockedAt: 'lockedAt',
  heartbeatAt: 'heartbeatAt',
  errorMessage: 'errorMessage',
  retryCount: 'retryCount',
  maxRetries: 'maxRetries'
} as const

export type TableMigrationScalarFieldEnum = (typeof TableMigrationScalarFieldEnum)[keyof typeof TableMigrationScalarFieldEnum]


export const DbosWorkflowStatusScalarFieldEnum = {
  workflowUuid: 'workflowUuid',
  status: 'status',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DbosWorkflowStatusScalarFieldEnum = (typeof DbosWorkflowStatusScalarFieldEnum)[keyof typeof DbosWorkflowStatusScalarFieldEnum]


export const DbosOperationOutputScalarFieldEnum = {
  workflowUuid: 'workflowUuid',
  functionId: 'functionId',
  functionName: 'functionName'
} as const

export type DbosOperationOutputScalarFieldEnum = (typeof DbosOperationOutputScalarFieldEnum)[keyof typeof DbosOperationOutputScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

