
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgentSessionEventStream` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AgentSessionEventStream
 * 
 */
export type AgentSessionEventStreamModel = runtime.Types.Result.DefaultSelection<Prisma.$AgentSessionEventStreamPayload>

export type AggregateAgentSessionEventStream = {
  _count: AgentSessionEventStreamCountAggregateOutputType | null
  _avg: AgentSessionEventStreamAvgAggregateOutputType | null
  _sum: AgentSessionEventStreamSumAggregateOutputType | null
  _min: AgentSessionEventStreamMinAggregateOutputType | null
  _max: AgentSessionEventStreamMaxAggregateOutputType | null
}

export type AgentSessionEventStreamAvgAggregateOutputType = {
  sequence: number | null
}

export type AgentSessionEventStreamSumAggregateOutputType = {
  sequence: number | null
}

export type AgentSessionEventStreamMinAggregateOutputType = {
  sessionId: string | null
  dialogueId: string | null
  streamId: string | null
  sequence: number | null
  eventId: string | null
}

export type AgentSessionEventStreamMaxAggregateOutputType = {
  sessionId: string | null
  dialogueId: string | null
  streamId: string | null
  sequence: number | null
  eventId: string | null
}

export type AgentSessionEventStreamCountAggregateOutputType = {
  sessionId: number
  dialogueId: number
  streamId: number
  sequence: number
  eventId: number
  _all: number
}


export type AgentSessionEventStreamAvgAggregateInputType = {
  sequence?: true
}

export type AgentSessionEventStreamSumAggregateInputType = {
  sequence?: true
}

export type AgentSessionEventStreamMinAggregateInputType = {
  sessionId?: true
  dialogueId?: true
  streamId?: true
  sequence?: true
  eventId?: true
}

export type AgentSessionEventStreamMaxAggregateInputType = {
  sessionId?: true
  dialogueId?: true
  streamId?: true
  sequence?: true
  eventId?: true
}

export type AgentSessionEventStreamCountAggregateInputType = {
  sessionId?: true
  dialogueId?: true
  streamId?: true
  sequence?: true
  eventId?: true
  _all?: true
}

export type AgentSessionEventStreamAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentSessionEventStream to aggregate.
   */
  where?: Prisma.AgentSessionEventStreamWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentSessionEventStreams to fetch.
   */
  orderBy?: Prisma.AgentSessionEventStreamOrderByWithRelationInput | Prisma.AgentSessionEventStreamOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgentSessionEventStreamWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentSessionEventStreams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentSessionEventStreams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgentSessionEventStreams
  **/
  _count?: true | AgentSessionEventStreamCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AgentSessionEventStreamAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AgentSessionEventStreamSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgentSessionEventStreamMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgentSessionEventStreamMaxAggregateInputType
}

export type GetAgentSessionEventStreamAggregateType<T extends AgentSessionEventStreamAggregateArgs> = {
      [P in keyof T & keyof AggregateAgentSessionEventStream]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgentSessionEventStream[P]>
    : Prisma.GetScalarType<T[P], AggregateAgentSessionEventStream[P]>
}




export type AgentSessionEventStreamGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgentSessionEventStreamWhereInput
  orderBy?: Prisma.AgentSessionEventStreamOrderByWithAggregationInput | Prisma.AgentSessionEventStreamOrderByWithAggregationInput[]
  by: Prisma.AgentSessionEventStreamScalarFieldEnum[] | Prisma.AgentSessionEventStreamScalarFieldEnum
  having?: Prisma.AgentSessionEventStreamScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgentSessionEventStreamCountAggregateInputType | true
  _avg?: AgentSessionEventStreamAvgAggregateInputType
  _sum?: AgentSessionEventStreamSumAggregateInputType
  _min?: AgentSessionEventStreamMinAggregateInputType
  _max?: AgentSessionEventStreamMaxAggregateInputType
}

export type AgentSessionEventStreamGroupByOutputType = {
  sessionId: string
  dialogueId: string | null
  streamId: string | null
  sequence: number
  eventId: string | null
  _count: AgentSessionEventStreamCountAggregateOutputType | null
  _avg: AgentSessionEventStreamAvgAggregateOutputType | null
  _sum: AgentSessionEventStreamSumAggregateOutputType | null
  _min: AgentSessionEventStreamMinAggregateOutputType | null
  _max: AgentSessionEventStreamMaxAggregateOutputType | null
}

export type GetAgentSessionEventStreamGroupByPayload<T extends AgentSessionEventStreamGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgentSessionEventStreamGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgentSessionEventStreamGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgentSessionEventStreamGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgentSessionEventStreamGroupByOutputType[P]>
      }
    >
  >



export type AgentSessionEventStreamWhereInput = {
  AND?: Prisma.AgentSessionEventStreamWhereInput | Prisma.AgentSessionEventStreamWhereInput[]
  OR?: Prisma.AgentSessionEventStreamWhereInput[]
  NOT?: Prisma.AgentSessionEventStreamWhereInput | Prisma.AgentSessionEventStreamWhereInput[]
  sessionId?: Prisma.StringFilter<"AgentSessionEventStream"> | string
  dialogueId?: Prisma.StringNullableFilter<"AgentSessionEventStream"> | string | null
  streamId?: Prisma.StringNullableFilter<"AgentSessionEventStream"> | string | null
  sequence?: Prisma.IntFilter<"AgentSessionEventStream"> | number
  eventId?: Prisma.StringNullableFilter<"AgentSessionEventStream"> | string | null
  dialogue?: Prisma.XOR<Prisma.DialogueNullableScalarRelationFilter, Prisma.DialogueWhereInput> | null
  events?: Prisma.AgentSessionEventListRelationFilter
}

export type AgentSessionEventStreamOrderByWithRelationInput = {
  sessionId?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrderInput | Prisma.SortOrder
  streamId?: Prisma.SortOrderInput | Prisma.SortOrder
  sequence?: Prisma.SortOrder
  eventId?: Prisma.SortOrderInput | Prisma.SortOrder
  dialogue?: Prisma.DialogueOrderByWithRelationInput
  events?: Prisma.AgentSessionEventOrderByRelationAggregateInput
}

export type AgentSessionEventStreamWhereUniqueInput = Prisma.AtLeast<{
  sessionId?: string
  AND?: Prisma.AgentSessionEventStreamWhereInput | Prisma.AgentSessionEventStreamWhereInput[]
  OR?: Prisma.AgentSessionEventStreamWhereInput[]
  NOT?: Prisma.AgentSessionEventStreamWhereInput | Prisma.AgentSessionEventStreamWhereInput[]
  dialogueId?: Prisma.StringNullableFilter<"AgentSessionEventStream"> | string | null
  streamId?: Prisma.StringNullableFilter<"AgentSessionEventStream"> | string | null
  sequence?: Prisma.IntFilter<"AgentSessionEventStream"> | number
  eventId?: Prisma.StringNullableFilter<"AgentSessionEventStream"> | string | null
  dialogue?: Prisma.XOR<Prisma.DialogueNullableScalarRelationFilter, Prisma.DialogueWhereInput> | null
  events?: Prisma.AgentSessionEventListRelationFilter
}, "sessionId">

export type AgentSessionEventStreamOrderByWithAggregationInput = {
  sessionId?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrderInput | Prisma.SortOrder
  streamId?: Prisma.SortOrderInput | Prisma.SortOrder
  sequence?: Prisma.SortOrder
  eventId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AgentSessionEventStreamCountOrderByAggregateInput
  _avg?: Prisma.AgentSessionEventStreamAvgOrderByAggregateInput
  _max?: Prisma.AgentSessionEventStreamMaxOrderByAggregateInput
  _min?: Prisma.AgentSessionEventStreamMinOrderByAggregateInput
  _sum?: Prisma.AgentSessionEventStreamSumOrderByAggregateInput
}

export type AgentSessionEventStreamScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgentSessionEventStreamScalarWhereWithAggregatesInput | Prisma.AgentSessionEventStreamScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgentSessionEventStreamScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgentSessionEventStreamScalarWhereWithAggregatesInput | Prisma.AgentSessionEventStreamScalarWhereWithAggregatesInput[]
  sessionId?: Prisma.StringWithAggregatesFilter<"AgentSessionEventStream"> | string
  dialogueId?: Prisma.StringNullableWithAggregatesFilter<"AgentSessionEventStream"> | string | null
  streamId?: Prisma.StringNullableWithAggregatesFilter<"AgentSessionEventStream"> | string | null
  sequence?: Prisma.IntWithAggregatesFilter<"AgentSessionEventStream"> | number
  eventId?: Prisma.StringNullableWithAggregatesFilter<"AgentSessionEventStream"> | string | null
}

export type AgentSessionEventStreamCreateInput = {
  sessionId: string
  streamId?: string | null
  sequence?: number
  eventId?: string | null
  dialogue?: Prisma.DialogueCreateNestedOneWithoutEventStreamsInput
  events?: Prisma.AgentSessionEventCreateNestedManyWithoutSessionInput
}

export type AgentSessionEventStreamUncheckedCreateInput = {
  sessionId: string
  dialogueId?: string | null
  streamId?: string | null
  sequence?: number
  eventId?: string | null
  events?: Prisma.AgentSessionEventUncheckedCreateNestedManyWithoutSessionInput
}

export type AgentSessionEventStreamUpdateInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dialogue?: Prisma.DialogueUpdateOneWithoutEventStreamsNestedInput
  events?: Prisma.AgentSessionEventUpdateManyWithoutSessionNestedInput
}

export type AgentSessionEventStreamUncheckedUpdateInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  dialogueId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  streamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  events?: Prisma.AgentSessionEventUncheckedUpdateManyWithoutSessionNestedInput
}

export type AgentSessionEventStreamCreateManyInput = {
  sessionId: string
  dialogueId?: string | null
  streamId?: string | null
  sequence?: number
  eventId?: string | null
}

export type AgentSessionEventStreamUpdateManyMutationInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgentSessionEventStreamUncheckedUpdateManyInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  dialogueId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  streamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgentSessionEventStreamListRelationFilter = {
  every?: Prisma.AgentSessionEventStreamWhereInput
  some?: Prisma.AgentSessionEventStreamWhereInput
  none?: Prisma.AgentSessionEventStreamWhereInput
}

export type AgentSessionEventStreamOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AgentSessionEventStreamCountOrderByAggregateInput = {
  sessionId?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type AgentSessionEventStreamAvgOrderByAggregateInput = {
  sequence?: Prisma.SortOrder
}

export type AgentSessionEventStreamMaxOrderByAggregateInput = {
  sessionId?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type AgentSessionEventStreamMinOrderByAggregateInput = {
  sessionId?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
}

export type AgentSessionEventStreamSumOrderByAggregateInput = {
  sequence?: Prisma.SortOrder
}

export type AgentSessionEventStreamScalarRelationFilter = {
  is?: Prisma.AgentSessionEventStreamWhereInput
  isNot?: Prisma.AgentSessionEventStreamWhereInput
}

export type AgentSessionEventStreamCreateNestedManyWithoutDialogueInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutDialogueInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput> | Prisma.AgentSessionEventStreamCreateWithoutDialogueInput[] | Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.AgentSessionEventStreamCreateOrConnectWithoutDialogueInput | Prisma.AgentSessionEventStreamCreateOrConnectWithoutDialogueInput[]
  createMany?: Prisma.AgentSessionEventStreamCreateManyDialogueInputEnvelope
  connect?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
}

export type AgentSessionEventStreamUncheckedCreateNestedManyWithoutDialogueInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutDialogueInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput> | Prisma.AgentSessionEventStreamCreateWithoutDialogueInput[] | Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.AgentSessionEventStreamCreateOrConnectWithoutDialogueInput | Prisma.AgentSessionEventStreamCreateOrConnectWithoutDialogueInput[]
  createMany?: Prisma.AgentSessionEventStreamCreateManyDialogueInputEnvelope
  connect?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
}

export type AgentSessionEventStreamUpdateManyWithoutDialogueNestedInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutDialogueInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput> | Prisma.AgentSessionEventStreamCreateWithoutDialogueInput[] | Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.AgentSessionEventStreamCreateOrConnectWithoutDialogueInput | Prisma.AgentSessionEventStreamCreateOrConnectWithoutDialogueInput[]
  upsert?: Prisma.AgentSessionEventStreamUpsertWithWhereUniqueWithoutDialogueInput | Prisma.AgentSessionEventStreamUpsertWithWhereUniqueWithoutDialogueInput[]
  createMany?: Prisma.AgentSessionEventStreamCreateManyDialogueInputEnvelope
  set?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
  disconnect?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
  delete?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
  connect?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
  update?: Prisma.AgentSessionEventStreamUpdateWithWhereUniqueWithoutDialogueInput | Prisma.AgentSessionEventStreamUpdateWithWhereUniqueWithoutDialogueInput[]
  updateMany?: Prisma.AgentSessionEventStreamUpdateManyWithWhereWithoutDialogueInput | Prisma.AgentSessionEventStreamUpdateManyWithWhereWithoutDialogueInput[]
  deleteMany?: Prisma.AgentSessionEventStreamScalarWhereInput | Prisma.AgentSessionEventStreamScalarWhereInput[]
}

export type AgentSessionEventStreamUncheckedUpdateManyWithoutDialogueNestedInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutDialogueInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput> | Prisma.AgentSessionEventStreamCreateWithoutDialogueInput[] | Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.AgentSessionEventStreamCreateOrConnectWithoutDialogueInput | Prisma.AgentSessionEventStreamCreateOrConnectWithoutDialogueInput[]
  upsert?: Prisma.AgentSessionEventStreamUpsertWithWhereUniqueWithoutDialogueInput | Prisma.AgentSessionEventStreamUpsertWithWhereUniqueWithoutDialogueInput[]
  createMany?: Prisma.AgentSessionEventStreamCreateManyDialogueInputEnvelope
  set?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
  disconnect?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
  delete?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
  connect?: Prisma.AgentSessionEventStreamWhereUniqueInput | Prisma.AgentSessionEventStreamWhereUniqueInput[]
  update?: Prisma.AgentSessionEventStreamUpdateWithWhereUniqueWithoutDialogueInput | Prisma.AgentSessionEventStreamUpdateWithWhereUniqueWithoutDialogueInput[]
  updateMany?: Prisma.AgentSessionEventStreamUpdateManyWithWhereWithoutDialogueInput | Prisma.AgentSessionEventStreamUpdateManyWithWhereWithoutDialogueInput[]
  deleteMany?: Prisma.AgentSessionEventStreamScalarWhereInput | Prisma.AgentSessionEventStreamScalarWhereInput[]
}

export type AgentSessionEventStreamCreateNestedOneWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutEventsInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.AgentSessionEventStreamCreateOrConnectWithoutEventsInput
  connect?: Prisma.AgentSessionEventStreamWhereUniqueInput
}

export type AgentSessionEventStreamUpdateOneRequiredWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutEventsInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.AgentSessionEventStreamCreateOrConnectWithoutEventsInput
  upsert?: Prisma.AgentSessionEventStreamUpsertWithoutEventsInput
  connect?: Prisma.AgentSessionEventStreamWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgentSessionEventStreamUpdateToOneWithWhereWithoutEventsInput, Prisma.AgentSessionEventStreamUpdateWithoutEventsInput>, Prisma.AgentSessionEventStreamUncheckedUpdateWithoutEventsInput>
}

export type AgentSessionEventStreamCreateWithoutDialogueInput = {
  sessionId: string
  streamId?: string | null
  sequence?: number
  eventId?: string | null
  events?: Prisma.AgentSessionEventCreateNestedManyWithoutSessionInput
}

export type AgentSessionEventStreamUncheckedCreateWithoutDialogueInput = {
  sessionId: string
  streamId?: string | null
  sequence?: number
  eventId?: string | null
  events?: Prisma.AgentSessionEventUncheckedCreateNestedManyWithoutSessionInput
}

export type AgentSessionEventStreamCreateOrConnectWithoutDialogueInput = {
  where: Prisma.AgentSessionEventStreamWhereUniqueInput
  create: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutDialogueInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput>
}

export type AgentSessionEventStreamCreateManyDialogueInputEnvelope = {
  data: Prisma.AgentSessionEventStreamCreateManyDialogueInput | Prisma.AgentSessionEventStreamCreateManyDialogueInput[]
  skipDuplicates?: boolean
}

export type AgentSessionEventStreamUpsertWithWhereUniqueWithoutDialogueInput = {
  where: Prisma.AgentSessionEventStreamWhereUniqueInput
  update: Prisma.XOR<Prisma.AgentSessionEventStreamUpdateWithoutDialogueInput, Prisma.AgentSessionEventStreamUncheckedUpdateWithoutDialogueInput>
  create: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutDialogueInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutDialogueInput>
}

export type AgentSessionEventStreamUpdateWithWhereUniqueWithoutDialogueInput = {
  where: Prisma.AgentSessionEventStreamWhereUniqueInput
  data: Prisma.XOR<Prisma.AgentSessionEventStreamUpdateWithoutDialogueInput, Prisma.AgentSessionEventStreamUncheckedUpdateWithoutDialogueInput>
}

export type AgentSessionEventStreamUpdateManyWithWhereWithoutDialogueInput = {
  where: Prisma.AgentSessionEventStreamScalarWhereInput
  data: Prisma.XOR<Prisma.AgentSessionEventStreamUpdateManyMutationInput, Prisma.AgentSessionEventStreamUncheckedUpdateManyWithoutDialogueInput>
}

export type AgentSessionEventStreamScalarWhereInput = {
  AND?: Prisma.AgentSessionEventStreamScalarWhereInput | Prisma.AgentSessionEventStreamScalarWhereInput[]
  OR?: Prisma.AgentSessionEventStreamScalarWhereInput[]
  NOT?: Prisma.AgentSessionEventStreamScalarWhereInput | Prisma.AgentSessionEventStreamScalarWhereInput[]
  sessionId?: Prisma.StringFilter<"AgentSessionEventStream"> | string
  dialogueId?: Prisma.StringNullableFilter<"AgentSessionEventStream"> | string | null
  streamId?: Prisma.StringNullableFilter<"AgentSessionEventStream"> | string | null
  sequence?: Prisma.IntFilter<"AgentSessionEventStream"> | number
  eventId?: Prisma.StringNullableFilter<"AgentSessionEventStream"> | string | null
}

export type AgentSessionEventStreamCreateWithoutEventsInput = {
  sessionId: string
  streamId?: string | null
  sequence?: number
  eventId?: string | null
  dialogue?: Prisma.DialogueCreateNestedOneWithoutEventStreamsInput
}

export type AgentSessionEventStreamUncheckedCreateWithoutEventsInput = {
  sessionId: string
  dialogueId?: string | null
  streamId?: string | null
  sequence?: number
  eventId?: string | null
}

export type AgentSessionEventStreamCreateOrConnectWithoutEventsInput = {
  where: Prisma.AgentSessionEventStreamWhereUniqueInput
  create: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutEventsInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutEventsInput>
}

export type AgentSessionEventStreamUpsertWithoutEventsInput = {
  update: Prisma.XOR<Prisma.AgentSessionEventStreamUpdateWithoutEventsInput, Prisma.AgentSessionEventStreamUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.AgentSessionEventStreamCreateWithoutEventsInput, Prisma.AgentSessionEventStreamUncheckedCreateWithoutEventsInput>
  where?: Prisma.AgentSessionEventStreamWhereInput
}

export type AgentSessionEventStreamUpdateToOneWithWhereWithoutEventsInput = {
  where?: Prisma.AgentSessionEventStreamWhereInput
  data: Prisma.XOR<Prisma.AgentSessionEventStreamUpdateWithoutEventsInput, Prisma.AgentSessionEventStreamUncheckedUpdateWithoutEventsInput>
}

export type AgentSessionEventStreamUpdateWithoutEventsInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dialogue?: Prisma.DialogueUpdateOneWithoutEventStreamsNestedInput
}

export type AgentSessionEventStreamUncheckedUpdateWithoutEventsInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  dialogueId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  streamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgentSessionEventStreamCreateManyDialogueInput = {
  sessionId: string
  streamId?: string | null
  sequence?: number
  eventId?: string | null
}

export type AgentSessionEventStreamUpdateWithoutDialogueInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  events?: Prisma.AgentSessionEventUpdateManyWithoutSessionNestedInput
}

export type AgentSessionEventStreamUncheckedUpdateWithoutDialogueInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  events?: Prisma.AgentSessionEventUncheckedUpdateManyWithoutSessionNestedInput
}

export type AgentSessionEventStreamUncheckedUpdateManyWithoutDialogueInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  eventId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type AgentSessionEventStreamCountOutputType
 */

export type AgentSessionEventStreamCountOutputType = {
  events: number
}

export type AgentSessionEventStreamCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | AgentSessionEventStreamCountOutputTypeCountEventsArgs
}

/**
 * AgentSessionEventStreamCountOutputType without action
 */
export type AgentSessionEventStreamCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStreamCountOutputType
   */
  select?: Prisma.AgentSessionEventStreamCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AgentSessionEventStreamCountOutputType without action
 */
export type AgentSessionEventStreamCountOutputTypeCountEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgentSessionEventWhereInput
}


export type AgentSessionEventStreamSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  sessionId?: boolean
  dialogueId?: boolean
  streamId?: boolean
  sequence?: boolean
  eventId?: boolean
  dialogue?: boolean | Prisma.AgentSessionEventStream$dialogueArgs<ExtArgs>
  events?: boolean | Prisma.AgentSessionEventStream$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.AgentSessionEventStreamCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agentSessionEventStream"]>

export type AgentSessionEventStreamSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  sessionId?: boolean
  dialogueId?: boolean
  streamId?: boolean
  sequence?: boolean
  eventId?: boolean
  dialogue?: boolean | Prisma.AgentSessionEventStream$dialogueArgs<ExtArgs>
}, ExtArgs["result"]["agentSessionEventStream"]>

export type AgentSessionEventStreamSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  sessionId?: boolean
  dialogueId?: boolean
  streamId?: boolean
  sequence?: boolean
  eventId?: boolean
  dialogue?: boolean | Prisma.AgentSessionEventStream$dialogueArgs<ExtArgs>
}, ExtArgs["result"]["agentSessionEventStream"]>

export type AgentSessionEventStreamSelectScalar = {
  sessionId?: boolean
  dialogueId?: boolean
  streamId?: boolean
  sequence?: boolean
  eventId?: boolean
}

export type AgentSessionEventStreamOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"sessionId" | "dialogueId" | "streamId" | "sequence" | "eventId", ExtArgs["result"]["agentSessionEventStream"]>
export type AgentSessionEventStreamInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dialogue?: boolean | Prisma.AgentSessionEventStream$dialogueArgs<ExtArgs>
  events?: boolean | Prisma.AgentSessionEventStream$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.AgentSessionEventStreamCountOutputTypeDefaultArgs<ExtArgs>
}
export type AgentSessionEventStreamIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dialogue?: boolean | Prisma.AgentSessionEventStream$dialogueArgs<ExtArgs>
}
export type AgentSessionEventStreamIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dialogue?: boolean | Prisma.AgentSessionEventStream$dialogueArgs<ExtArgs>
}

export type $AgentSessionEventStreamPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgentSessionEventStream"
  objects: {
    dialogue: Prisma.$DialoguePayload<ExtArgs> | null
    events: Prisma.$AgentSessionEventPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    sessionId: string
    dialogueId: string | null
    streamId: string | null
    sequence: number
    eventId: string | null
  }, ExtArgs["result"]["agentSessionEventStream"]>
  composites: {}
}

export type AgentSessionEventStreamGetPayload<S extends boolean | null | undefined | AgentSessionEventStreamDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload, S>

export type AgentSessionEventStreamCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgentSessionEventStreamFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgentSessionEventStreamCountAggregateInputType | true
  }

export interface AgentSessionEventStreamDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgentSessionEventStream'], meta: { name: 'AgentSessionEventStream' } }
  /**
   * Find zero or one AgentSessionEventStream that matches the filter.
   * @param {AgentSessionEventStreamFindUniqueArgs} args - Arguments to find a AgentSessionEventStream
   * @example
   * // Get one AgentSessionEventStream
   * const agentSessionEventStream = await prisma.agentSessionEventStream.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgentSessionEventStreamFindUniqueArgs>(args: Prisma.SelectSubset<T, AgentSessionEventStreamFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventStreamClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgentSessionEventStream that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgentSessionEventStreamFindUniqueOrThrowArgs} args - Arguments to find a AgentSessionEventStream
   * @example
   * // Get one AgentSessionEventStream
   * const agentSessionEventStream = await prisma.agentSessionEventStream.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgentSessionEventStreamFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgentSessionEventStreamFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventStreamClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentSessionEventStream that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventStreamFindFirstArgs} args - Arguments to find a AgentSessionEventStream
   * @example
   * // Get one AgentSessionEventStream
   * const agentSessionEventStream = await prisma.agentSessionEventStream.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgentSessionEventStreamFindFirstArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventStreamFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventStreamClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentSessionEventStream that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventStreamFindFirstOrThrowArgs} args - Arguments to find a AgentSessionEventStream
   * @example
   * // Get one AgentSessionEventStream
   * const agentSessionEventStream = await prisma.agentSessionEventStream.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgentSessionEventStreamFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventStreamFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventStreamClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgentSessionEventStreams that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventStreamFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgentSessionEventStreams
   * const agentSessionEventStreams = await prisma.agentSessionEventStream.findMany()
   * 
   * // Get first 10 AgentSessionEventStreams
   * const agentSessionEventStreams = await prisma.agentSessionEventStream.findMany({ take: 10 })
   * 
   * // Only select the `sessionId`
   * const agentSessionEventStreamWithSessionIdOnly = await prisma.agentSessionEventStream.findMany({ select: { sessionId: true } })
   * 
   */
  findMany<T extends AgentSessionEventStreamFindManyArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventStreamFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgentSessionEventStream.
   * @param {AgentSessionEventStreamCreateArgs} args - Arguments to create a AgentSessionEventStream.
   * @example
   * // Create one AgentSessionEventStream
   * const AgentSessionEventStream = await prisma.agentSessionEventStream.create({
   *   data: {
   *     // ... data to create a AgentSessionEventStream
   *   }
   * })
   * 
   */
  create<T extends AgentSessionEventStreamCreateArgs>(args: Prisma.SelectSubset<T, AgentSessionEventStreamCreateArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventStreamClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgentSessionEventStreams.
   * @param {AgentSessionEventStreamCreateManyArgs} args - Arguments to create many AgentSessionEventStreams.
   * @example
   * // Create many AgentSessionEventStreams
   * const agentSessionEventStream = await prisma.agentSessionEventStream.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgentSessionEventStreamCreateManyArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventStreamCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AgentSessionEventStreams and returns the data saved in the database.
   * @param {AgentSessionEventStreamCreateManyAndReturnArgs} args - Arguments to create many AgentSessionEventStreams.
   * @example
   * // Create many AgentSessionEventStreams
   * const agentSessionEventStream = await prisma.agentSessionEventStream.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AgentSessionEventStreams and only return the `sessionId`
   * const agentSessionEventStreamWithSessionIdOnly = await prisma.agentSessionEventStream.createManyAndReturn({
   *   select: { sessionId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgentSessionEventStreamCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventStreamCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AgentSessionEventStream.
   * @param {AgentSessionEventStreamDeleteArgs} args - Arguments to delete one AgentSessionEventStream.
   * @example
   * // Delete one AgentSessionEventStream
   * const AgentSessionEventStream = await prisma.agentSessionEventStream.delete({
   *   where: {
   *     // ... filter to delete one AgentSessionEventStream
   *   }
   * })
   * 
   */
  delete<T extends AgentSessionEventStreamDeleteArgs>(args: Prisma.SelectSubset<T, AgentSessionEventStreamDeleteArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventStreamClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgentSessionEventStream.
   * @param {AgentSessionEventStreamUpdateArgs} args - Arguments to update one AgentSessionEventStream.
   * @example
   * // Update one AgentSessionEventStream
   * const agentSessionEventStream = await prisma.agentSessionEventStream.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgentSessionEventStreamUpdateArgs>(args: Prisma.SelectSubset<T, AgentSessionEventStreamUpdateArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventStreamClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgentSessionEventStreams.
   * @param {AgentSessionEventStreamDeleteManyArgs} args - Arguments to filter AgentSessionEventStreams to delete.
   * @example
   * // Delete a few AgentSessionEventStreams
   * const { count } = await prisma.agentSessionEventStream.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgentSessionEventStreamDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventStreamDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentSessionEventStreams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventStreamUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgentSessionEventStreams
   * const agentSessionEventStream = await prisma.agentSessionEventStream.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgentSessionEventStreamUpdateManyArgs>(args: Prisma.SelectSubset<T, AgentSessionEventStreamUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentSessionEventStreams and returns the data updated in the database.
   * @param {AgentSessionEventStreamUpdateManyAndReturnArgs} args - Arguments to update many AgentSessionEventStreams.
   * @example
   * // Update many AgentSessionEventStreams
   * const agentSessionEventStream = await prisma.agentSessionEventStream.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AgentSessionEventStreams and only return the `sessionId`
   * const agentSessionEventStreamWithSessionIdOnly = await prisma.agentSessionEventStream.updateManyAndReturn({
   *   select: { sessionId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgentSessionEventStreamUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgentSessionEventStreamUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AgentSessionEventStream.
   * @param {AgentSessionEventStreamUpsertArgs} args - Arguments to update or create a AgentSessionEventStream.
   * @example
   * // Update or create a AgentSessionEventStream
   * const agentSessionEventStream = await prisma.agentSessionEventStream.upsert({
   *   create: {
   *     // ... data to create a AgentSessionEventStream
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgentSessionEventStream we want to update
   *   }
   * })
   */
  upsert<T extends AgentSessionEventStreamUpsertArgs>(args: Prisma.SelectSubset<T, AgentSessionEventStreamUpsertArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventStreamClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgentSessionEventStreams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventStreamCountArgs} args - Arguments to filter AgentSessionEventStreams to count.
   * @example
   * // Count the number of AgentSessionEventStreams
   * const count = await prisma.agentSessionEventStream.count({
   *   where: {
   *     // ... the filter for the AgentSessionEventStreams we want to count
   *   }
   * })
  **/
  count<T extends AgentSessionEventStreamCountArgs>(
    args?: Prisma.Subset<T, AgentSessionEventStreamCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgentSessionEventStreamCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgentSessionEventStream.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventStreamAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgentSessionEventStreamAggregateArgs>(args: Prisma.Subset<T, AgentSessionEventStreamAggregateArgs>): Prisma.PrismaPromise<GetAgentSessionEventStreamAggregateType<T>>

  /**
   * Group by AgentSessionEventStream.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventStreamGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgentSessionEventStreamGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgentSessionEventStreamGroupByArgs['orderBy'] }
      : { orderBy?: AgentSessionEventStreamGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgentSessionEventStreamGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgentSessionEventStreamGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgentSessionEventStream model
 */
readonly fields: AgentSessionEventStreamFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgentSessionEventStream.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgentSessionEventStreamClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dialogue<T extends Prisma.AgentSessionEventStream$dialogueArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AgentSessionEventStream$dialogueArgs<ExtArgs>>): Prisma.Prisma__DialogueClient<runtime.Types.Result.GetResult<Prisma.$DialoguePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  events<T extends Prisma.AgentSessionEventStream$eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AgentSessionEventStream$eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgentSessionEventStream model
 */
export interface AgentSessionEventStreamFieldRefs {
  readonly sessionId: Prisma.FieldRef<"AgentSessionEventStream", 'String'>
  readonly dialogueId: Prisma.FieldRef<"AgentSessionEventStream", 'String'>
  readonly streamId: Prisma.FieldRef<"AgentSessionEventStream", 'String'>
  readonly sequence: Prisma.FieldRef<"AgentSessionEventStream", 'Int'>
  readonly eventId: Prisma.FieldRef<"AgentSessionEventStream", 'String'>
}
    

// Custom InputTypes
/**
 * AgentSessionEventStream findUnique
 */
export type AgentSessionEventStreamFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEventStream to fetch.
   */
  where: Prisma.AgentSessionEventStreamWhereUniqueInput
}

/**
 * AgentSessionEventStream findUniqueOrThrow
 */
export type AgentSessionEventStreamFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEventStream to fetch.
   */
  where: Prisma.AgentSessionEventStreamWhereUniqueInput
}

/**
 * AgentSessionEventStream findFirst
 */
export type AgentSessionEventStreamFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEventStream to fetch.
   */
  where?: Prisma.AgentSessionEventStreamWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentSessionEventStreams to fetch.
   */
  orderBy?: Prisma.AgentSessionEventStreamOrderByWithRelationInput | Prisma.AgentSessionEventStreamOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentSessionEventStreams.
   */
  cursor?: Prisma.AgentSessionEventStreamWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentSessionEventStreams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentSessionEventStreams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentSessionEventStreams.
   */
  distinct?: Prisma.AgentSessionEventStreamScalarFieldEnum | Prisma.AgentSessionEventStreamScalarFieldEnum[]
}

/**
 * AgentSessionEventStream findFirstOrThrow
 */
export type AgentSessionEventStreamFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEventStream to fetch.
   */
  where?: Prisma.AgentSessionEventStreamWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentSessionEventStreams to fetch.
   */
  orderBy?: Prisma.AgentSessionEventStreamOrderByWithRelationInput | Prisma.AgentSessionEventStreamOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentSessionEventStreams.
   */
  cursor?: Prisma.AgentSessionEventStreamWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentSessionEventStreams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentSessionEventStreams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentSessionEventStreams.
   */
  distinct?: Prisma.AgentSessionEventStreamScalarFieldEnum | Prisma.AgentSessionEventStreamScalarFieldEnum[]
}

/**
 * AgentSessionEventStream findMany
 */
export type AgentSessionEventStreamFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEventStreams to fetch.
   */
  where?: Prisma.AgentSessionEventStreamWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentSessionEventStreams to fetch.
   */
  orderBy?: Prisma.AgentSessionEventStreamOrderByWithRelationInput | Prisma.AgentSessionEventStreamOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgentSessionEventStreams.
   */
  cursor?: Prisma.AgentSessionEventStreamWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentSessionEventStreams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentSessionEventStreams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentSessionEventStreams.
   */
  distinct?: Prisma.AgentSessionEventStreamScalarFieldEnum | Prisma.AgentSessionEventStreamScalarFieldEnum[]
}

/**
 * AgentSessionEventStream create
 */
export type AgentSessionEventStreamCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
  /**
   * The data needed to create a AgentSessionEventStream.
   */
  data: Prisma.XOR<Prisma.AgentSessionEventStreamCreateInput, Prisma.AgentSessionEventStreamUncheckedCreateInput>
}

/**
 * AgentSessionEventStream createMany
 */
export type AgentSessionEventStreamCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgentSessionEventStreams.
   */
  data: Prisma.AgentSessionEventStreamCreateManyInput | Prisma.AgentSessionEventStreamCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AgentSessionEventStream createManyAndReturn
 */
export type AgentSessionEventStreamCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * The data used to create many AgentSessionEventStreams.
   */
  data: Prisma.AgentSessionEventStreamCreateManyInput | Prisma.AgentSessionEventStreamCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AgentSessionEventStream update
 */
export type AgentSessionEventStreamUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
  /**
   * The data needed to update a AgentSessionEventStream.
   */
  data: Prisma.XOR<Prisma.AgentSessionEventStreamUpdateInput, Prisma.AgentSessionEventStreamUncheckedUpdateInput>
  /**
   * Choose, which AgentSessionEventStream to update.
   */
  where: Prisma.AgentSessionEventStreamWhereUniqueInput
}

/**
 * AgentSessionEventStream updateMany
 */
export type AgentSessionEventStreamUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgentSessionEventStreams.
   */
  data: Prisma.XOR<Prisma.AgentSessionEventStreamUpdateManyMutationInput, Prisma.AgentSessionEventStreamUncheckedUpdateManyInput>
  /**
   * Filter which AgentSessionEventStreams to update
   */
  where?: Prisma.AgentSessionEventStreamWhereInput
  /**
   * Limit how many AgentSessionEventStreams to update.
   */
  limit?: number
}

/**
 * AgentSessionEventStream updateManyAndReturn
 */
export type AgentSessionEventStreamUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * The data used to update AgentSessionEventStreams.
   */
  data: Prisma.XOR<Prisma.AgentSessionEventStreamUpdateManyMutationInput, Prisma.AgentSessionEventStreamUncheckedUpdateManyInput>
  /**
   * Filter which AgentSessionEventStreams to update
   */
  where?: Prisma.AgentSessionEventStreamWhereInput
  /**
   * Limit how many AgentSessionEventStreams to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AgentSessionEventStream upsert
 */
export type AgentSessionEventStreamUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
  /**
   * The filter to search for the AgentSessionEventStream to update in case it exists.
   */
  where: Prisma.AgentSessionEventStreamWhereUniqueInput
  /**
   * In case the AgentSessionEventStream found by the `where` argument doesn't exist, create a new AgentSessionEventStream with this data.
   */
  create: Prisma.XOR<Prisma.AgentSessionEventStreamCreateInput, Prisma.AgentSessionEventStreamUncheckedCreateInput>
  /**
   * In case the AgentSessionEventStream was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgentSessionEventStreamUpdateInput, Prisma.AgentSessionEventStreamUncheckedUpdateInput>
}

/**
 * AgentSessionEventStream delete
 */
export type AgentSessionEventStreamDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
  /**
   * Filter which AgentSessionEventStream to delete.
   */
  where: Prisma.AgentSessionEventStreamWhereUniqueInput
}

/**
 * AgentSessionEventStream deleteMany
 */
export type AgentSessionEventStreamDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentSessionEventStreams to delete
   */
  where?: Prisma.AgentSessionEventStreamWhereInput
  /**
   * Limit how many AgentSessionEventStreams to delete.
   */
  limit?: number
}

/**
 * AgentSessionEventStream.dialogue
 */
export type AgentSessionEventStream$dialogueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dialogue
   */
  select?: Prisma.DialogueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dialogue
   */
  omit?: Prisma.DialogueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInclude<ExtArgs> | null
  where?: Prisma.DialogueWhereInput
}

/**
 * AgentSessionEventStream.events
 */
export type AgentSessionEventStream$eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  where?: Prisma.AgentSessionEventWhereInput
  orderBy?: Prisma.AgentSessionEventOrderByWithRelationInput | Prisma.AgentSessionEventOrderByWithRelationInput[]
  cursor?: Prisma.AgentSessionEventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AgentSessionEventScalarFieldEnum | Prisma.AgentSessionEventScalarFieldEnum[]
}

/**
 * AgentSessionEventStream without action
 */
export type AgentSessionEventStreamDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEventStream
   */
  select?: Prisma.AgentSessionEventStreamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEventStream
   */
  omit?: Prisma.AgentSessionEventStreamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventStreamInclude<ExtArgs> | null
}
