
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgentSessionEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AgentSessionEvent
 * 
 */
export type AgentSessionEventModel = runtime.Types.Result.DefaultSelection<Prisma.$AgentSessionEventPayload>

export type AggregateAgentSessionEvent = {
  _count: AgentSessionEventCountAggregateOutputType | null
  _avg: AgentSessionEventAvgAggregateOutputType | null
  _sum: AgentSessionEventSumAggregateOutputType | null
  _min: AgentSessionEventMinAggregateOutputType | null
  _max: AgentSessionEventMaxAggregateOutputType | null
}

export type AgentSessionEventAvgAggregateOutputType = {
  sequence: number | null
}

export type AgentSessionEventSumAggregateOutputType = {
  sequence: number | null
}

export type AgentSessionEventMinAggregateOutputType = {
  eventId: string | null
  sessionId: string | null
  streamId: string | null
  sequence: number | null
  type: string | null
  observedAt: Date | null
  claimedResumeTokenId: string | null
  createdAt: Date | null
}

export type AgentSessionEventMaxAggregateOutputType = {
  eventId: string | null
  sessionId: string | null
  streamId: string | null
  sequence: number | null
  type: string | null
  observedAt: Date | null
  claimedResumeTokenId: string | null
  createdAt: Date | null
}

export type AgentSessionEventCountAggregateOutputType = {
  eventId: number
  sessionId: number
  streamId: number
  sequence: number
  type: number
  payload: number
  observedAt: number
  claimedResumeTokenId: number
  createdAt: number
  _all: number
}


export type AgentSessionEventAvgAggregateInputType = {
  sequence?: true
}

export type AgentSessionEventSumAggregateInputType = {
  sequence?: true
}

export type AgentSessionEventMinAggregateInputType = {
  eventId?: true
  sessionId?: true
  streamId?: true
  sequence?: true
  type?: true
  observedAt?: true
  claimedResumeTokenId?: true
  createdAt?: true
}

export type AgentSessionEventMaxAggregateInputType = {
  eventId?: true
  sessionId?: true
  streamId?: true
  sequence?: true
  type?: true
  observedAt?: true
  claimedResumeTokenId?: true
  createdAt?: true
}

export type AgentSessionEventCountAggregateInputType = {
  eventId?: true
  sessionId?: true
  streamId?: true
  sequence?: true
  type?: true
  payload?: true
  observedAt?: true
  claimedResumeTokenId?: true
  createdAt?: true
  _all?: true
}

export type AgentSessionEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentSessionEvent to aggregate.
   */
  where?: Prisma.AgentSessionEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentSessionEvents to fetch.
   */
  orderBy?: Prisma.AgentSessionEventOrderByWithRelationInput | Prisma.AgentSessionEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgentSessionEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentSessionEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentSessionEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgentSessionEvents
  **/
  _count?: true | AgentSessionEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AgentSessionEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AgentSessionEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgentSessionEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgentSessionEventMaxAggregateInputType
}

export type GetAgentSessionEventAggregateType<T extends AgentSessionEventAggregateArgs> = {
      [P in keyof T & keyof AggregateAgentSessionEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgentSessionEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateAgentSessionEvent[P]>
}




export type AgentSessionEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgentSessionEventWhereInput
  orderBy?: Prisma.AgentSessionEventOrderByWithAggregationInput | Prisma.AgentSessionEventOrderByWithAggregationInput[]
  by: Prisma.AgentSessionEventScalarFieldEnum[] | Prisma.AgentSessionEventScalarFieldEnum
  having?: Prisma.AgentSessionEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgentSessionEventCountAggregateInputType | true
  _avg?: AgentSessionEventAvgAggregateInputType
  _sum?: AgentSessionEventSumAggregateInputType
  _min?: AgentSessionEventMinAggregateInputType
  _max?: AgentSessionEventMaxAggregateInputType
}

export type AgentSessionEventGroupByOutputType = {
  eventId: string
  sessionId: string
  streamId: string
  sequence: number
  type: string
  payload: runtime.JsonValue
  observedAt: Date
  claimedResumeTokenId: string | null
  createdAt: Date
  _count: AgentSessionEventCountAggregateOutputType | null
  _avg: AgentSessionEventAvgAggregateOutputType | null
  _sum: AgentSessionEventSumAggregateOutputType | null
  _min: AgentSessionEventMinAggregateOutputType | null
  _max: AgentSessionEventMaxAggregateOutputType | null
}

export type GetAgentSessionEventGroupByPayload<T extends AgentSessionEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgentSessionEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgentSessionEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgentSessionEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgentSessionEventGroupByOutputType[P]>
      }
    >
  >



export type AgentSessionEventWhereInput = {
  AND?: Prisma.AgentSessionEventWhereInput | Prisma.AgentSessionEventWhereInput[]
  OR?: Prisma.AgentSessionEventWhereInput[]
  NOT?: Prisma.AgentSessionEventWhereInput | Prisma.AgentSessionEventWhereInput[]
  eventId?: Prisma.StringFilter<"AgentSessionEvent"> | string
  sessionId?: Prisma.StringFilter<"AgentSessionEvent"> | string
  streamId?: Prisma.StringFilter<"AgentSessionEvent"> | string
  sequence?: Prisma.IntFilter<"AgentSessionEvent"> | number
  type?: Prisma.StringFilter<"AgentSessionEvent"> | string
  payload?: Prisma.JsonFilter<"AgentSessionEvent">
  observedAt?: Prisma.DateTimeFilter<"AgentSessionEvent"> | Date | string
  claimedResumeTokenId?: Prisma.StringNullableFilter<"AgentSessionEvent"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AgentSessionEvent"> | Date | string
  session?: Prisma.XOR<Prisma.AgentSessionEventStreamScalarRelationFilter, Prisma.AgentSessionEventStreamWhereInput>
}

export type AgentSessionEventOrderByWithRelationInput = {
  eventId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  type?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  observedAt?: Prisma.SortOrder
  claimedResumeTokenId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  session?: Prisma.AgentSessionEventStreamOrderByWithRelationInput
}

export type AgentSessionEventWhereUniqueInput = Prisma.AtLeast<{
  eventId?: string
  claimedResumeTokenId?: string
  sessionId_streamId_sequence?: Prisma.AgentSessionEventSessionIdStreamIdSequenceCompoundUniqueInput
  AND?: Prisma.AgentSessionEventWhereInput | Prisma.AgentSessionEventWhereInput[]
  OR?: Prisma.AgentSessionEventWhereInput[]
  NOT?: Prisma.AgentSessionEventWhereInput | Prisma.AgentSessionEventWhereInput[]
  sessionId?: Prisma.StringFilter<"AgentSessionEvent"> | string
  streamId?: Prisma.StringFilter<"AgentSessionEvent"> | string
  sequence?: Prisma.IntFilter<"AgentSessionEvent"> | number
  type?: Prisma.StringFilter<"AgentSessionEvent"> | string
  payload?: Prisma.JsonFilter<"AgentSessionEvent">
  observedAt?: Prisma.DateTimeFilter<"AgentSessionEvent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"AgentSessionEvent"> | Date | string
  session?: Prisma.XOR<Prisma.AgentSessionEventStreamScalarRelationFilter, Prisma.AgentSessionEventStreamWhereInput>
}, "eventId" | "claimedResumeTokenId" | "sessionId_streamId_sequence">

export type AgentSessionEventOrderByWithAggregationInput = {
  eventId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  type?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  observedAt?: Prisma.SortOrder
  claimedResumeTokenId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AgentSessionEventCountOrderByAggregateInput
  _avg?: Prisma.AgentSessionEventAvgOrderByAggregateInput
  _max?: Prisma.AgentSessionEventMaxOrderByAggregateInput
  _min?: Prisma.AgentSessionEventMinOrderByAggregateInput
  _sum?: Prisma.AgentSessionEventSumOrderByAggregateInput
}

export type AgentSessionEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgentSessionEventScalarWhereWithAggregatesInput | Prisma.AgentSessionEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgentSessionEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgentSessionEventScalarWhereWithAggregatesInput | Prisma.AgentSessionEventScalarWhereWithAggregatesInput[]
  eventId?: Prisma.StringWithAggregatesFilter<"AgentSessionEvent"> | string
  sessionId?: Prisma.StringWithAggregatesFilter<"AgentSessionEvent"> | string
  streamId?: Prisma.StringWithAggregatesFilter<"AgentSessionEvent"> | string
  sequence?: Prisma.IntWithAggregatesFilter<"AgentSessionEvent"> | number
  type?: Prisma.StringWithAggregatesFilter<"AgentSessionEvent"> | string
  payload?: Prisma.JsonWithAggregatesFilter<"AgentSessionEvent">
  observedAt?: Prisma.DateTimeWithAggregatesFilter<"AgentSessionEvent"> | Date | string
  claimedResumeTokenId?: Prisma.StringNullableWithAggregatesFilter<"AgentSessionEvent"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AgentSessionEvent"> | Date | string
}

export type AgentSessionEventCreateInput = {
  eventId: string
  streamId: string
  sequence: number
  type: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt: Date | string
  claimedResumeTokenId?: string | null
  createdAt?: Date | string
  session: Prisma.AgentSessionEventStreamCreateNestedOneWithoutEventsInput
}

export type AgentSessionEventUncheckedCreateInput = {
  eventId: string
  sessionId: string
  streamId: string
  sequence: number
  type: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt: Date | string
  claimedResumeTokenId?: string | null
  createdAt?: Date | string
}

export type AgentSessionEventUpdateInput = {
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  claimedResumeTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.AgentSessionEventStreamUpdateOneRequiredWithoutEventsNestedInput
}

export type AgentSessionEventUncheckedUpdateInput = {
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  claimedResumeTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentSessionEventCreateManyInput = {
  eventId: string
  sessionId: string
  streamId: string
  sequence: number
  type: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt: Date | string
  claimedResumeTokenId?: string | null
  createdAt?: Date | string
}

export type AgentSessionEventUpdateManyMutationInput = {
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  claimedResumeTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentSessionEventUncheckedUpdateManyInput = {
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  claimedResumeTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentSessionEventListRelationFilter = {
  every?: Prisma.AgentSessionEventWhereInput
  some?: Prisma.AgentSessionEventWhereInput
  none?: Prisma.AgentSessionEventWhereInput
}

export type AgentSessionEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AgentSessionEventSessionIdStreamIdSequenceCompoundUniqueInput = {
  sessionId: string
  streamId: string
  sequence: number
}

export type AgentSessionEventCountOrderByAggregateInput = {
  eventId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  type?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  observedAt?: Prisma.SortOrder
  claimedResumeTokenId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentSessionEventAvgOrderByAggregateInput = {
  sequence?: Prisma.SortOrder
}

export type AgentSessionEventMaxOrderByAggregateInput = {
  eventId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  type?: Prisma.SortOrder
  observedAt?: Prisma.SortOrder
  claimedResumeTokenId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentSessionEventMinOrderByAggregateInput = {
  eventId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  streamId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  type?: Prisma.SortOrder
  observedAt?: Prisma.SortOrder
  claimedResumeTokenId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentSessionEventSumOrderByAggregateInput = {
  sequence?: Prisma.SortOrder
}

export type AgentSessionEventCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventCreateWithoutSessionInput, Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput> | Prisma.AgentSessionEventCreateWithoutSessionInput[] | Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AgentSessionEventCreateOrConnectWithoutSessionInput | Prisma.AgentSessionEventCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.AgentSessionEventCreateManySessionInputEnvelope
  connect?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
}

export type AgentSessionEventUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventCreateWithoutSessionInput, Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput> | Prisma.AgentSessionEventCreateWithoutSessionInput[] | Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AgentSessionEventCreateOrConnectWithoutSessionInput | Prisma.AgentSessionEventCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.AgentSessionEventCreateManySessionInputEnvelope
  connect?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
}

export type AgentSessionEventUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventCreateWithoutSessionInput, Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput> | Prisma.AgentSessionEventCreateWithoutSessionInput[] | Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AgentSessionEventCreateOrConnectWithoutSessionInput | Prisma.AgentSessionEventCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.AgentSessionEventUpsertWithWhereUniqueWithoutSessionInput | Prisma.AgentSessionEventUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.AgentSessionEventCreateManySessionInputEnvelope
  set?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
  disconnect?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
  delete?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
  connect?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
  update?: Prisma.AgentSessionEventUpdateWithWhereUniqueWithoutSessionInput | Prisma.AgentSessionEventUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.AgentSessionEventUpdateManyWithWhereWithoutSessionInput | Prisma.AgentSessionEventUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.AgentSessionEventScalarWhereInput | Prisma.AgentSessionEventScalarWhereInput[]
}

export type AgentSessionEventUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.AgentSessionEventCreateWithoutSessionInput, Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput> | Prisma.AgentSessionEventCreateWithoutSessionInput[] | Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.AgentSessionEventCreateOrConnectWithoutSessionInput | Prisma.AgentSessionEventCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.AgentSessionEventUpsertWithWhereUniqueWithoutSessionInput | Prisma.AgentSessionEventUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.AgentSessionEventCreateManySessionInputEnvelope
  set?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
  disconnect?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
  delete?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
  connect?: Prisma.AgentSessionEventWhereUniqueInput | Prisma.AgentSessionEventWhereUniqueInput[]
  update?: Prisma.AgentSessionEventUpdateWithWhereUniqueWithoutSessionInput | Prisma.AgentSessionEventUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.AgentSessionEventUpdateManyWithWhereWithoutSessionInput | Prisma.AgentSessionEventUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.AgentSessionEventScalarWhereInput | Prisma.AgentSessionEventScalarWhereInput[]
}

export type AgentSessionEventCreateWithoutSessionInput = {
  eventId: string
  streamId: string
  sequence: number
  type: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt: Date | string
  claimedResumeTokenId?: string | null
  createdAt?: Date | string
}

export type AgentSessionEventUncheckedCreateWithoutSessionInput = {
  eventId: string
  streamId: string
  sequence: number
  type: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt: Date | string
  claimedResumeTokenId?: string | null
  createdAt?: Date | string
}

export type AgentSessionEventCreateOrConnectWithoutSessionInput = {
  where: Prisma.AgentSessionEventWhereUniqueInput
  create: Prisma.XOR<Prisma.AgentSessionEventCreateWithoutSessionInput, Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput>
}

export type AgentSessionEventCreateManySessionInputEnvelope = {
  data: Prisma.AgentSessionEventCreateManySessionInput | Prisma.AgentSessionEventCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type AgentSessionEventUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.AgentSessionEventWhereUniqueInput
  update: Prisma.XOR<Prisma.AgentSessionEventUpdateWithoutSessionInput, Prisma.AgentSessionEventUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.AgentSessionEventCreateWithoutSessionInput, Prisma.AgentSessionEventUncheckedCreateWithoutSessionInput>
}

export type AgentSessionEventUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.AgentSessionEventWhereUniqueInput
  data: Prisma.XOR<Prisma.AgentSessionEventUpdateWithoutSessionInput, Prisma.AgentSessionEventUncheckedUpdateWithoutSessionInput>
}

export type AgentSessionEventUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.AgentSessionEventScalarWhereInput
  data: Prisma.XOR<Prisma.AgentSessionEventUpdateManyMutationInput, Prisma.AgentSessionEventUncheckedUpdateManyWithoutSessionInput>
}

export type AgentSessionEventScalarWhereInput = {
  AND?: Prisma.AgentSessionEventScalarWhereInput | Prisma.AgentSessionEventScalarWhereInput[]
  OR?: Prisma.AgentSessionEventScalarWhereInput[]
  NOT?: Prisma.AgentSessionEventScalarWhereInput | Prisma.AgentSessionEventScalarWhereInput[]
  eventId?: Prisma.StringFilter<"AgentSessionEvent"> | string
  sessionId?: Prisma.StringFilter<"AgentSessionEvent"> | string
  streamId?: Prisma.StringFilter<"AgentSessionEvent"> | string
  sequence?: Prisma.IntFilter<"AgentSessionEvent"> | number
  type?: Prisma.StringFilter<"AgentSessionEvent"> | string
  payload?: Prisma.JsonFilter<"AgentSessionEvent">
  observedAt?: Prisma.DateTimeFilter<"AgentSessionEvent"> | Date | string
  claimedResumeTokenId?: Prisma.StringNullableFilter<"AgentSessionEvent"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AgentSessionEvent"> | Date | string
}

export type AgentSessionEventCreateManySessionInput = {
  eventId: string
  streamId: string
  sequence: number
  type: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt: Date | string
  claimedResumeTokenId?: string | null
  createdAt?: Date | string
}

export type AgentSessionEventUpdateWithoutSessionInput = {
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  claimedResumeTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentSessionEventUncheckedUpdateWithoutSessionInput = {
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  claimedResumeTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentSessionEventUncheckedUpdateManyWithoutSessionInput = {
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  streamId?: Prisma.StringFieldUpdateOperationsInput | string
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  observedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  claimedResumeTokenId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AgentSessionEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  eventId?: boolean
  sessionId?: boolean
  streamId?: boolean
  sequence?: boolean
  type?: boolean
  payload?: boolean
  observedAt?: boolean
  claimedResumeTokenId?: boolean
  createdAt?: boolean
  session?: boolean | Prisma.AgentSessionEventStreamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agentSessionEvent"]>

export type AgentSessionEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  eventId?: boolean
  sessionId?: boolean
  streamId?: boolean
  sequence?: boolean
  type?: boolean
  payload?: boolean
  observedAt?: boolean
  claimedResumeTokenId?: boolean
  createdAt?: boolean
  session?: boolean | Prisma.AgentSessionEventStreamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agentSessionEvent"]>

export type AgentSessionEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  eventId?: boolean
  sessionId?: boolean
  streamId?: boolean
  sequence?: boolean
  type?: boolean
  payload?: boolean
  observedAt?: boolean
  claimedResumeTokenId?: boolean
  createdAt?: boolean
  session?: boolean | Prisma.AgentSessionEventStreamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agentSessionEvent"]>

export type AgentSessionEventSelectScalar = {
  eventId?: boolean
  sessionId?: boolean
  streamId?: boolean
  sequence?: boolean
  type?: boolean
  payload?: boolean
  observedAt?: boolean
  claimedResumeTokenId?: boolean
  createdAt?: boolean
}

export type AgentSessionEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"eventId" | "sessionId" | "streamId" | "sequence" | "type" | "payload" | "observedAt" | "claimedResumeTokenId" | "createdAt", ExtArgs["result"]["agentSessionEvent"]>
export type AgentSessionEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.AgentSessionEventStreamDefaultArgs<ExtArgs>
}
export type AgentSessionEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.AgentSessionEventStreamDefaultArgs<ExtArgs>
}
export type AgentSessionEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.AgentSessionEventStreamDefaultArgs<ExtArgs>
}

export type $AgentSessionEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgentSessionEvent"
  objects: {
    session: Prisma.$AgentSessionEventStreamPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    eventId: string
    sessionId: string
    streamId: string
    sequence: number
    type: string
    payload: runtime.JsonValue
    observedAt: Date
    claimedResumeTokenId: string | null
    createdAt: Date
  }, ExtArgs["result"]["agentSessionEvent"]>
  composites: {}
}

export type AgentSessionEventGetPayload<S extends boolean | null | undefined | AgentSessionEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload, S>

export type AgentSessionEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgentSessionEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgentSessionEventCountAggregateInputType | true
  }

export interface AgentSessionEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgentSessionEvent'], meta: { name: 'AgentSessionEvent' } }
  /**
   * Find zero or one AgentSessionEvent that matches the filter.
   * @param {AgentSessionEventFindUniqueArgs} args - Arguments to find a AgentSessionEvent
   * @example
   * // Get one AgentSessionEvent
   * const agentSessionEvent = await prisma.agentSessionEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgentSessionEventFindUniqueArgs>(args: Prisma.SelectSubset<T, AgentSessionEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgentSessionEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgentSessionEventFindUniqueOrThrowArgs} args - Arguments to find a AgentSessionEvent
   * @example
   * // Get one AgentSessionEvent
   * const agentSessionEvent = await prisma.agentSessionEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgentSessionEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgentSessionEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentSessionEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventFindFirstArgs} args - Arguments to find a AgentSessionEvent
   * @example
   * // Get one AgentSessionEvent
   * const agentSessionEvent = await prisma.agentSessionEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgentSessionEventFindFirstArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentSessionEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventFindFirstOrThrowArgs} args - Arguments to find a AgentSessionEvent
   * @example
   * // Get one AgentSessionEvent
   * const agentSessionEvent = await prisma.agentSessionEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgentSessionEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgentSessionEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgentSessionEvents
   * const agentSessionEvents = await prisma.agentSessionEvent.findMany()
   * 
   * // Get first 10 AgentSessionEvents
   * const agentSessionEvents = await prisma.agentSessionEvent.findMany({ take: 10 })
   * 
   * // Only select the `eventId`
   * const agentSessionEventWithEventIdOnly = await prisma.agentSessionEvent.findMany({ select: { eventId: true } })
   * 
   */
  findMany<T extends AgentSessionEventFindManyArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgentSessionEvent.
   * @param {AgentSessionEventCreateArgs} args - Arguments to create a AgentSessionEvent.
   * @example
   * // Create one AgentSessionEvent
   * const AgentSessionEvent = await prisma.agentSessionEvent.create({
   *   data: {
   *     // ... data to create a AgentSessionEvent
   *   }
   * })
   * 
   */
  create<T extends AgentSessionEventCreateArgs>(args: Prisma.SelectSubset<T, AgentSessionEventCreateArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgentSessionEvents.
   * @param {AgentSessionEventCreateManyArgs} args - Arguments to create many AgentSessionEvents.
   * @example
   * // Create many AgentSessionEvents
   * const agentSessionEvent = await prisma.agentSessionEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgentSessionEventCreateManyArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AgentSessionEvents and returns the data saved in the database.
   * @param {AgentSessionEventCreateManyAndReturnArgs} args - Arguments to create many AgentSessionEvents.
   * @example
   * // Create many AgentSessionEvents
   * const agentSessionEvent = await prisma.agentSessionEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AgentSessionEvents and only return the `eventId`
   * const agentSessionEventWithEventIdOnly = await prisma.agentSessionEvent.createManyAndReturn({
   *   select: { eventId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgentSessionEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AgentSessionEvent.
   * @param {AgentSessionEventDeleteArgs} args - Arguments to delete one AgentSessionEvent.
   * @example
   * // Delete one AgentSessionEvent
   * const AgentSessionEvent = await prisma.agentSessionEvent.delete({
   *   where: {
   *     // ... filter to delete one AgentSessionEvent
   *   }
   * })
   * 
   */
  delete<T extends AgentSessionEventDeleteArgs>(args: Prisma.SelectSubset<T, AgentSessionEventDeleteArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgentSessionEvent.
   * @param {AgentSessionEventUpdateArgs} args - Arguments to update one AgentSessionEvent.
   * @example
   * // Update one AgentSessionEvent
   * const agentSessionEvent = await prisma.agentSessionEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgentSessionEventUpdateArgs>(args: Prisma.SelectSubset<T, AgentSessionEventUpdateArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgentSessionEvents.
   * @param {AgentSessionEventDeleteManyArgs} args - Arguments to filter AgentSessionEvents to delete.
   * @example
   * // Delete a few AgentSessionEvents
   * const { count } = await prisma.agentSessionEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgentSessionEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgentSessionEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentSessionEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgentSessionEvents
   * const agentSessionEvent = await prisma.agentSessionEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgentSessionEventUpdateManyArgs>(args: Prisma.SelectSubset<T, AgentSessionEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentSessionEvents and returns the data updated in the database.
   * @param {AgentSessionEventUpdateManyAndReturnArgs} args - Arguments to update many AgentSessionEvents.
   * @example
   * // Update many AgentSessionEvents
   * const agentSessionEvent = await prisma.agentSessionEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AgentSessionEvents and only return the `eventId`
   * const agentSessionEventWithEventIdOnly = await prisma.agentSessionEvent.updateManyAndReturn({
   *   select: { eventId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgentSessionEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgentSessionEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AgentSessionEvent.
   * @param {AgentSessionEventUpsertArgs} args - Arguments to update or create a AgentSessionEvent.
   * @example
   * // Update or create a AgentSessionEvent
   * const agentSessionEvent = await prisma.agentSessionEvent.upsert({
   *   create: {
   *     // ... data to create a AgentSessionEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgentSessionEvent we want to update
   *   }
   * })
   */
  upsert<T extends AgentSessionEventUpsertArgs>(args: Prisma.SelectSubset<T, AgentSessionEventUpsertArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgentSessionEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventCountArgs} args - Arguments to filter AgentSessionEvents to count.
   * @example
   * // Count the number of AgentSessionEvents
   * const count = await prisma.agentSessionEvent.count({
   *   where: {
   *     // ... the filter for the AgentSessionEvents we want to count
   *   }
   * })
  **/
  count<T extends AgentSessionEventCountArgs>(
    args?: Prisma.Subset<T, AgentSessionEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgentSessionEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgentSessionEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgentSessionEventAggregateArgs>(args: Prisma.Subset<T, AgentSessionEventAggregateArgs>): Prisma.PrismaPromise<GetAgentSessionEventAggregateType<T>>

  /**
   * Group by AgentSessionEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentSessionEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgentSessionEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgentSessionEventGroupByArgs['orderBy'] }
      : { orderBy?: AgentSessionEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgentSessionEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgentSessionEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgentSessionEvent model
 */
readonly fields: AgentSessionEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgentSessionEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgentSessionEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.AgentSessionEventStreamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AgentSessionEventStreamDefaultArgs<ExtArgs>>): Prisma.Prisma__AgentSessionEventStreamClient<runtime.Types.Result.GetResult<Prisma.$AgentSessionEventStreamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgentSessionEvent model
 */
export interface AgentSessionEventFieldRefs {
  readonly eventId: Prisma.FieldRef<"AgentSessionEvent", 'String'>
  readonly sessionId: Prisma.FieldRef<"AgentSessionEvent", 'String'>
  readonly streamId: Prisma.FieldRef<"AgentSessionEvent", 'String'>
  readonly sequence: Prisma.FieldRef<"AgentSessionEvent", 'Int'>
  readonly type: Prisma.FieldRef<"AgentSessionEvent", 'String'>
  readonly payload: Prisma.FieldRef<"AgentSessionEvent", 'Json'>
  readonly observedAt: Prisma.FieldRef<"AgentSessionEvent", 'DateTime'>
  readonly claimedResumeTokenId: Prisma.FieldRef<"AgentSessionEvent", 'String'>
  readonly createdAt: Prisma.FieldRef<"AgentSessionEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AgentSessionEvent findUnique
 */
export type AgentSessionEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEvent to fetch.
   */
  where: Prisma.AgentSessionEventWhereUniqueInput
}

/**
 * AgentSessionEvent findUniqueOrThrow
 */
export type AgentSessionEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEvent to fetch.
   */
  where: Prisma.AgentSessionEventWhereUniqueInput
}

/**
 * AgentSessionEvent findFirst
 */
export type AgentSessionEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEvent to fetch.
   */
  where?: Prisma.AgentSessionEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentSessionEvents to fetch.
   */
  orderBy?: Prisma.AgentSessionEventOrderByWithRelationInput | Prisma.AgentSessionEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentSessionEvents.
   */
  cursor?: Prisma.AgentSessionEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentSessionEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentSessionEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentSessionEvents.
   */
  distinct?: Prisma.AgentSessionEventScalarFieldEnum | Prisma.AgentSessionEventScalarFieldEnum[]
}

/**
 * AgentSessionEvent findFirstOrThrow
 */
export type AgentSessionEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEvent to fetch.
   */
  where?: Prisma.AgentSessionEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentSessionEvents to fetch.
   */
  orderBy?: Prisma.AgentSessionEventOrderByWithRelationInput | Prisma.AgentSessionEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentSessionEvents.
   */
  cursor?: Prisma.AgentSessionEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentSessionEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentSessionEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentSessionEvents.
   */
  distinct?: Prisma.AgentSessionEventScalarFieldEnum | Prisma.AgentSessionEventScalarFieldEnum[]
}

/**
 * AgentSessionEvent findMany
 */
export type AgentSessionEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  /**
   * Filter, which AgentSessionEvents to fetch.
   */
  where?: Prisma.AgentSessionEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentSessionEvents to fetch.
   */
  orderBy?: Prisma.AgentSessionEventOrderByWithRelationInput | Prisma.AgentSessionEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgentSessionEvents.
   */
  cursor?: Prisma.AgentSessionEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentSessionEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentSessionEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentSessionEvents.
   */
  distinct?: Prisma.AgentSessionEventScalarFieldEnum | Prisma.AgentSessionEventScalarFieldEnum[]
}

/**
 * AgentSessionEvent create
 */
export type AgentSessionEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  /**
   * The data needed to create a AgentSessionEvent.
   */
  data: Prisma.XOR<Prisma.AgentSessionEventCreateInput, Prisma.AgentSessionEventUncheckedCreateInput>
}

/**
 * AgentSessionEvent createMany
 */
export type AgentSessionEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgentSessionEvents.
   */
  data: Prisma.AgentSessionEventCreateManyInput | Prisma.AgentSessionEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AgentSessionEvent createManyAndReturn
 */
export type AgentSessionEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * The data used to create many AgentSessionEvents.
   */
  data: Prisma.AgentSessionEventCreateManyInput | Prisma.AgentSessionEventCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AgentSessionEvent update
 */
export type AgentSessionEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  /**
   * The data needed to update a AgentSessionEvent.
   */
  data: Prisma.XOR<Prisma.AgentSessionEventUpdateInput, Prisma.AgentSessionEventUncheckedUpdateInput>
  /**
   * Choose, which AgentSessionEvent to update.
   */
  where: Prisma.AgentSessionEventWhereUniqueInput
}

/**
 * AgentSessionEvent updateMany
 */
export type AgentSessionEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgentSessionEvents.
   */
  data: Prisma.XOR<Prisma.AgentSessionEventUpdateManyMutationInput, Prisma.AgentSessionEventUncheckedUpdateManyInput>
  /**
   * Filter which AgentSessionEvents to update
   */
  where?: Prisma.AgentSessionEventWhereInput
  /**
   * Limit how many AgentSessionEvents to update.
   */
  limit?: number
}

/**
 * AgentSessionEvent updateManyAndReturn
 */
export type AgentSessionEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * The data used to update AgentSessionEvents.
   */
  data: Prisma.XOR<Prisma.AgentSessionEventUpdateManyMutationInput, Prisma.AgentSessionEventUncheckedUpdateManyInput>
  /**
   * Filter which AgentSessionEvents to update
   */
  where?: Prisma.AgentSessionEventWhereInput
  /**
   * Limit how many AgentSessionEvents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AgentSessionEvent upsert
 */
export type AgentSessionEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  /**
   * The filter to search for the AgentSessionEvent to update in case it exists.
   */
  where: Prisma.AgentSessionEventWhereUniqueInput
  /**
   * In case the AgentSessionEvent found by the `where` argument doesn't exist, create a new AgentSessionEvent with this data.
   */
  create: Prisma.XOR<Prisma.AgentSessionEventCreateInput, Prisma.AgentSessionEventUncheckedCreateInput>
  /**
   * In case the AgentSessionEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgentSessionEventUpdateInput, Prisma.AgentSessionEventUncheckedUpdateInput>
}

/**
 * AgentSessionEvent delete
 */
export type AgentSessionEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
  /**
   * Filter which AgentSessionEvent to delete.
   */
  where: Prisma.AgentSessionEventWhereUniqueInput
}

/**
 * AgentSessionEvent deleteMany
 */
export type AgentSessionEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentSessionEvents to delete
   */
  where?: Prisma.AgentSessionEventWhereInput
  /**
   * Limit how many AgentSessionEvents to delete.
   */
  limit?: number
}

/**
 * AgentSessionEvent without action
 */
export type AgentSessionEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentSessionEvent
   */
  select?: Prisma.AgentSessionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentSessionEvent
   */
  omit?: Prisma.AgentSessionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentSessionEventInclude<ExtArgs> | null
}
