
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DbosOperationOutput` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DbosOperationOutput
 * 
 */
export type DbosOperationOutputModel = runtime.Types.Result.DefaultSelection<Prisma.$DbosOperationOutputPayload>

export type AggregateDbosOperationOutput = {
  _count: DbosOperationOutputCountAggregateOutputType | null
  _avg: DbosOperationOutputAvgAggregateOutputType | null
  _sum: DbosOperationOutputSumAggregateOutputType | null
  _min: DbosOperationOutputMinAggregateOutputType | null
  _max: DbosOperationOutputMaxAggregateOutputType | null
}

export type DbosOperationOutputAvgAggregateOutputType = {
  functionId: number | null
}

export type DbosOperationOutputSumAggregateOutputType = {
  functionId: number | null
}

export type DbosOperationOutputMinAggregateOutputType = {
  workflowUuid: string | null
  functionId: number | null
  functionName: string | null
}

export type DbosOperationOutputMaxAggregateOutputType = {
  workflowUuid: string | null
  functionId: number | null
  functionName: string | null
}

export type DbosOperationOutputCountAggregateOutputType = {
  workflowUuid: number
  functionId: number
  functionName: number
  _all: number
}


export type DbosOperationOutputAvgAggregateInputType = {
  functionId?: true
}

export type DbosOperationOutputSumAggregateInputType = {
  functionId?: true
}

export type DbosOperationOutputMinAggregateInputType = {
  workflowUuid?: true
  functionId?: true
  functionName?: true
}

export type DbosOperationOutputMaxAggregateInputType = {
  workflowUuid?: true
  functionId?: true
  functionName?: true
}

export type DbosOperationOutputCountAggregateInputType = {
  workflowUuid?: true
  functionId?: true
  functionName?: true
  _all?: true
}

export type DbosOperationOutputAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbosOperationOutput to aggregate.
   */
  where?: Prisma.DbosOperationOutputWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbosOperationOutputs to fetch.
   */
  orderBy?: Prisma.DbosOperationOutputOrderByWithRelationInput | Prisma.DbosOperationOutputOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DbosOperationOutputWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbosOperationOutputs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbosOperationOutputs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DbosOperationOutputs
  **/
  _count?: true | DbosOperationOutputCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DbosOperationOutputAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DbosOperationOutputSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DbosOperationOutputMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DbosOperationOutputMaxAggregateInputType
}

export type GetDbosOperationOutputAggregateType<T extends DbosOperationOutputAggregateArgs> = {
      [P in keyof T & keyof AggregateDbosOperationOutput]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDbosOperationOutput[P]>
    : Prisma.GetScalarType<T[P], AggregateDbosOperationOutput[P]>
}




export type DbosOperationOutputGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DbosOperationOutputWhereInput
  orderBy?: Prisma.DbosOperationOutputOrderByWithAggregationInput | Prisma.DbosOperationOutputOrderByWithAggregationInput[]
  by: Prisma.DbosOperationOutputScalarFieldEnum[] | Prisma.DbosOperationOutputScalarFieldEnum
  having?: Prisma.DbosOperationOutputScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DbosOperationOutputCountAggregateInputType | true
  _avg?: DbosOperationOutputAvgAggregateInputType
  _sum?: DbosOperationOutputSumAggregateInputType
  _min?: DbosOperationOutputMinAggregateInputType
  _max?: DbosOperationOutputMaxAggregateInputType
}

export type DbosOperationOutputGroupByOutputType = {
  workflowUuid: string
  functionId: number
  functionName: string | null
  _count: DbosOperationOutputCountAggregateOutputType | null
  _avg: DbosOperationOutputAvgAggregateOutputType | null
  _sum: DbosOperationOutputSumAggregateOutputType | null
  _min: DbosOperationOutputMinAggregateOutputType | null
  _max: DbosOperationOutputMaxAggregateOutputType | null
}

export type GetDbosOperationOutputGroupByPayload<T extends DbosOperationOutputGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DbosOperationOutputGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DbosOperationOutputGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DbosOperationOutputGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DbosOperationOutputGroupByOutputType[P]>
      }
    >
  >



export type DbosOperationOutputWhereInput = {
  AND?: Prisma.DbosOperationOutputWhereInput | Prisma.DbosOperationOutputWhereInput[]
  OR?: Prisma.DbosOperationOutputWhereInput[]
  NOT?: Prisma.DbosOperationOutputWhereInput | Prisma.DbosOperationOutputWhereInput[]
  workflowUuid?: Prisma.StringFilter<"DbosOperationOutput"> | string
  functionId?: Prisma.IntFilter<"DbosOperationOutput"> | number
  functionName?: Prisma.StringNullableFilter<"DbosOperationOutput"> | string | null
}

export type DbosOperationOutputOrderByWithRelationInput = {
  workflowUuid?: Prisma.SortOrder
  functionId?: Prisma.SortOrder
  functionName?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type DbosOperationOutputWhereUniqueInput = Prisma.AtLeast<{
  workflowUuid_functionId?: Prisma.DbosOperationOutputWorkflowUuidFunctionIdCompoundUniqueInput
  AND?: Prisma.DbosOperationOutputWhereInput | Prisma.DbosOperationOutputWhereInput[]
  OR?: Prisma.DbosOperationOutputWhereInput[]
  NOT?: Prisma.DbosOperationOutputWhereInput | Prisma.DbosOperationOutputWhereInput[]
  workflowUuid?: Prisma.StringFilter<"DbosOperationOutput"> | string
  functionId?: Prisma.IntFilter<"DbosOperationOutput"> | number
  functionName?: Prisma.StringNullableFilter<"DbosOperationOutput"> | string | null
}, "workflowUuid_functionId">

export type DbosOperationOutputOrderByWithAggregationInput = {
  workflowUuid?: Prisma.SortOrder
  functionId?: Prisma.SortOrder
  functionName?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DbosOperationOutputCountOrderByAggregateInput
  _avg?: Prisma.DbosOperationOutputAvgOrderByAggregateInput
  _max?: Prisma.DbosOperationOutputMaxOrderByAggregateInput
  _min?: Prisma.DbosOperationOutputMinOrderByAggregateInput
  _sum?: Prisma.DbosOperationOutputSumOrderByAggregateInput
}

export type DbosOperationOutputScalarWhereWithAggregatesInput = {
  AND?: Prisma.DbosOperationOutputScalarWhereWithAggregatesInput | Prisma.DbosOperationOutputScalarWhereWithAggregatesInput[]
  OR?: Prisma.DbosOperationOutputScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DbosOperationOutputScalarWhereWithAggregatesInput | Prisma.DbosOperationOutputScalarWhereWithAggregatesInput[]
  workflowUuid?: Prisma.StringWithAggregatesFilter<"DbosOperationOutput"> | string
  functionId?: Prisma.IntWithAggregatesFilter<"DbosOperationOutput"> | number
  functionName?: Prisma.StringNullableWithAggregatesFilter<"DbosOperationOutput"> | string | null
}

export type DbosOperationOutputCreateInput = {
  workflowUuid: string
  functionId: number
  functionName?: string | null
}

export type DbosOperationOutputUncheckedCreateInput = {
  workflowUuid: string
  functionId: number
  functionName?: string | null
}

export type DbosOperationOutputUpdateInput = {
  workflowUuid?: Prisma.StringFieldUpdateOperationsInput | string
  functionId?: Prisma.IntFieldUpdateOperationsInput | number
  functionName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DbosOperationOutputUncheckedUpdateInput = {
  workflowUuid?: Prisma.StringFieldUpdateOperationsInput | string
  functionId?: Prisma.IntFieldUpdateOperationsInput | number
  functionName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DbosOperationOutputCreateManyInput = {
  workflowUuid: string
  functionId: number
  functionName?: string | null
}

export type DbosOperationOutputUpdateManyMutationInput = {
  workflowUuid?: Prisma.StringFieldUpdateOperationsInput | string
  functionId?: Prisma.IntFieldUpdateOperationsInput | number
  functionName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DbosOperationOutputUncheckedUpdateManyInput = {
  workflowUuid?: Prisma.StringFieldUpdateOperationsInput | string
  functionId?: Prisma.IntFieldUpdateOperationsInput | number
  functionName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DbosOperationOutputWorkflowUuidFunctionIdCompoundUniqueInput = {
  workflowUuid: string
  functionId: number
}

export type DbosOperationOutputCountOrderByAggregateInput = {
  workflowUuid?: Prisma.SortOrder
  functionId?: Prisma.SortOrder
  functionName?: Prisma.SortOrder
}

export type DbosOperationOutputAvgOrderByAggregateInput = {
  functionId?: Prisma.SortOrder
}

export type DbosOperationOutputMaxOrderByAggregateInput = {
  workflowUuid?: Prisma.SortOrder
  functionId?: Prisma.SortOrder
  functionName?: Prisma.SortOrder
}

export type DbosOperationOutputMinOrderByAggregateInput = {
  workflowUuid?: Prisma.SortOrder
  functionId?: Prisma.SortOrder
  functionName?: Prisma.SortOrder
}

export type DbosOperationOutputSumOrderByAggregateInput = {
  functionId?: Prisma.SortOrder
}



export type DbosOperationOutputSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workflowUuid?: boolean
  functionId?: boolean
  functionName?: boolean
}, ExtArgs["result"]["dbosOperationOutput"]>

export type DbosOperationOutputSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workflowUuid?: boolean
  functionId?: boolean
  functionName?: boolean
}, ExtArgs["result"]["dbosOperationOutput"]>

export type DbosOperationOutputSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  workflowUuid?: boolean
  functionId?: boolean
  functionName?: boolean
}, ExtArgs["result"]["dbosOperationOutput"]>

export type DbosOperationOutputSelectScalar = {
  workflowUuid?: boolean
  functionId?: boolean
  functionName?: boolean
}

export type DbosOperationOutputOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"workflowUuid" | "functionId" | "functionName", ExtArgs["result"]["dbosOperationOutput"]>

export type $DbosOperationOutputPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DbosOperationOutput"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    workflowUuid: string
    functionId: number
    functionName: string | null
  }, ExtArgs["result"]["dbosOperationOutput"]>
  composites: {}
}

export type DbosOperationOutputGetPayload<S extends boolean | null | undefined | DbosOperationOutputDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload, S>

export type DbosOperationOutputCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DbosOperationOutputFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DbosOperationOutputCountAggregateInputType | true
  }

export interface DbosOperationOutputDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DbosOperationOutput'], meta: { name: 'DbosOperationOutput' } }
  /**
   * Find zero or one DbosOperationOutput that matches the filter.
   * @param {DbosOperationOutputFindUniqueArgs} args - Arguments to find a DbosOperationOutput
   * @example
   * // Get one DbosOperationOutput
   * const dbosOperationOutput = await prisma.dbosOperationOutput.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DbosOperationOutputFindUniqueArgs>(args: Prisma.SelectSubset<T, DbosOperationOutputFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DbosOperationOutputClient<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DbosOperationOutput that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DbosOperationOutputFindUniqueOrThrowArgs} args - Arguments to find a DbosOperationOutput
   * @example
   * // Get one DbosOperationOutput
   * const dbosOperationOutput = await prisma.dbosOperationOutput.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DbosOperationOutputFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DbosOperationOutputFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbosOperationOutputClient<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbosOperationOutput that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbosOperationOutputFindFirstArgs} args - Arguments to find a DbosOperationOutput
   * @example
   * // Get one DbosOperationOutput
   * const dbosOperationOutput = await prisma.dbosOperationOutput.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DbosOperationOutputFindFirstArgs>(args?: Prisma.SelectSubset<T, DbosOperationOutputFindFirstArgs<ExtArgs>>): Prisma.Prisma__DbosOperationOutputClient<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbosOperationOutput that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbosOperationOutputFindFirstOrThrowArgs} args - Arguments to find a DbosOperationOutput
   * @example
   * // Get one DbosOperationOutput
   * const dbosOperationOutput = await prisma.dbosOperationOutput.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DbosOperationOutputFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DbosOperationOutputFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbosOperationOutputClient<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DbosOperationOutputs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbosOperationOutputFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DbosOperationOutputs
   * const dbosOperationOutputs = await prisma.dbosOperationOutput.findMany()
   * 
   * // Get first 10 DbosOperationOutputs
   * const dbosOperationOutputs = await prisma.dbosOperationOutput.findMany({ take: 10 })
   * 
   * // Only select the `workflowUuid`
   * const dbosOperationOutputWithWorkflowUuidOnly = await prisma.dbosOperationOutput.findMany({ select: { workflowUuid: true } })
   * 
   */
  findMany<T extends DbosOperationOutputFindManyArgs>(args?: Prisma.SelectSubset<T, DbosOperationOutputFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DbosOperationOutput.
   * @param {DbosOperationOutputCreateArgs} args - Arguments to create a DbosOperationOutput.
   * @example
   * // Create one DbosOperationOutput
   * const DbosOperationOutput = await prisma.dbosOperationOutput.create({
   *   data: {
   *     // ... data to create a DbosOperationOutput
   *   }
   * })
   * 
   */
  create<T extends DbosOperationOutputCreateArgs>(args: Prisma.SelectSubset<T, DbosOperationOutputCreateArgs<ExtArgs>>): Prisma.Prisma__DbosOperationOutputClient<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DbosOperationOutputs.
   * @param {DbosOperationOutputCreateManyArgs} args - Arguments to create many DbosOperationOutputs.
   * @example
   * // Create many DbosOperationOutputs
   * const dbosOperationOutput = await prisma.dbosOperationOutput.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DbosOperationOutputCreateManyArgs>(args?: Prisma.SelectSubset<T, DbosOperationOutputCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DbosOperationOutputs and returns the data saved in the database.
   * @param {DbosOperationOutputCreateManyAndReturnArgs} args - Arguments to create many DbosOperationOutputs.
   * @example
   * // Create many DbosOperationOutputs
   * const dbosOperationOutput = await prisma.dbosOperationOutput.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DbosOperationOutputs and only return the `workflowUuid`
   * const dbosOperationOutputWithWorkflowUuidOnly = await prisma.dbosOperationOutput.createManyAndReturn({
   *   select: { workflowUuid: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DbosOperationOutputCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DbosOperationOutputCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DbosOperationOutput.
   * @param {DbosOperationOutputDeleteArgs} args - Arguments to delete one DbosOperationOutput.
   * @example
   * // Delete one DbosOperationOutput
   * const DbosOperationOutput = await prisma.dbosOperationOutput.delete({
   *   where: {
   *     // ... filter to delete one DbosOperationOutput
   *   }
   * })
   * 
   */
  delete<T extends DbosOperationOutputDeleteArgs>(args: Prisma.SelectSubset<T, DbosOperationOutputDeleteArgs<ExtArgs>>): Prisma.Prisma__DbosOperationOutputClient<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DbosOperationOutput.
   * @param {DbosOperationOutputUpdateArgs} args - Arguments to update one DbosOperationOutput.
   * @example
   * // Update one DbosOperationOutput
   * const dbosOperationOutput = await prisma.dbosOperationOutput.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DbosOperationOutputUpdateArgs>(args: Prisma.SelectSubset<T, DbosOperationOutputUpdateArgs<ExtArgs>>): Prisma.Prisma__DbosOperationOutputClient<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DbosOperationOutputs.
   * @param {DbosOperationOutputDeleteManyArgs} args - Arguments to filter DbosOperationOutputs to delete.
   * @example
   * // Delete a few DbosOperationOutputs
   * const { count } = await prisma.dbosOperationOutput.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DbosOperationOutputDeleteManyArgs>(args?: Prisma.SelectSubset<T, DbosOperationOutputDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbosOperationOutputs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbosOperationOutputUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DbosOperationOutputs
   * const dbosOperationOutput = await prisma.dbosOperationOutput.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DbosOperationOutputUpdateManyArgs>(args: Prisma.SelectSubset<T, DbosOperationOutputUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbosOperationOutputs and returns the data updated in the database.
   * @param {DbosOperationOutputUpdateManyAndReturnArgs} args - Arguments to update many DbosOperationOutputs.
   * @example
   * // Update many DbosOperationOutputs
   * const dbosOperationOutput = await prisma.dbosOperationOutput.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DbosOperationOutputs and only return the `workflowUuid`
   * const dbosOperationOutputWithWorkflowUuidOnly = await prisma.dbosOperationOutput.updateManyAndReturn({
   *   select: { workflowUuid: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DbosOperationOutputUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DbosOperationOutputUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DbosOperationOutput.
   * @param {DbosOperationOutputUpsertArgs} args - Arguments to update or create a DbosOperationOutput.
   * @example
   * // Update or create a DbosOperationOutput
   * const dbosOperationOutput = await prisma.dbosOperationOutput.upsert({
   *   create: {
   *     // ... data to create a DbosOperationOutput
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DbosOperationOutput we want to update
   *   }
   * })
   */
  upsert<T extends DbosOperationOutputUpsertArgs>(args: Prisma.SelectSubset<T, DbosOperationOutputUpsertArgs<ExtArgs>>): Prisma.Prisma__DbosOperationOutputClient<runtime.Types.Result.GetResult<Prisma.$DbosOperationOutputPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DbosOperationOutputs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbosOperationOutputCountArgs} args - Arguments to filter DbosOperationOutputs to count.
   * @example
   * // Count the number of DbosOperationOutputs
   * const count = await prisma.dbosOperationOutput.count({
   *   where: {
   *     // ... the filter for the DbosOperationOutputs we want to count
   *   }
   * })
  **/
  count<T extends DbosOperationOutputCountArgs>(
    args?: Prisma.Subset<T, DbosOperationOutputCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DbosOperationOutputCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DbosOperationOutput.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbosOperationOutputAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DbosOperationOutputAggregateArgs>(args: Prisma.Subset<T, DbosOperationOutputAggregateArgs>): Prisma.PrismaPromise<GetDbosOperationOutputAggregateType<T>>

  /**
   * Group by DbosOperationOutput.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbosOperationOutputGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DbosOperationOutputGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DbosOperationOutputGroupByArgs['orderBy'] }
      : { orderBy?: DbosOperationOutputGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DbosOperationOutputGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDbosOperationOutputGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DbosOperationOutput model
 */
readonly fields: DbosOperationOutputFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DbosOperationOutput.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DbosOperationOutputClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DbosOperationOutput model
 */
export interface DbosOperationOutputFieldRefs {
  readonly workflowUuid: Prisma.FieldRef<"DbosOperationOutput", 'String'>
  readonly functionId: Prisma.FieldRef<"DbosOperationOutput", 'Int'>
  readonly functionName: Prisma.FieldRef<"DbosOperationOutput", 'String'>
}
    

// Custom InputTypes
/**
 * DbosOperationOutput findUnique
 */
export type DbosOperationOutputFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * Filter, which DbosOperationOutput to fetch.
   */
  where: Prisma.DbosOperationOutputWhereUniqueInput
}

/**
 * DbosOperationOutput findUniqueOrThrow
 */
export type DbosOperationOutputFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * Filter, which DbosOperationOutput to fetch.
   */
  where: Prisma.DbosOperationOutputWhereUniqueInput
}

/**
 * DbosOperationOutput findFirst
 */
export type DbosOperationOutputFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * Filter, which DbosOperationOutput to fetch.
   */
  where?: Prisma.DbosOperationOutputWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbosOperationOutputs to fetch.
   */
  orderBy?: Prisma.DbosOperationOutputOrderByWithRelationInput | Prisma.DbosOperationOutputOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbosOperationOutputs.
   */
  cursor?: Prisma.DbosOperationOutputWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbosOperationOutputs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbosOperationOutputs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbosOperationOutputs.
   */
  distinct?: Prisma.DbosOperationOutputScalarFieldEnum | Prisma.DbosOperationOutputScalarFieldEnum[]
}

/**
 * DbosOperationOutput findFirstOrThrow
 */
export type DbosOperationOutputFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * Filter, which DbosOperationOutput to fetch.
   */
  where?: Prisma.DbosOperationOutputWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbosOperationOutputs to fetch.
   */
  orderBy?: Prisma.DbosOperationOutputOrderByWithRelationInput | Prisma.DbosOperationOutputOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbosOperationOutputs.
   */
  cursor?: Prisma.DbosOperationOutputWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbosOperationOutputs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbosOperationOutputs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbosOperationOutputs.
   */
  distinct?: Prisma.DbosOperationOutputScalarFieldEnum | Prisma.DbosOperationOutputScalarFieldEnum[]
}

/**
 * DbosOperationOutput findMany
 */
export type DbosOperationOutputFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * Filter, which DbosOperationOutputs to fetch.
   */
  where?: Prisma.DbosOperationOutputWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbosOperationOutputs to fetch.
   */
  orderBy?: Prisma.DbosOperationOutputOrderByWithRelationInput | Prisma.DbosOperationOutputOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DbosOperationOutputs.
   */
  cursor?: Prisma.DbosOperationOutputWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbosOperationOutputs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbosOperationOutputs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbosOperationOutputs.
   */
  distinct?: Prisma.DbosOperationOutputScalarFieldEnum | Prisma.DbosOperationOutputScalarFieldEnum[]
}

/**
 * DbosOperationOutput create
 */
export type DbosOperationOutputCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * The data needed to create a DbosOperationOutput.
   */
  data: Prisma.XOR<Prisma.DbosOperationOutputCreateInput, Prisma.DbosOperationOutputUncheckedCreateInput>
}

/**
 * DbosOperationOutput createMany
 */
export type DbosOperationOutputCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DbosOperationOutputs.
   */
  data: Prisma.DbosOperationOutputCreateManyInput | Prisma.DbosOperationOutputCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DbosOperationOutput createManyAndReturn
 */
export type DbosOperationOutputCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * The data used to create many DbosOperationOutputs.
   */
  data: Prisma.DbosOperationOutputCreateManyInput | Prisma.DbosOperationOutputCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DbosOperationOutput update
 */
export type DbosOperationOutputUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * The data needed to update a DbosOperationOutput.
   */
  data: Prisma.XOR<Prisma.DbosOperationOutputUpdateInput, Prisma.DbosOperationOutputUncheckedUpdateInput>
  /**
   * Choose, which DbosOperationOutput to update.
   */
  where: Prisma.DbosOperationOutputWhereUniqueInput
}

/**
 * DbosOperationOutput updateMany
 */
export type DbosOperationOutputUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DbosOperationOutputs.
   */
  data: Prisma.XOR<Prisma.DbosOperationOutputUpdateManyMutationInput, Prisma.DbosOperationOutputUncheckedUpdateManyInput>
  /**
   * Filter which DbosOperationOutputs to update
   */
  where?: Prisma.DbosOperationOutputWhereInput
  /**
   * Limit how many DbosOperationOutputs to update.
   */
  limit?: number
}

/**
 * DbosOperationOutput updateManyAndReturn
 */
export type DbosOperationOutputUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * The data used to update DbosOperationOutputs.
   */
  data: Prisma.XOR<Prisma.DbosOperationOutputUpdateManyMutationInput, Prisma.DbosOperationOutputUncheckedUpdateManyInput>
  /**
   * Filter which DbosOperationOutputs to update
   */
  where?: Prisma.DbosOperationOutputWhereInput
  /**
   * Limit how many DbosOperationOutputs to update.
   */
  limit?: number
}

/**
 * DbosOperationOutput upsert
 */
export type DbosOperationOutputUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * The filter to search for the DbosOperationOutput to update in case it exists.
   */
  where: Prisma.DbosOperationOutputWhereUniqueInput
  /**
   * In case the DbosOperationOutput found by the `where` argument doesn't exist, create a new DbosOperationOutput with this data.
   */
  create: Prisma.XOR<Prisma.DbosOperationOutputCreateInput, Prisma.DbosOperationOutputUncheckedCreateInput>
  /**
   * In case the DbosOperationOutput was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DbosOperationOutputUpdateInput, Prisma.DbosOperationOutputUncheckedUpdateInput>
}

/**
 * DbosOperationOutput delete
 */
export type DbosOperationOutputDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
  /**
   * Filter which DbosOperationOutput to delete.
   */
  where: Prisma.DbosOperationOutputWhereUniqueInput
}

/**
 * DbosOperationOutput deleteMany
 */
export type DbosOperationOutputDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbosOperationOutputs to delete
   */
  where?: Prisma.DbosOperationOutputWhereInput
  /**
   * Limit how many DbosOperationOutputs to delete.
   */
  limit?: number
}

/**
 * DbosOperationOutput without action
 */
export type DbosOperationOutputDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbosOperationOutput
   */
  select?: Prisma.DbosOperationOutputSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbosOperationOutput
   */
  omit?: Prisma.DbosOperationOutputOmit<ExtArgs> | null
}
