
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DialogueTurn` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DialogueTurn
 * 
 */
export type DialogueTurnModel = runtime.Types.Result.DefaultSelection<Prisma.$DialogueTurnPayload>

export type AggregateDialogueTurn = {
  _count: DialogueTurnCountAggregateOutputType | null
  _avg: DialogueTurnAvgAggregateOutputType | null
  _sum: DialogueTurnSumAggregateOutputType | null
  _min: DialogueTurnMinAggregateOutputType | null
  _max: DialogueTurnMaxAggregateOutputType | null
}

export type DialogueTurnAvgAggregateOutputType = {
  endItemSequence: number | null
}

export type DialogueTurnSumAggregateOutputType = {
  endItemSequence: bigint | null
}

export type DialogueTurnMinAggregateOutputType = {
  id: string | null
  dialogueId: string | null
  commandId: string | null
  userItemId: string | null
  inputSha256: string | null
  status: $Enums.DialogueTurnStatus | null
  dispatchState: $Enums.DialogueDispatchState | null
  cancelRequested: boolean | null
  runtimeSessionId: string | null
  createdAt: Date | null
  completedAt: Date | null
  endItemSequence: bigint | null
}

export type DialogueTurnMaxAggregateOutputType = {
  id: string | null
  dialogueId: string | null
  commandId: string | null
  userItemId: string | null
  inputSha256: string | null
  status: $Enums.DialogueTurnStatus | null
  dispatchState: $Enums.DialogueDispatchState | null
  cancelRequested: boolean | null
  runtimeSessionId: string | null
  createdAt: Date | null
  completedAt: Date | null
  endItemSequence: bigint | null
}

export type DialogueTurnCountAggregateOutputType = {
  id: number
  dialogueId: number
  commandId: number
  userItemId: number
  inputSha256: number
  status: number
  dispatchState: number
  cancelRequested: number
  runtimeSessionId: number
  outcome: number
  createdAt: number
  completedAt: number
  endItemSequence: number
  _all: number
}


export type DialogueTurnAvgAggregateInputType = {
  endItemSequence?: true
}

export type DialogueTurnSumAggregateInputType = {
  endItemSequence?: true
}

export type DialogueTurnMinAggregateInputType = {
  id?: true
  dialogueId?: true
  commandId?: true
  userItemId?: true
  inputSha256?: true
  status?: true
  dispatchState?: true
  cancelRequested?: true
  runtimeSessionId?: true
  createdAt?: true
  completedAt?: true
  endItemSequence?: true
}

export type DialogueTurnMaxAggregateInputType = {
  id?: true
  dialogueId?: true
  commandId?: true
  userItemId?: true
  inputSha256?: true
  status?: true
  dispatchState?: true
  cancelRequested?: true
  runtimeSessionId?: true
  createdAt?: true
  completedAt?: true
  endItemSequence?: true
}

export type DialogueTurnCountAggregateInputType = {
  id?: true
  dialogueId?: true
  commandId?: true
  userItemId?: true
  inputSha256?: true
  status?: true
  dispatchState?: true
  cancelRequested?: true
  runtimeSessionId?: true
  outcome?: true
  createdAt?: true
  completedAt?: true
  endItemSequence?: true
  _all?: true
}

export type DialogueTurnAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DialogueTurn to aggregate.
   */
  where?: Prisma.DialogueTurnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueTurns to fetch.
   */
  orderBy?: Prisma.DialogueTurnOrderByWithRelationInput | Prisma.DialogueTurnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DialogueTurnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueTurns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueTurns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DialogueTurns
  **/
  _count?: true | DialogueTurnCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DialogueTurnAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DialogueTurnSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DialogueTurnMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DialogueTurnMaxAggregateInputType
}

export type GetDialogueTurnAggregateType<T extends DialogueTurnAggregateArgs> = {
      [P in keyof T & keyof AggregateDialogueTurn]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDialogueTurn[P]>
    : Prisma.GetScalarType<T[P], AggregateDialogueTurn[P]>
}




export type DialogueTurnGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DialogueTurnWhereInput
  orderBy?: Prisma.DialogueTurnOrderByWithAggregationInput | Prisma.DialogueTurnOrderByWithAggregationInput[]
  by: Prisma.DialogueTurnScalarFieldEnum[] | Prisma.DialogueTurnScalarFieldEnum
  having?: Prisma.DialogueTurnScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DialogueTurnCountAggregateInputType | true
  _avg?: DialogueTurnAvgAggregateInputType
  _sum?: DialogueTurnSumAggregateInputType
  _min?: DialogueTurnMinAggregateInputType
  _max?: DialogueTurnMaxAggregateInputType
}

export type DialogueTurnGroupByOutputType = {
  id: string
  dialogueId: string
  commandId: string
  userItemId: string
  inputSha256: string
  status: $Enums.DialogueTurnStatus
  dispatchState: $Enums.DialogueDispatchState
  cancelRequested: boolean
  runtimeSessionId: string | null
  outcome: runtime.JsonValue
  createdAt: Date
  completedAt: Date | null
  endItemSequence: bigint | null
  _count: DialogueTurnCountAggregateOutputType | null
  _avg: DialogueTurnAvgAggregateOutputType | null
  _sum: DialogueTurnSumAggregateOutputType | null
  _min: DialogueTurnMinAggregateOutputType | null
  _max: DialogueTurnMaxAggregateOutputType | null
}

export type GetDialogueTurnGroupByPayload<T extends DialogueTurnGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DialogueTurnGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DialogueTurnGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DialogueTurnGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DialogueTurnGroupByOutputType[P]>
      }
    >
  >



export type DialogueTurnWhereInput = {
  AND?: Prisma.DialogueTurnWhereInput | Prisma.DialogueTurnWhereInput[]
  OR?: Prisma.DialogueTurnWhereInput[]
  NOT?: Prisma.DialogueTurnWhereInput | Prisma.DialogueTurnWhereInput[]
  id?: Prisma.StringFilter<"DialogueTurn"> | string
  dialogueId?: Prisma.StringFilter<"DialogueTurn"> | string
  commandId?: Prisma.StringFilter<"DialogueTurn"> | string
  userItemId?: Prisma.StringFilter<"DialogueTurn"> | string
  inputSha256?: Prisma.StringFilter<"DialogueTurn"> | string
  status?: Prisma.EnumDialogueTurnStatusFilter<"DialogueTurn"> | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFilter<"DialogueTurn"> | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFilter<"DialogueTurn"> | boolean
  runtimeSessionId?: Prisma.StringNullableFilter<"DialogueTurn"> | string | null
  outcome?: Prisma.JsonFilter<"DialogueTurn">
  createdAt?: Prisma.DateTimeFilter<"DialogueTurn"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"DialogueTurn"> | Date | string | null
  endItemSequence?: Prisma.BigIntNullableFilter<"DialogueTurn"> | bigint | number | null
  dialogue?: Prisma.XOR<Prisma.DialogueScalarRelationFilter, Prisma.DialogueWhereInput>
}

export type DialogueTurnOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  commandId?: Prisma.SortOrder
  userItemId?: Prisma.SortOrder
  inputSha256?: Prisma.SortOrder
  status?: Prisma.SortOrder
  dispatchState?: Prisma.SortOrder
  cancelRequested?: Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  outcome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  endItemSequence?: Prisma.SortOrderInput | Prisma.SortOrder
  dialogue?: Prisma.DialogueOrderByWithRelationInput
}

export type DialogueTurnWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userItemId?: string
  dialogueId_commandId?: Prisma.DialogueTurnDialogueIdCommandIdCompoundUniqueInput
  AND?: Prisma.DialogueTurnWhereInput | Prisma.DialogueTurnWhereInput[]
  OR?: Prisma.DialogueTurnWhereInput[]
  NOT?: Prisma.DialogueTurnWhereInput | Prisma.DialogueTurnWhereInput[]
  dialogueId?: Prisma.StringFilter<"DialogueTurn"> | string
  commandId?: Prisma.StringFilter<"DialogueTurn"> | string
  inputSha256?: Prisma.StringFilter<"DialogueTurn"> | string
  status?: Prisma.EnumDialogueTurnStatusFilter<"DialogueTurn"> | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFilter<"DialogueTurn"> | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFilter<"DialogueTurn"> | boolean
  runtimeSessionId?: Prisma.StringNullableFilter<"DialogueTurn"> | string | null
  outcome?: Prisma.JsonFilter<"DialogueTurn">
  createdAt?: Prisma.DateTimeFilter<"DialogueTurn"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"DialogueTurn"> | Date | string | null
  endItemSequence?: Prisma.BigIntNullableFilter<"DialogueTurn"> | bigint | number | null
  dialogue?: Prisma.XOR<Prisma.DialogueScalarRelationFilter, Prisma.DialogueWhereInput>
}, "id" | "userItemId" | "dialogueId_commandId">

export type DialogueTurnOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  commandId?: Prisma.SortOrder
  userItemId?: Prisma.SortOrder
  inputSha256?: Prisma.SortOrder
  status?: Prisma.SortOrder
  dispatchState?: Prisma.SortOrder
  cancelRequested?: Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  outcome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  endItemSequence?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DialogueTurnCountOrderByAggregateInput
  _avg?: Prisma.DialogueTurnAvgOrderByAggregateInput
  _max?: Prisma.DialogueTurnMaxOrderByAggregateInput
  _min?: Prisma.DialogueTurnMinOrderByAggregateInput
  _sum?: Prisma.DialogueTurnSumOrderByAggregateInput
}

export type DialogueTurnScalarWhereWithAggregatesInput = {
  AND?: Prisma.DialogueTurnScalarWhereWithAggregatesInput | Prisma.DialogueTurnScalarWhereWithAggregatesInput[]
  OR?: Prisma.DialogueTurnScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DialogueTurnScalarWhereWithAggregatesInput | Prisma.DialogueTurnScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DialogueTurn"> | string
  dialogueId?: Prisma.StringWithAggregatesFilter<"DialogueTurn"> | string
  commandId?: Prisma.StringWithAggregatesFilter<"DialogueTurn"> | string
  userItemId?: Prisma.StringWithAggregatesFilter<"DialogueTurn"> | string
  inputSha256?: Prisma.StringWithAggregatesFilter<"DialogueTurn"> | string
  status?: Prisma.EnumDialogueTurnStatusWithAggregatesFilter<"DialogueTurn"> | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateWithAggregatesFilter<"DialogueTurn"> | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolWithAggregatesFilter<"DialogueTurn"> | boolean
  runtimeSessionId?: Prisma.StringNullableWithAggregatesFilter<"DialogueTurn"> | string | null
  outcome?: Prisma.JsonWithAggregatesFilter<"DialogueTurn">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DialogueTurn"> | Date | string
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"DialogueTurn"> | Date | string | null
  endItemSequence?: Prisma.BigIntNullableWithAggregatesFilter<"DialogueTurn"> | bigint | number | null
}

export type DialogueTurnCreateInput = {
  id: string
  commandId: string
  userItemId: string
  inputSha256: string
  status?: $Enums.DialogueTurnStatus
  dispatchState?: $Enums.DialogueDispatchState
  cancelRequested?: boolean
  runtimeSessionId?: string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  completedAt?: Date | string | null
  endItemSequence?: bigint | number | null
  dialogue: Prisma.DialogueCreateNestedOneWithoutTurnsInput
}

export type DialogueTurnUncheckedCreateInput = {
  id: string
  dialogueId: string
  commandId: string
  userItemId: string
  inputSha256: string
  status?: $Enums.DialogueTurnStatus
  dispatchState?: $Enums.DialogueDispatchState
  cancelRequested?: boolean
  runtimeSessionId?: string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  completedAt?: Date | string | null
  endItemSequence?: bigint | number | null
}

export type DialogueTurnUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  commandId?: Prisma.StringFieldUpdateOperationsInput | string
  userItemId?: Prisma.StringFieldUpdateOperationsInput | string
  inputSha256?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueTurnStatusFieldUpdateOperationsInput | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFieldUpdateOperationsInput | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runtimeSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endItemSequence?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  dialogue?: Prisma.DialogueUpdateOneRequiredWithoutTurnsNestedInput
}

export type DialogueTurnUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dialogueId?: Prisma.StringFieldUpdateOperationsInput | string
  commandId?: Prisma.StringFieldUpdateOperationsInput | string
  userItemId?: Prisma.StringFieldUpdateOperationsInput | string
  inputSha256?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueTurnStatusFieldUpdateOperationsInput | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFieldUpdateOperationsInput | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runtimeSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endItemSequence?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type DialogueTurnCreateManyInput = {
  id: string
  dialogueId: string
  commandId: string
  userItemId: string
  inputSha256: string
  status?: $Enums.DialogueTurnStatus
  dispatchState?: $Enums.DialogueDispatchState
  cancelRequested?: boolean
  runtimeSessionId?: string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  completedAt?: Date | string | null
  endItemSequence?: bigint | number | null
}

export type DialogueTurnUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  commandId?: Prisma.StringFieldUpdateOperationsInput | string
  userItemId?: Prisma.StringFieldUpdateOperationsInput | string
  inputSha256?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueTurnStatusFieldUpdateOperationsInput | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFieldUpdateOperationsInput | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runtimeSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endItemSequence?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type DialogueTurnUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dialogueId?: Prisma.StringFieldUpdateOperationsInput | string
  commandId?: Prisma.StringFieldUpdateOperationsInput | string
  userItemId?: Prisma.StringFieldUpdateOperationsInput | string
  inputSha256?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueTurnStatusFieldUpdateOperationsInput | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFieldUpdateOperationsInput | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runtimeSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endItemSequence?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type DialogueTurnListRelationFilter = {
  every?: Prisma.DialogueTurnWhereInput
  some?: Prisma.DialogueTurnWhereInput
  none?: Prisma.DialogueTurnWhereInput
}

export type DialogueTurnOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DialogueTurnDialogueIdCommandIdCompoundUniqueInput = {
  dialogueId: string
  commandId: string
}

export type DialogueTurnCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  commandId?: Prisma.SortOrder
  userItemId?: Prisma.SortOrder
  inputSha256?: Prisma.SortOrder
  status?: Prisma.SortOrder
  dispatchState?: Prisma.SortOrder
  cancelRequested?: Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  endItemSequence?: Prisma.SortOrder
}

export type DialogueTurnAvgOrderByAggregateInput = {
  endItemSequence?: Prisma.SortOrder
}

export type DialogueTurnMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  commandId?: Prisma.SortOrder
  userItemId?: Prisma.SortOrder
  inputSha256?: Prisma.SortOrder
  status?: Prisma.SortOrder
  dispatchState?: Prisma.SortOrder
  cancelRequested?: Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  endItemSequence?: Prisma.SortOrder
}

export type DialogueTurnMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  commandId?: Prisma.SortOrder
  userItemId?: Prisma.SortOrder
  inputSha256?: Prisma.SortOrder
  status?: Prisma.SortOrder
  dispatchState?: Prisma.SortOrder
  cancelRequested?: Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  endItemSequence?: Prisma.SortOrder
}

export type DialogueTurnSumOrderByAggregateInput = {
  endItemSequence?: Prisma.SortOrder
}

export type DialogueTurnCreateNestedManyWithoutDialogueInput = {
  create?: Prisma.XOR<Prisma.DialogueTurnCreateWithoutDialogueInput, Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput> | Prisma.DialogueTurnCreateWithoutDialogueInput[] | Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.DialogueTurnCreateOrConnectWithoutDialogueInput | Prisma.DialogueTurnCreateOrConnectWithoutDialogueInput[]
  createMany?: Prisma.DialogueTurnCreateManyDialogueInputEnvelope
  connect?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
}

export type DialogueTurnUncheckedCreateNestedManyWithoutDialogueInput = {
  create?: Prisma.XOR<Prisma.DialogueTurnCreateWithoutDialogueInput, Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput> | Prisma.DialogueTurnCreateWithoutDialogueInput[] | Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.DialogueTurnCreateOrConnectWithoutDialogueInput | Prisma.DialogueTurnCreateOrConnectWithoutDialogueInput[]
  createMany?: Prisma.DialogueTurnCreateManyDialogueInputEnvelope
  connect?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
}

export type DialogueTurnUpdateManyWithoutDialogueNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueTurnCreateWithoutDialogueInput, Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput> | Prisma.DialogueTurnCreateWithoutDialogueInput[] | Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.DialogueTurnCreateOrConnectWithoutDialogueInput | Prisma.DialogueTurnCreateOrConnectWithoutDialogueInput[]
  upsert?: Prisma.DialogueTurnUpsertWithWhereUniqueWithoutDialogueInput | Prisma.DialogueTurnUpsertWithWhereUniqueWithoutDialogueInput[]
  createMany?: Prisma.DialogueTurnCreateManyDialogueInputEnvelope
  set?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
  disconnect?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
  delete?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
  connect?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
  update?: Prisma.DialogueTurnUpdateWithWhereUniqueWithoutDialogueInput | Prisma.DialogueTurnUpdateWithWhereUniqueWithoutDialogueInput[]
  updateMany?: Prisma.DialogueTurnUpdateManyWithWhereWithoutDialogueInput | Prisma.DialogueTurnUpdateManyWithWhereWithoutDialogueInput[]
  deleteMany?: Prisma.DialogueTurnScalarWhereInput | Prisma.DialogueTurnScalarWhereInput[]
}

export type DialogueTurnUncheckedUpdateManyWithoutDialogueNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueTurnCreateWithoutDialogueInput, Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput> | Prisma.DialogueTurnCreateWithoutDialogueInput[] | Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.DialogueTurnCreateOrConnectWithoutDialogueInput | Prisma.DialogueTurnCreateOrConnectWithoutDialogueInput[]
  upsert?: Prisma.DialogueTurnUpsertWithWhereUniqueWithoutDialogueInput | Prisma.DialogueTurnUpsertWithWhereUniqueWithoutDialogueInput[]
  createMany?: Prisma.DialogueTurnCreateManyDialogueInputEnvelope
  set?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
  disconnect?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
  delete?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
  connect?: Prisma.DialogueTurnWhereUniqueInput | Prisma.DialogueTurnWhereUniqueInput[]
  update?: Prisma.DialogueTurnUpdateWithWhereUniqueWithoutDialogueInput | Prisma.DialogueTurnUpdateWithWhereUniqueWithoutDialogueInput[]
  updateMany?: Prisma.DialogueTurnUpdateManyWithWhereWithoutDialogueInput | Prisma.DialogueTurnUpdateManyWithWhereWithoutDialogueInput[]
  deleteMany?: Prisma.DialogueTurnScalarWhereInput | Prisma.DialogueTurnScalarWhereInput[]
}

export type EnumDialogueTurnStatusFieldUpdateOperationsInput = {
  set?: $Enums.DialogueTurnStatus
}

export type EnumDialogueDispatchStateFieldUpdateOperationsInput = {
  set?: $Enums.DialogueDispatchState
}

export type DialogueTurnCreateWithoutDialogueInput = {
  id: string
  commandId: string
  userItemId: string
  inputSha256: string
  status?: $Enums.DialogueTurnStatus
  dispatchState?: $Enums.DialogueDispatchState
  cancelRequested?: boolean
  runtimeSessionId?: string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  completedAt?: Date | string | null
  endItemSequence?: bigint | number | null
}

export type DialogueTurnUncheckedCreateWithoutDialogueInput = {
  id: string
  commandId: string
  userItemId: string
  inputSha256: string
  status?: $Enums.DialogueTurnStatus
  dispatchState?: $Enums.DialogueDispatchState
  cancelRequested?: boolean
  runtimeSessionId?: string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  completedAt?: Date | string | null
  endItemSequence?: bigint | number | null
}

export type DialogueTurnCreateOrConnectWithoutDialogueInput = {
  where: Prisma.DialogueTurnWhereUniqueInput
  create: Prisma.XOR<Prisma.DialogueTurnCreateWithoutDialogueInput, Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput>
}

export type DialogueTurnCreateManyDialogueInputEnvelope = {
  data: Prisma.DialogueTurnCreateManyDialogueInput | Prisma.DialogueTurnCreateManyDialogueInput[]
  skipDuplicates?: boolean
}

export type DialogueTurnUpsertWithWhereUniqueWithoutDialogueInput = {
  where: Prisma.DialogueTurnWhereUniqueInput
  update: Prisma.XOR<Prisma.DialogueTurnUpdateWithoutDialogueInput, Prisma.DialogueTurnUncheckedUpdateWithoutDialogueInput>
  create: Prisma.XOR<Prisma.DialogueTurnCreateWithoutDialogueInput, Prisma.DialogueTurnUncheckedCreateWithoutDialogueInput>
}

export type DialogueTurnUpdateWithWhereUniqueWithoutDialogueInput = {
  where: Prisma.DialogueTurnWhereUniqueInput
  data: Prisma.XOR<Prisma.DialogueTurnUpdateWithoutDialogueInput, Prisma.DialogueTurnUncheckedUpdateWithoutDialogueInput>
}

export type DialogueTurnUpdateManyWithWhereWithoutDialogueInput = {
  where: Prisma.DialogueTurnScalarWhereInput
  data: Prisma.XOR<Prisma.DialogueTurnUpdateManyMutationInput, Prisma.DialogueTurnUncheckedUpdateManyWithoutDialogueInput>
}

export type DialogueTurnScalarWhereInput = {
  AND?: Prisma.DialogueTurnScalarWhereInput | Prisma.DialogueTurnScalarWhereInput[]
  OR?: Prisma.DialogueTurnScalarWhereInput[]
  NOT?: Prisma.DialogueTurnScalarWhereInput | Prisma.DialogueTurnScalarWhereInput[]
  id?: Prisma.StringFilter<"DialogueTurn"> | string
  dialogueId?: Prisma.StringFilter<"DialogueTurn"> | string
  commandId?: Prisma.StringFilter<"DialogueTurn"> | string
  userItemId?: Prisma.StringFilter<"DialogueTurn"> | string
  inputSha256?: Prisma.StringFilter<"DialogueTurn"> | string
  status?: Prisma.EnumDialogueTurnStatusFilter<"DialogueTurn"> | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFilter<"DialogueTurn"> | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFilter<"DialogueTurn"> | boolean
  runtimeSessionId?: Prisma.StringNullableFilter<"DialogueTurn"> | string | null
  outcome?: Prisma.JsonFilter<"DialogueTurn">
  createdAt?: Prisma.DateTimeFilter<"DialogueTurn"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"DialogueTurn"> | Date | string | null
  endItemSequence?: Prisma.BigIntNullableFilter<"DialogueTurn"> | bigint | number | null
}

export type DialogueTurnCreateManyDialogueInput = {
  id: string
  commandId: string
  userItemId: string
  inputSha256: string
  status?: $Enums.DialogueTurnStatus
  dispatchState?: $Enums.DialogueDispatchState
  cancelRequested?: boolean
  runtimeSessionId?: string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  completedAt?: Date | string | null
  endItemSequence?: bigint | number | null
}

export type DialogueTurnUpdateWithoutDialogueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  commandId?: Prisma.StringFieldUpdateOperationsInput | string
  userItemId?: Prisma.StringFieldUpdateOperationsInput | string
  inputSha256?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueTurnStatusFieldUpdateOperationsInput | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFieldUpdateOperationsInput | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runtimeSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endItemSequence?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type DialogueTurnUncheckedUpdateWithoutDialogueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  commandId?: Prisma.StringFieldUpdateOperationsInput | string
  userItemId?: Prisma.StringFieldUpdateOperationsInput | string
  inputSha256?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueTurnStatusFieldUpdateOperationsInput | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFieldUpdateOperationsInput | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runtimeSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endItemSequence?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type DialogueTurnUncheckedUpdateManyWithoutDialogueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  commandId?: Prisma.StringFieldUpdateOperationsInput | string
  userItemId?: Prisma.StringFieldUpdateOperationsInput | string
  inputSha256?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueTurnStatusFieldUpdateOperationsInput | $Enums.DialogueTurnStatus
  dispatchState?: Prisma.EnumDialogueDispatchStateFieldUpdateOperationsInput | $Enums.DialogueDispatchState
  cancelRequested?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runtimeSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  outcome?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endItemSequence?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}



export type DialogueTurnSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dialogueId?: boolean
  commandId?: boolean
  userItemId?: boolean
  inputSha256?: boolean
  status?: boolean
  dispatchState?: boolean
  cancelRequested?: boolean
  runtimeSessionId?: boolean
  outcome?: boolean
  createdAt?: boolean
  completedAt?: boolean
  endItemSequence?: boolean
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dialogueTurn"]>

export type DialogueTurnSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dialogueId?: boolean
  commandId?: boolean
  userItemId?: boolean
  inputSha256?: boolean
  status?: boolean
  dispatchState?: boolean
  cancelRequested?: boolean
  runtimeSessionId?: boolean
  outcome?: boolean
  createdAt?: boolean
  completedAt?: boolean
  endItemSequence?: boolean
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dialogueTurn"]>

export type DialogueTurnSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dialogueId?: boolean
  commandId?: boolean
  userItemId?: boolean
  inputSha256?: boolean
  status?: boolean
  dispatchState?: boolean
  cancelRequested?: boolean
  runtimeSessionId?: boolean
  outcome?: boolean
  createdAt?: boolean
  completedAt?: boolean
  endItemSequence?: boolean
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dialogueTurn"]>

export type DialogueTurnSelectScalar = {
  id?: boolean
  dialogueId?: boolean
  commandId?: boolean
  userItemId?: boolean
  inputSha256?: boolean
  status?: boolean
  dispatchState?: boolean
  cancelRequested?: boolean
  runtimeSessionId?: boolean
  outcome?: boolean
  createdAt?: boolean
  completedAt?: boolean
  endItemSequence?: boolean
}

export type DialogueTurnOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "dialogueId" | "commandId" | "userItemId" | "inputSha256" | "status" | "dispatchState" | "cancelRequested" | "runtimeSessionId" | "outcome" | "createdAt" | "completedAt" | "endItemSequence", ExtArgs["result"]["dialogueTurn"]>
export type DialogueTurnInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}
export type DialogueTurnIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}
export type DialogueTurnIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}

export type $DialogueTurnPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DialogueTurn"
  objects: {
    dialogue: Prisma.$DialoguePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    dialogueId: string
    commandId: string
    userItemId: string
    inputSha256: string
    status: $Enums.DialogueTurnStatus
    dispatchState: $Enums.DialogueDispatchState
    cancelRequested: boolean
    runtimeSessionId: string | null
    outcome: runtime.JsonValue
    createdAt: Date
    completedAt: Date | null
    endItemSequence: bigint | null
  }, ExtArgs["result"]["dialogueTurn"]>
  composites: {}
}

export type DialogueTurnGetPayload<S extends boolean | null | undefined | DialogueTurnDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload, S>

export type DialogueTurnCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DialogueTurnFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DialogueTurnCountAggregateInputType | true
  }

export interface DialogueTurnDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DialogueTurn'], meta: { name: 'DialogueTurn' } }
  /**
   * Find zero or one DialogueTurn that matches the filter.
   * @param {DialogueTurnFindUniqueArgs} args - Arguments to find a DialogueTurn
   * @example
   * // Get one DialogueTurn
   * const dialogueTurn = await prisma.dialogueTurn.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DialogueTurnFindUniqueArgs>(args: Prisma.SelectSubset<T, DialogueTurnFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DialogueTurnClient<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DialogueTurn that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DialogueTurnFindUniqueOrThrowArgs} args - Arguments to find a DialogueTurn
   * @example
   * // Get one DialogueTurn
   * const dialogueTurn = await prisma.dialogueTurn.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DialogueTurnFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DialogueTurnFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DialogueTurnClient<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DialogueTurn that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTurnFindFirstArgs} args - Arguments to find a DialogueTurn
   * @example
   * // Get one DialogueTurn
   * const dialogueTurn = await prisma.dialogueTurn.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DialogueTurnFindFirstArgs>(args?: Prisma.SelectSubset<T, DialogueTurnFindFirstArgs<ExtArgs>>): Prisma.Prisma__DialogueTurnClient<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DialogueTurn that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTurnFindFirstOrThrowArgs} args - Arguments to find a DialogueTurn
   * @example
   * // Get one DialogueTurn
   * const dialogueTurn = await prisma.dialogueTurn.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DialogueTurnFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DialogueTurnFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DialogueTurnClient<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DialogueTurns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTurnFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DialogueTurns
   * const dialogueTurns = await prisma.dialogueTurn.findMany()
   * 
   * // Get first 10 DialogueTurns
   * const dialogueTurns = await prisma.dialogueTurn.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dialogueTurnWithIdOnly = await prisma.dialogueTurn.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DialogueTurnFindManyArgs>(args?: Prisma.SelectSubset<T, DialogueTurnFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DialogueTurn.
   * @param {DialogueTurnCreateArgs} args - Arguments to create a DialogueTurn.
   * @example
   * // Create one DialogueTurn
   * const DialogueTurn = await prisma.dialogueTurn.create({
   *   data: {
   *     // ... data to create a DialogueTurn
   *   }
   * })
   * 
   */
  create<T extends DialogueTurnCreateArgs>(args: Prisma.SelectSubset<T, DialogueTurnCreateArgs<ExtArgs>>): Prisma.Prisma__DialogueTurnClient<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DialogueTurns.
   * @param {DialogueTurnCreateManyArgs} args - Arguments to create many DialogueTurns.
   * @example
   * // Create many DialogueTurns
   * const dialogueTurn = await prisma.dialogueTurn.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DialogueTurnCreateManyArgs>(args?: Prisma.SelectSubset<T, DialogueTurnCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DialogueTurns and returns the data saved in the database.
   * @param {DialogueTurnCreateManyAndReturnArgs} args - Arguments to create many DialogueTurns.
   * @example
   * // Create many DialogueTurns
   * const dialogueTurn = await prisma.dialogueTurn.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DialogueTurns and only return the `id`
   * const dialogueTurnWithIdOnly = await prisma.dialogueTurn.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DialogueTurnCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DialogueTurnCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DialogueTurn.
   * @param {DialogueTurnDeleteArgs} args - Arguments to delete one DialogueTurn.
   * @example
   * // Delete one DialogueTurn
   * const DialogueTurn = await prisma.dialogueTurn.delete({
   *   where: {
   *     // ... filter to delete one DialogueTurn
   *   }
   * })
   * 
   */
  delete<T extends DialogueTurnDeleteArgs>(args: Prisma.SelectSubset<T, DialogueTurnDeleteArgs<ExtArgs>>): Prisma.Prisma__DialogueTurnClient<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DialogueTurn.
   * @param {DialogueTurnUpdateArgs} args - Arguments to update one DialogueTurn.
   * @example
   * // Update one DialogueTurn
   * const dialogueTurn = await prisma.dialogueTurn.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DialogueTurnUpdateArgs>(args: Prisma.SelectSubset<T, DialogueTurnUpdateArgs<ExtArgs>>): Prisma.Prisma__DialogueTurnClient<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DialogueTurns.
   * @param {DialogueTurnDeleteManyArgs} args - Arguments to filter DialogueTurns to delete.
   * @example
   * // Delete a few DialogueTurns
   * const { count } = await prisma.dialogueTurn.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DialogueTurnDeleteManyArgs>(args?: Prisma.SelectSubset<T, DialogueTurnDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DialogueTurns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTurnUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DialogueTurns
   * const dialogueTurn = await prisma.dialogueTurn.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DialogueTurnUpdateManyArgs>(args: Prisma.SelectSubset<T, DialogueTurnUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DialogueTurns and returns the data updated in the database.
   * @param {DialogueTurnUpdateManyAndReturnArgs} args - Arguments to update many DialogueTurns.
   * @example
   * // Update many DialogueTurns
   * const dialogueTurn = await prisma.dialogueTurn.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DialogueTurns and only return the `id`
   * const dialogueTurnWithIdOnly = await prisma.dialogueTurn.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DialogueTurnUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DialogueTurnUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DialogueTurn.
   * @param {DialogueTurnUpsertArgs} args - Arguments to update or create a DialogueTurn.
   * @example
   * // Update or create a DialogueTurn
   * const dialogueTurn = await prisma.dialogueTurn.upsert({
   *   create: {
   *     // ... data to create a DialogueTurn
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DialogueTurn we want to update
   *   }
   * })
   */
  upsert<T extends DialogueTurnUpsertArgs>(args: Prisma.SelectSubset<T, DialogueTurnUpsertArgs<ExtArgs>>): Prisma.Prisma__DialogueTurnClient<runtime.Types.Result.GetResult<Prisma.$DialogueTurnPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DialogueTurns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTurnCountArgs} args - Arguments to filter DialogueTurns to count.
   * @example
   * // Count the number of DialogueTurns
   * const count = await prisma.dialogueTurn.count({
   *   where: {
   *     // ... the filter for the DialogueTurns we want to count
   *   }
   * })
  **/
  count<T extends DialogueTurnCountArgs>(
    args?: Prisma.Subset<T, DialogueTurnCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DialogueTurnCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DialogueTurn.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTurnAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DialogueTurnAggregateArgs>(args: Prisma.Subset<T, DialogueTurnAggregateArgs>): Prisma.PrismaPromise<GetDialogueTurnAggregateType<T>>

  /**
   * Group by DialogueTurn.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueTurnGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DialogueTurnGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DialogueTurnGroupByArgs['orderBy'] }
      : { orderBy?: DialogueTurnGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DialogueTurnGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDialogueTurnGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DialogueTurn model
 */
readonly fields: DialogueTurnFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DialogueTurn.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DialogueTurnClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dialogue<T extends Prisma.DialogueDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DialogueDefaultArgs<ExtArgs>>): Prisma.Prisma__DialogueClient<runtime.Types.Result.GetResult<Prisma.$DialoguePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DialogueTurn model
 */
export interface DialogueTurnFieldRefs {
  readonly id: Prisma.FieldRef<"DialogueTurn", 'String'>
  readonly dialogueId: Prisma.FieldRef<"DialogueTurn", 'String'>
  readonly commandId: Prisma.FieldRef<"DialogueTurn", 'String'>
  readonly userItemId: Prisma.FieldRef<"DialogueTurn", 'String'>
  readonly inputSha256: Prisma.FieldRef<"DialogueTurn", 'String'>
  readonly status: Prisma.FieldRef<"DialogueTurn", 'DialogueTurnStatus'>
  readonly dispatchState: Prisma.FieldRef<"DialogueTurn", 'DialogueDispatchState'>
  readonly cancelRequested: Prisma.FieldRef<"DialogueTurn", 'Boolean'>
  readonly runtimeSessionId: Prisma.FieldRef<"DialogueTurn", 'String'>
  readonly outcome: Prisma.FieldRef<"DialogueTurn", 'Json'>
  readonly createdAt: Prisma.FieldRef<"DialogueTurn", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"DialogueTurn", 'DateTime'>
  readonly endItemSequence: Prisma.FieldRef<"DialogueTurn", 'BigInt'>
}
    

// Custom InputTypes
/**
 * DialogueTurn findUnique
 */
export type DialogueTurnFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTurn to fetch.
   */
  where: Prisma.DialogueTurnWhereUniqueInput
}

/**
 * DialogueTurn findUniqueOrThrow
 */
export type DialogueTurnFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTurn to fetch.
   */
  where: Prisma.DialogueTurnWhereUniqueInput
}

/**
 * DialogueTurn findFirst
 */
export type DialogueTurnFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTurn to fetch.
   */
  where?: Prisma.DialogueTurnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueTurns to fetch.
   */
  orderBy?: Prisma.DialogueTurnOrderByWithRelationInput | Prisma.DialogueTurnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DialogueTurns.
   */
  cursor?: Prisma.DialogueTurnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueTurns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueTurns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DialogueTurns.
   */
  distinct?: Prisma.DialogueTurnScalarFieldEnum | Prisma.DialogueTurnScalarFieldEnum[]
}

/**
 * DialogueTurn findFirstOrThrow
 */
export type DialogueTurnFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTurn to fetch.
   */
  where?: Prisma.DialogueTurnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueTurns to fetch.
   */
  orderBy?: Prisma.DialogueTurnOrderByWithRelationInput | Prisma.DialogueTurnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DialogueTurns.
   */
  cursor?: Prisma.DialogueTurnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueTurns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueTurns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DialogueTurns.
   */
  distinct?: Prisma.DialogueTurnScalarFieldEnum | Prisma.DialogueTurnScalarFieldEnum[]
}

/**
 * DialogueTurn findMany
 */
export type DialogueTurnFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
  /**
   * Filter, which DialogueTurns to fetch.
   */
  where?: Prisma.DialogueTurnWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueTurns to fetch.
   */
  orderBy?: Prisma.DialogueTurnOrderByWithRelationInput | Prisma.DialogueTurnOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DialogueTurns.
   */
  cursor?: Prisma.DialogueTurnWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueTurns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueTurns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DialogueTurns.
   */
  distinct?: Prisma.DialogueTurnScalarFieldEnum | Prisma.DialogueTurnScalarFieldEnum[]
}

/**
 * DialogueTurn create
 */
export type DialogueTurnCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
  /**
   * The data needed to create a DialogueTurn.
   */
  data: Prisma.XOR<Prisma.DialogueTurnCreateInput, Prisma.DialogueTurnUncheckedCreateInput>
}

/**
 * DialogueTurn createMany
 */
export type DialogueTurnCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DialogueTurns.
   */
  data: Prisma.DialogueTurnCreateManyInput | Prisma.DialogueTurnCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DialogueTurn createManyAndReturn
 */
export type DialogueTurnCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * The data used to create many DialogueTurns.
   */
  data: Prisma.DialogueTurnCreateManyInput | Prisma.DialogueTurnCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DialogueTurn update
 */
export type DialogueTurnUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
  /**
   * The data needed to update a DialogueTurn.
   */
  data: Prisma.XOR<Prisma.DialogueTurnUpdateInput, Prisma.DialogueTurnUncheckedUpdateInput>
  /**
   * Choose, which DialogueTurn to update.
   */
  where: Prisma.DialogueTurnWhereUniqueInput
}

/**
 * DialogueTurn updateMany
 */
export type DialogueTurnUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DialogueTurns.
   */
  data: Prisma.XOR<Prisma.DialogueTurnUpdateManyMutationInput, Prisma.DialogueTurnUncheckedUpdateManyInput>
  /**
   * Filter which DialogueTurns to update
   */
  where?: Prisma.DialogueTurnWhereInput
  /**
   * Limit how many DialogueTurns to update.
   */
  limit?: number
}

/**
 * DialogueTurn updateManyAndReturn
 */
export type DialogueTurnUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * The data used to update DialogueTurns.
   */
  data: Prisma.XOR<Prisma.DialogueTurnUpdateManyMutationInput, Prisma.DialogueTurnUncheckedUpdateManyInput>
  /**
   * Filter which DialogueTurns to update
   */
  where?: Prisma.DialogueTurnWhereInput
  /**
   * Limit how many DialogueTurns to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DialogueTurn upsert
 */
export type DialogueTurnUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
  /**
   * The filter to search for the DialogueTurn to update in case it exists.
   */
  where: Prisma.DialogueTurnWhereUniqueInput
  /**
   * In case the DialogueTurn found by the `where` argument doesn't exist, create a new DialogueTurn with this data.
   */
  create: Prisma.XOR<Prisma.DialogueTurnCreateInput, Prisma.DialogueTurnUncheckedCreateInput>
  /**
   * In case the DialogueTurn was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DialogueTurnUpdateInput, Prisma.DialogueTurnUncheckedUpdateInput>
}

/**
 * DialogueTurn delete
 */
export type DialogueTurnDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
  /**
   * Filter which DialogueTurn to delete.
   */
  where: Prisma.DialogueTurnWhereUniqueInput
}

/**
 * DialogueTurn deleteMany
 */
export type DialogueTurnDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DialogueTurns to delete
   */
  where?: Prisma.DialogueTurnWhereInput
  /**
   * Limit how many DialogueTurns to delete.
   */
  limit?: number
}

/**
 * DialogueTurn without action
 */
export type DialogueTurnDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueTurn
   */
  select?: Prisma.DialogueTurnSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueTurn
   */
  omit?: Prisma.DialogueTurnOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueTurnInclude<ExtArgs> | null
}
