
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DialogueInteraction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DialogueInteraction
 * 
 */
export type DialogueInteractionModel = runtime.Types.Result.DefaultSelection<Prisma.$DialogueInteractionPayload>

export type AggregateDialogueInteraction = {
  _count: DialogueInteractionCountAggregateOutputType | null
  _min: DialogueInteractionMinAggregateOutputType | null
  _max: DialogueInteractionMaxAggregateOutputType | null
}

export type DialogueInteractionMinAggregateOutputType = {
  id: string | null
  dialogueId: string | null
  turnId: string | null
  runtimeSessionId: string | null
  runtimeRequestId: string | null
  status: $Enums.DialogueInteractionStatus | null
  responseCommandId: string | null
}

export type DialogueInteractionMaxAggregateOutputType = {
  id: string | null
  dialogueId: string | null
  turnId: string | null
  runtimeSessionId: string | null
  runtimeRequestId: string | null
  status: $Enums.DialogueInteractionStatus | null
  responseCommandId: string | null
}

export type DialogueInteractionCountAggregateOutputType = {
  id: number
  dialogueId: number
  turnId: number
  runtimeSessionId: number
  runtimeRequestId: number
  status: number
  request: number
  response: number
  responseCommandId: number
  _all: number
}


export type DialogueInteractionMinAggregateInputType = {
  id?: true
  dialogueId?: true
  turnId?: true
  runtimeSessionId?: true
  runtimeRequestId?: true
  status?: true
  responseCommandId?: true
}

export type DialogueInteractionMaxAggregateInputType = {
  id?: true
  dialogueId?: true
  turnId?: true
  runtimeSessionId?: true
  runtimeRequestId?: true
  status?: true
  responseCommandId?: true
}

export type DialogueInteractionCountAggregateInputType = {
  id?: true
  dialogueId?: true
  turnId?: true
  runtimeSessionId?: true
  runtimeRequestId?: true
  status?: true
  request?: true
  response?: true
  responseCommandId?: true
  _all?: true
}

export type DialogueInteractionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DialogueInteraction to aggregate.
   */
  where?: Prisma.DialogueInteractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueInteractions to fetch.
   */
  orderBy?: Prisma.DialogueInteractionOrderByWithRelationInput | Prisma.DialogueInteractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DialogueInteractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueInteractions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueInteractions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DialogueInteractions
  **/
  _count?: true | DialogueInteractionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DialogueInteractionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DialogueInteractionMaxAggregateInputType
}

export type GetDialogueInteractionAggregateType<T extends DialogueInteractionAggregateArgs> = {
      [P in keyof T & keyof AggregateDialogueInteraction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDialogueInteraction[P]>
    : Prisma.GetScalarType<T[P], AggregateDialogueInteraction[P]>
}




export type DialogueInteractionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DialogueInteractionWhereInput
  orderBy?: Prisma.DialogueInteractionOrderByWithAggregationInput | Prisma.DialogueInteractionOrderByWithAggregationInput[]
  by: Prisma.DialogueInteractionScalarFieldEnum[] | Prisma.DialogueInteractionScalarFieldEnum
  having?: Prisma.DialogueInteractionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DialogueInteractionCountAggregateInputType | true
  _min?: DialogueInteractionMinAggregateInputType
  _max?: DialogueInteractionMaxAggregateInputType
}

export type DialogueInteractionGroupByOutputType = {
  id: string
  dialogueId: string
  turnId: string | null
  runtimeSessionId: string
  runtimeRequestId: string
  status: $Enums.DialogueInteractionStatus
  request: runtime.JsonValue
  response: runtime.JsonValue | null
  responseCommandId: string | null
  _count: DialogueInteractionCountAggregateOutputType | null
  _min: DialogueInteractionMinAggregateOutputType | null
  _max: DialogueInteractionMaxAggregateOutputType | null
}

export type GetDialogueInteractionGroupByPayload<T extends DialogueInteractionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DialogueInteractionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DialogueInteractionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DialogueInteractionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DialogueInteractionGroupByOutputType[P]>
      }
    >
  >



export type DialogueInteractionWhereInput = {
  AND?: Prisma.DialogueInteractionWhereInput | Prisma.DialogueInteractionWhereInput[]
  OR?: Prisma.DialogueInteractionWhereInput[]
  NOT?: Prisma.DialogueInteractionWhereInput | Prisma.DialogueInteractionWhereInput[]
  id?: Prisma.StringFilter<"DialogueInteraction"> | string
  dialogueId?: Prisma.StringFilter<"DialogueInteraction"> | string
  turnId?: Prisma.StringNullableFilter<"DialogueInteraction"> | string | null
  runtimeSessionId?: Prisma.StringFilter<"DialogueInteraction"> | string
  runtimeRequestId?: Prisma.StringFilter<"DialogueInteraction"> | string
  status?: Prisma.EnumDialogueInteractionStatusFilter<"DialogueInteraction"> | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonFilter<"DialogueInteraction">
  response?: Prisma.JsonNullableFilter<"DialogueInteraction">
  responseCommandId?: Prisma.StringNullableFilter<"DialogueInteraction"> | string | null
  dialogue?: Prisma.XOR<Prisma.DialogueScalarRelationFilter, Prisma.DialogueWhereInput>
}

export type DialogueInteractionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  turnId?: Prisma.SortOrderInput | Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrder
  runtimeRequestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  request?: Prisma.SortOrder
  response?: Prisma.SortOrderInput | Prisma.SortOrder
  responseCommandId?: Prisma.SortOrderInput | Prisma.SortOrder
  dialogue?: Prisma.DialogueOrderByWithRelationInput
}

export type DialogueInteractionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  runtimeSessionId_runtimeRequestId?: Prisma.DialogueInteractionRuntimeSessionIdRuntimeRequestIdCompoundUniqueInput
  AND?: Prisma.DialogueInteractionWhereInput | Prisma.DialogueInteractionWhereInput[]
  OR?: Prisma.DialogueInteractionWhereInput[]
  NOT?: Prisma.DialogueInteractionWhereInput | Prisma.DialogueInteractionWhereInput[]
  dialogueId?: Prisma.StringFilter<"DialogueInteraction"> | string
  turnId?: Prisma.StringNullableFilter<"DialogueInteraction"> | string | null
  runtimeSessionId?: Prisma.StringFilter<"DialogueInteraction"> | string
  runtimeRequestId?: Prisma.StringFilter<"DialogueInteraction"> | string
  status?: Prisma.EnumDialogueInteractionStatusFilter<"DialogueInteraction"> | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonFilter<"DialogueInteraction">
  response?: Prisma.JsonNullableFilter<"DialogueInteraction">
  responseCommandId?: Prisma.StringNullableFilter<"DialogueInteraction"> | string | null
  dialogue?: Prisma.XOR<Prisma.DialogueScalarRelationFilter, Prisma.DialogueWhereInput>
}, "id" | "runtimeSessionId_runtimeRequestId">

export type DialogueInteractionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  turnId?: Prisma.SortOrderInput | Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrder
  runtimeRequestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  request?: Prisma.SortOrder
  response?: Prisma.SortOrderInput | Prisma.SortOrder
  responseCommandId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DialogueInteractionCountOrderByAggregateInput
  _max?: Prisma.DialogueInteractionMaxOrderByAggregateInput
  _min?: Prisma.DialogueInteractionMinOrderByAggregateInput
}

export type DialogueInteractionScalarWhereWithAggregatesInput = {
  AND?: Prisma.DialogueInteractionScalarWhereWithAggregatesInput | Prisma.DialogueInteractionScalarWhereWithAggregatesInput[]
  OR?: Prisma.DialogueInteractionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DialogueInteractionScalarWhereWithAggregatesInput | Prisma.DialogueInteractionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DialogueInteraction"> | string
  dialogueId?: Prisma.StringWithAggregatesFilter<"DialogueInteraction"> | string
  turnId?: Prisma.StringNullableWithAggregatesFilter<"DialogueInteraction"> | string | null
  runtimeSessionId?: Prisma.StringWithAggregatesFilter<"DialogueInteraction"> | string
  runtimeRequestId?: Prisma.StringWithAggregatesFilter<"DialogueInteraction"> | string
  status?: Prisma.EnumDialogueInteractionStatusWithAggregatesFilter<"DialogueInteraction"> | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonWithAggregatesFilter<"DialogueInteraction">
  response?: Prisma.JsonNullableWithAggregatesFilter<"DialogueInteraction">
  responseCommandId?: Prisma.StringNullableWithAggregatesFilter<"DialogueInteraction"> | string | null
}

export type DialogueInteractionCreateInput = {
  id: string
  turnId?: string | null
  runtimeSessionId: string
  runtimeRequestId: string
  status?: $Enums.DialogueInteractionStatus
  request: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: string | null
  dialogue: Prisma.DialogueCreateNestedOneWithoutInteractionsInput
}

export type DialogueInteractionUncheckedCreateInput = {
  id: string
  dialogueId: string
  turnId?: string | null
  runtimeSessionId: string
  runtimeRequestId: string
  status?: $Enums.DialogueInteractionStatus
  request: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: string | null
}

export type DialogueInteractionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  turnId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  runtimeSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  runtimeRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueInteractionStatusFieldUpdateOperationsInput | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dialogue?: Prisma.DialogueUpdateOneRequiredWithoutInteractionsNestedInput
}

export type DialogueInteractionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dialogueId?: Prisma.StringFieldUpdateOperationsInput | string
  turnId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  runtimeSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  runtimeRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueInteractionStatusFieldUpdateOperationsInput | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DialogueInteractionCreateManyInput = {
  id: string
  dialogueId: string
  turnId?: string | null
  runtimeSessionId: string
  runtimeRequestId: string
  status?: $Enums.DialogueInteractionStatus
  request: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: string | null
}

export type DialogueInteractionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  turnId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  runtimeSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  runtimeRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueInteractionStatusFieldUpdateOperationsInput | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DialogueInteractionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dialogueId?: Prisma.StringFieldUpdateOperationsInput | string
  turnId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  runtimeSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  runtimeRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueInteractionStatusFieldUpdateOperationsInput | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DialogueInteractionListRelationFilter = {
  every?: Prisma.DialogueInteractionWhereInput
  some?: Prisma.DialogueInteractionWhereInput
  none?: Prisma.DialogueInteractionWhereInput
}

export type DialogueInteractionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DialogueInteractionRuntimeSessionIdRuntimeRequestIdCompoundUniqueInput = {
  runtimeSessionId: string
  runtimeRequestId: string
}

export type DialogueInteractionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  turnId?: Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrder
  runtimeRequestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  request?: Prisma.SortOrder
  response?: Prisma.SortOrder
  responseCommandId?: Prisma.SortOrder
}

export type DialogueInteractionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  turnId?: Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrder
  runtimeRequestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  responseCommandId?: Prisma.SortOrder
}

export type DialogueInteractionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dialogueId?: Prisma.SortOrder
  turnId?: Prisma.SortOrder
  runtimeSessionId?: Prisma.SortOrder
  runtimeRequestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  responseCommandId?: Prisma.SortOrder
}

export type DialogueInteractionCreateNestedManyWithoutDialogueInput = {
  create?: Prisma.XOR<Prisma.DialogueInteractionCreateWithoutDialogueInput, Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput> | Prisma.DialogueInteractionCreateWithoutDialogueInput[] | Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.DialogueInteractionCreateOrConnectWithoutDialogueInput | Prisma.DialogueInteractionCreateOrConnectWithoutDialogueInput[]
  createMany?: Prisma.DialogueInteractionCreateManyDialogueInputEnvelope
  connect?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
}

export type DialogueInteractionUncheckedCreateNestedManyWithoutDialogueInput = {
  create?: Prisma.XOR<Prisma.DialogueInteractionCreateWithoutDialogueInput, Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput> | Prisma.DialogueInteractionCreateWithoutDialogueInput[] | Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.DialogueInteractionCreateOrConnectWithoutDialogueInput | Prisma.DialogueInteractionCreateOrConnectWithoutDialogueInput[]
  createMany?: Prisma.DialogueInteractionCreateManyDialogueInputEnvelope
  connect?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
}

export type DialogueInteractionUpdateManyWithoutDialogueNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueInteractionCreateWithoutDialogueInput, Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput> | Prisma.DialogueInteractionCreateWithoutDialogueInput[] | Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.DialogueInteractionCreateOrConnectWithoutDialogueInput | Prisma.DialogueInteractionCreateOrConnectWithoutDialogueInput[]
  upsert?: Prisma.DialogueInteractionUpsertWithWhereUniqueWithoutDialogueInput | Prisma.DialogueInteractionUpsertWithWhereUniqueWithoutDialogueInput[]
  createMany?: Prisma.DialogueInteractionCreateManyDialogueInputEnvelope
  set?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
  disconnect?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
  delete?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
  connect?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
  update?: Prisma.DialogueInteractionUpdateWithWhereUniqueWithoutDialogueInput | Prisma.DialogueInteractionUpdateWithWhereUniqueWithoutDialogueInput[]
  updateMany?: Prisma.DialogueInteractionUpdateManyWithWhereWithoutDialogueInput | Prisma.DialogueInteractionUpdateManyWithWhereWithoutDialogueInput[]
  deleteMany?: Prisma.DialogueInteractionScalarWhereInput | Prisma.DialogueInteractionScalarWhereInput[]
}

export type DialogueInteractionUncheckedUpdateManyWithoutDialogueNestedInput = {
  create?: Prisma.XOR<Prisma.DialogueInteractionCreateWithoutDialogueInput, Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput> | Prisma.DialogueInteractionCreateWithoutDialogueInput[] | Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput[]
  connectOrCreate?: Prisma.DialogueInteractionCreateOrConnectWithoutDialogueInput | Prisma.DialogueInteractionCreateOrConnectWithoutDialogueInput[]
  upsert?: Prisma.DialogueInteractionUpsertWithWhereUniqueWithoutDialogueInput | Prisma.DialogueInteractionUpsertWithWhereUniqueWithoutDialogueInput[]
  createMany?: Prisma.DialogueInteractionCreateManyDialogueInputEnvelope
  set?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
  disconnect?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
  delete?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
  connect?: Prisma.DialogueInteractionWhereUniqueInput | Prisma.DialogueInteractionWhereUniqueInput[]
  update?: Prisma.DialogueInteractionUpdateWithWhereUniqueWithoutDialogueInput | Prisma.DialogueInteractionUpdateWithWhereUniqueWithoutDialogueInput[]
  updateMany?: Prisma.DialogueInteractionUpdateManyWithWhereWithoutDialogueInput | Prisma.DialogueInteractionUpdateManyWithWhereWithoutDialogueInput[]
  deleteMany?: Prisma.DialogueInteractionScalarWhereInput | Prisma.DialogueInteractionScalarWhereInput[]
}

export type EnumDialogueInteractionStatusFieldUpdateOperationsInput = {
  set?: $Enums.DialogueInteractionStatus
}

export type DialogueInteractionCreateWithoutDialogueInput = {
  id: string
  turnId?: string | null
  runtimeSessionId: string
  runtimeRequestId: string
  status?: $Enums.DialogueInteractionStatus
  request: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: string | null
}

export type DialogueInteractionUncheckedCreateWithoutDialogueInput = {
  id: string
  turnId?: string | null
  runtimeSessionId: string
  runtimeRequestId: string
  status?: $Enums.DialogueInteractionStatus
  request: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: string | null
}

export type DialogueInteractionCreateOrConnectWithoutDialogueInput = {
  where: Prisma.DialogueInteractionWhereUniqueInput
  create: Prisma.XOR<Prisma.DialogueInteractionCreateWithoutDialogueInput, Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput>
}

export type DialogueInteractionCreateManyDialogueInputEnvelope = {
  data: Prisma.DialogueInteractionCreateManyDialogueInput | Prisma.DialogueInteractionCreateManyDialogueInput[]
  skipDuplicates?: boolean
}

export type DialogueInteractionUpsertWithWhereUniqueWithoutDialogueInput = {
  where: Prisma.DialogueInteractionWhereUniqueInput
  update: Prisma.XOR<Prisma.DialogueInteractionUpdateWithoutDialogueInput, Prisma.DialogueInteractionUncheckedUpdateWithoutDialogueInput>
  create: Prisma.XOR<Prisma.DialogueInteractionCreateWithoutDialogueInput, Prisma.DialogueInteractionUncheckedCreateWithoutDialogueInput>
}

export type DialogueInteractionUpdateWithWhereUniqueWithoutDialogueInput = {
  where: Prisma.DialogueInteractionWhereUniqueInput
  data: Prisma.XOR<Prisma.DialogueInteractionUpdateWithoutDialogueInput, Prisma.DialogueInteractionUncheckedUpdateWithoutDialogueInput>
}

export type DialogueInteractionUpdateManyWithWhereWithoutDialogueInput = {
  where: Prisma.DialogueInteractionScalarWhereInput
  data: Prisma.XOR<Prisma.DialogueInteractionUpdateManyMutationInput, Prisma.DialogueInteractionUncheckedUpdateManyWithoutDialogueInput>
}

export type DialogueInteractionScalarWhereInput = {
  AND?: Prisma.DialogueInteractionScalarWhereInput | Prisma.DialogueInteractionScalarWhereInput[]
  OR?: Prisma.DialogueInteractionScalarWhereInput[]
  NOT?: Prisma.DialogueInteractionScalarWhereInput | Prisma.DialogueInteractionScalarWhereInput[]
  id?: Prisma.StringFilter<"DialogueInteraction"> | string
  dialogueId?: Prisma.StringFilter<"DialogueInteraction"> | string
  turnId?: Prisma.StringNullableFilter<"DialogueInteraction"> | string | null
  runtimeSessionId?: Prisma.StringFilter<"DialogueInteraction"> | string
  runtimeRequestId?: Prisma.StringFilter<"DialogueInteraction"> | string
  status?: Prisma.EnumDialogueInteractionStatusFilter<"DialogueInteraction"> | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonFilter<"DialogueInteraction">
  response?: Prisma.JsonNullableFilter<"DialogueInteraction">
  responseCommandId?: Prisma.StringNullableFilter<"DialogueInteraction"> | string | null
}

export type DialogueInteractionCreateManyDialogueInput = {
  id: string
  turnId?: string | null
  runtimeSessionId: string
  runtimeRequestId: string
  status?: $Enums.DialogueInteractionStatus
  request: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: string | null
}

export type DialogueInteractionUpdateWithoutDialogueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  turnId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  runtimeSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  runtimeRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueInteractionStatusFieldUpdateOperationsInput | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DialogueInteractionUncheckedUpdateWithoutDialogueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  turnId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  runtimeSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  runtimeRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueInteractionStatusFieldUpdateOperationsInput | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DialogueInteractionUncheckedUpdateManyWithoutDialogueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  turnId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  runtimeSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  runtimeRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDialogueInteractionStatusFieldUpdateOperationsInput | $Enums.DialogueInteractionStatus
  request?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  response?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  responseCommandId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type DialogueInteractionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dialogueId?: boolean
  turnId?: boolean
  runtimeSessionId?: boolean
  runtimeRequestId?: boolean
  status?: boolean
  request?: boolean
  response?: boolean
  responseCommandId?: boolean
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dialogueInteraction"]>

export type DialogueInteractionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dialogueId?: boolean
  turnId?: boolean
  runtimeSessionId?: boolean
  runtimeRequestId?: boolean
  status?: boolean
  request?: boolean
  response?: boolean
  responseCommandId?: boolean
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dialogueInteraction"]>

export type DialogueInteractionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dialogueId?: boolean
  turnId?: boolean
  runtimeSessionId?: boolean
  runtimeRequestId?: boolean
  status?: boolean
  request?: boolean
  response?: boolean
  responseCommandId?: boolean
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dialogueInteraction"]>

export type DialogueInteractionSelectScalar = {
  id?: boolean
  dialogueId?: boolean
  turnId?: boolean
  runtimeSessionId?: boolean
  runtimeRequestId?: boolean
  status?: boolean
  request?: boolean
  response?: boolean
  responseCommandId?: boolean
}

export type DialogueInteractionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "dialogueId" | "turnId" | "runtimeSessionId" | "runtimeRequestId" | "status" | "request" | "response" | "responseCommandId", ExtArgs["result"]["dialogueInteraction"]>
export type DialogueInteractionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}
export type DialogueInteractionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}
export type DialogueInteractionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dialogue?: boolean | Prisma.DialogueDefaultArgs<ExtArgs>
}

export type $DialogueInteractionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DialogueInteraction"
  objects: {
    dialogue: Prisma.$DialoguePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    dialogueId: string
    turnId: string | null
    runtimeSessionId: string
    runtimeRequestId: string
    status: $Enums.DialogueInteractionStatus
    request: runtime.JsonValue
    response: runtime.JsonValue | null
    responseCommandId: string | null
  }, ExtArgs["result"]["dialogueInteraction"]>
  composites: {}
}

export type DialogueInteractionGetPayload<S extends boolean | null | undefined | DialogueInteractionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload, S>

export type DialogueInteractionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DialogueInteractionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DialogueInteractionCountAggregateInputType | true
  }

export interface DialogueInteractionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DialogueInteraction'], meta: { name: 'DialogueInteraction' } }
  /**
   * Find zero or one DialogueInteraction that matches the filter.
   * @param {DialogueInteractionFindUniqueArgs} args - Arguments to find a DialogueInteraction
   * @example
   * // Get one DialogueInteraction
   * const dialogueInteraction = await prisma.dialogueInteraction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DialogueInteractionFindUniqueArgs>(args: Prisma.SelectSubset<T, DialogueInteractionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DialogueInteractionClient<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DialogueInteraction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DialogueInteractionFindUniqueOrThrowArgs} args - Arguments to find a DialogueInteraction
   * @example
   * // Get one DialogueInteraction
   * const dialogueInteraction = await prisma.dialogueInteraction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DialogueInteractionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DialogueInteractionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DialogueInteractionClient<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DialogueInteraction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueInteractionFindFirstArgs} args - Arguments to find a DialogueInteraction
   * @example
   * // Get one DialogueInteraction
   * const dialogueInteraction = await prisma.dialogueInteraction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DialogueInteractionFindFirstArgs>(args?: Prisma.SelectSubset<T, DialogueInteractionFindFirstArgs<ExtArgs>>): Prisma.Prisma__DialogueInteractionClient<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DialogueInteraction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueInteractionFindFirstOrThrowArgs} args - Arguments to find a DialogueInteraction
   * @example
   * // Get one DialogueInteraction
   * const dialogueInteraction = await prisma.dialogueInteraction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DialogueInteractionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DialogueInteractionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DialogueInteractionClient<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DialogueInteractions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueInteractionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DialogueInteractions
   * const dialogueInteractions = await prisma.dialogueInteraction.findMany()
   * 
   * // Get first 10 DialogueInteractions
   * const dialogueInteractions = await prisma.dialogueInteraction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dialogueInteractionWithIdOnly = await prisma.dialogueInteraction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DialogueInteractionFindManyArgs>(args?: Prisma.SelectSubset<T, DialogueInteractionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DialogueInteraction.
   * @param {DialogueInteractionCreateArgs} args - Arguments to create a DialogueInteraction.
   * @example
   * // Create one DialogueInteraction
   * const DialogueInteraction = await prisma.dialogueInteraction.create({
   *   data: {
   *     // ... data to create a DialogueInteraction
   *   }
   * })
   * 
   */
  create<T extends DialogueInteractionCreateArgs>(args: Prisma.SelectSubset<T, DialogueInteractionCreateArgs<ExtArgs>>): Prisma.Prisma__DialogueInteractionClient<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DialogueInteractions.
   * @param {DialogueInteractionCreateManyArgs} args - Arguments to create many DialogueInteractions.
   * @example
   * // Create many DialogueInteractions
   * const dialogueInteraction = await prisma.dialogueInteraction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DialogueInteractionCreateManyArgs>(args?: Prisma.SelectSubset<T, DialogueInteractionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DialogueInteractions and returns the data saved in the database.
   * @param {DialogueInteractionCreateManyAndReturnArgs} args - Arguments to create many DialogueInteractions.
   * @example
   * // Create many DialogueInteractions
   * const dialogueInteraction = await prisma.dialogueInteraction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DialogueInteractions and only return the `id`
   * const dialogueInteractionWithIdOnly = await prisma.dialogueInteraction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DialogueInteractionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DialogueInteractionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DialogueInteraction.
   * @param {DialogueInteractionDeleteArgs} args - Arguments to delete one DialogueInteraction.
   * @example
   * // Delete one DialogueInteraction
   * const DialogueInteraction = await prisma.dialogueInteraction.delete({
   *   where: {
   *     // ... filter to delete one DialogueInteraction
   *   }
   * })
   * 
   */
  delete<T extends DialogueInteractionDeleteArgs>(args: Prisma.SelectSubset<T, DialogueInteractionDeleteArgs<ExtArgs>>): Prisma.Prisma__DialogueInteractionClient<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DialogueInteraction.
   * @param {DialogueInteractionUpdateArgs} args - Arguments to update one DialogueInteraction.
   * @example
   * // Update one DialogueInteraction
   * const dialogueInteraction = await prisma.dialogueInteraction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DialogueInteractionUpdateArgs>(args: Prisma.SelectSubset<T, DialogueInteractionUpdateArgs<ExtArgs>>): Prisma.Prisma__DialogueInteractionClient<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DialogueInteractions.
   * @param {DialogueInteractionDeleteManyArgs} args - Arguments to filter DialogueInteractions to delete.
   * @example
   * // Delete a few DialogueInteractions
   * const { count } = await prisma.dialogueInteraction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DialogueInteractionDeleteManyArgs>(args?: Prisma.SelectSubset<T, DialogueInteractionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DialogueInteractions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueInteractionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DialogueInteractions
   * const dialogueInteraction = await prisma.dialogueInteraction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DialogueInteractionUpdateManyArgs>(args: Prisma.SelectSubset<T, DialogueInteractionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DialogueInteractions and returns the data updated in the database.
   * @param {DialogueInteractionUpdateManyAndReturnArgs} args - Arguments to update many DialogueInteractions.
   * @example
   * // Update many DialogueInteractions
   * const dialogueInteraction = await prisma.dialogueInteraction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DialogueInteractions and only return the `id`
   * const dialogueInteractionWithIdOnly = await prisma.dialogueInteraction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DialogueInteractionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DialogueInteractionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DialogueInteraction.
   * @param {DialogueInteractionUpsertArgs} args - Arguments to update or create a DialogueInteraction.
   * @example
   * // Update or create a DialogueInteraction
   * const dialogueInteraction = await prisma.dialogueInteraction.upsert({
   *   create: {
   *     // ... data to create a DialogueInteraction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DialogueInteraction we want to update
   *   }
   * })
   */
  upsert<T extends DialogueInteractionUpsertArgs>(args: Prisma.SelectSubset<T, DialogueInteractionUpsertArgs<ExtArgs>>): Prisma.Prisma__DialogueInteractionClient<runtime.Types.Result.GetResult<Prisma.$DialogueInteractionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DialogueInteractions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueInteractionCountArgs} args - Arguments to filter DialogueInteractions to count.
   * @example
   * // Count the number of DialogueInteractions
   * const count = await prisma.dialogueInteraction.count({
   *   where: {
   *     // ... the filter for the DialogueInteractions we want to count
   *   }
   * })
  **/
  count<T extends DialogueInteractionCountArgs>(
    args?: Prisma.Subset<T, DialogueInteractionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DialogueInteractionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DialogueInteraction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueInteractionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DialogueInteractionAggregateArgs>(args: Prisma.Subset<T, DialogueInteractionAggregateArgs>): Prisma.PrismaPromise<GetDialogueInteractionAggregateType<T>>

  /**
   * Group by DialogueInteraction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DialogueInteractionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DialogueInteractionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DialogueInteractionGroupByArgs['orderBy'] }
      : { orderBy?: DialogueInteractionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DialogueInteractionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDialogueInteractionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DialogueInteraction model
 */
readonly fields: DialogueInteractionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DialogueInteraction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DialogueInteractionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dialogue<T extends Prisma.DialogueDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DialogueDefaultArgs<ExtArgs>>): Prisma.Prisma__DialogueClient<runtime.Types.Result.GetResult<Prisma.$DialoguePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DialogueInteraction model
 */
export interface DialogueInteractionFieldRefs {
  readonly id: Prisma.FieldRef<"DialogueInteraction", 'String'>
  readonly dialogueId: Prisma.FieldRef<"DialogueInteraction", 'String'>
  readonly turnId: Prisma.FieldRef<"DialogueInteraction", 'String'>
  readonly runtimeSessionId: Prisma.FieldRef<"DialogueInteraction", 'String'>
  readonly runtimeRequestId: Prisma.FieldRef<"DialogueInteraction", 'String'>
  readonly status: Prisma.FieldRef<"DialogueInteraction", 'DialogueInteractionStatus'>
  readonly request: Prisma.FieldRef<"DialogueInteraction", 'Json'>
  readonly response: Prisma.FieldRef<"DialogueInteraction", 'Json'>
  readonly responseCommandId: Prisma.FieldRef<"DialogueInteraction", 'String'>
}
    

// Custom InputTypes
/**
 * DialogueInteraction findUnique
 */
export type DialogueInteractionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueInteraction to fetch.
   */
  where: Prisma.DialogueInteractionWhereUniqueInput
}

/**
 * DialogueInteraction findUniqueOrThrow
 */
export type DialogueInteractionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueInteraction to fetch.
   */
  where: Prisma.DialogueInteractionWhereUniqueInput
}

/**
 * DialogueInteraction findFirst
 */
export type DialogueInteractionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueInteraction to fetch.
   */
  where?: Prisma.DialogueInteractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueInteractions to fetch.
   */
  orderBy?: Prisma.DialogueInteractionOrderByWithRelationInput | Prisma.DialogueInteractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DialogueInteractions.
   */
  cursor?: Prisma.DialogueInteractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueInteractions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueInteractions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DialogueInteractions.
   */
  distinct?: Prisma.DialogueInteractionScalarFieldEnum | Prisma.DialogueInteractionScalarFieldEnum[]
}

/**
 * DialogueInteraction findFirstOrThrow
 */
export type DialogueInteractionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueInteraction to fetch.
   */
  where?: Prisma.DialogueInteractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueInteractions to fetch.
   */
  orderBy?: Prisma.DialogueInteractionOrderByWithRelationInput | Prisma.DialogueInteractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DialogueInteractions.
   */
  cursor?: Prisma.DialogueInteractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueInteractions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueInteractions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DialogueInteractions.
   */
  distinct?: Prisma.DialogueInteractionScalarFieldEnum | Prisma.DialogueInteractionScalarFieldEnum[]
}

/**
 * DialogueInteraction findMany
 */
export type DialogueInteractionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
  /**
   * Filter, which DialogueInteractions to fetch.
   */
  where?: Prisma.DialogueInteractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DialogueInteractions to fetch.
   */
  orderBy?: Prisma.DialogueInteractionOrderByWithRelationInput | Prisma.DialogueInteractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DialogueInteractions.
   */
  cursor?: Prisma.DialogueInteractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DialogueInteractions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DialogueInteractions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DialogueInteractions.
   */
  distinct?: Prisma.DialogueInteractionScalarFieldEnum | Prisma.DialogueInteractionScalarFieldEnum[]
}

/**
 * DialogueInteraction create
 */
export type DialogueInteractionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
  /**
   * The data needed to create a DialogueInteraction.
   */
  data: Prisma.XOR<Prisma.DialogueInteractionCreateInput, Prisma.DialogueInteractionUncheckedCreateInput>
}

/**
 * DialogueInteraction createMany
 */
export type DialogueInteractionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DialogueInteractions.
   */
  data: Prisma.DialogueInteractionCreateManyInput | Prisma.DialogueInteractionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DialogueInteraction createManyAndReturn
 */
export type DialogueInteractionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * The data used to create many DialogueInteractions.
   */
  data: Prisma.DialogueInteractionCreateManyInput | Prisma.DialogueInteractionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DialogueInteraction update
 */
export type DialogueInteractionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
  /**
   * The data needed to update a DialogueInteraction.
   */
  data: Prisma.XOR<Prisma.DialogueInteractionUpdateInput, Prisma.DialogueInteractionUncheckedUpdateInput>
  /**
   * Choose, which DialogueInteraction to update.
   */
  where: Prisma.DialogueInteractionWhereUniqueInput
}

/**
 * DialogueInteraction updateMany
 */
export type DialogueInteractionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DialogueInteractions.
   */
  data: Prisma.XOR<Prisma.DialogueInteractionUpdateManyMutationInput, Prisma.DialogueInteractionUncheckedUpdateManyInput>
  /**
   * Filter which DialogueInteractions to update
   */
  where?: Prisma.DialogueInteractionWhereInput
  /**
   * Limit how many DialogueInteractions to update.
   */
  limit?: number
}

/**
 * DialogueInteraction updateManyAndReturn
 */
export type DialogueInteractionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * The data used to update DialogueInteractions.
   */
  data: Prisma.XOR<Prisma.DialogueInteractionUpdateManyMutationInput, Prisma.DialogueInteractionUncheckedUpdateManyInput>
  /**
   * Filter which DialogueInteractions to update
   */
  where?: Prisma.DialogueInteractionWhereInput
  /**
   * Limit how many DialogueInteractions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DialogueInteraction upsert
 */
export type DialogueInteractionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
  /**
   * The filter to search for the DialogueInteraction to update in case it exists.
   */
  where: Prisma.DialogueInteractionWhereUniqueInput
  /**
   * In case the DialogueInteraction found by the `where` argument doesn't exist, create a new DialogueInteraction with this data.
   */
  create: Prisma.XOR<Prisma.DialogueInteractionCreateInput, Prisma.DialogueInteractionUncheckedCreateInput>
  /**
   * In case the DialogueInteraction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DialogueInteractionUpdateInput, Prisma.DialogueInteractionUncheckedUpdateInput>
}

/**
 * DialogueInteraction delete
 */
export type DialogueInteractionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
  /**
   * Filter which DialogueInteraction to delete.
   */
  where: Prisma.DialogueInteractionWhereUniqueInput
}

/**
 * DialogueInteraction deleteMany
 */
export type DialogueInteractionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DialogueInteractions to delete
   */
  where?: Prisma.DialogueInteractionWhereInput
  /**
   * Limit how many DialogueInteractions to delete.
   */
  limit?: number
}

/**
 * DialogueInteraction without action
 */
export type DialogueInteractionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DialogueInteraction
   */
  select?: Prisma.DialogueInteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DialogueInteraction
   */
  omit?: Prisma.DialogueInteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DialogueInteractionInclude<ExtArgs> | null
}
