
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReviewThread` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ReviewThread
 * 
 */
export type ReviewThreadModel = runtime.Types.Result.DefaultSelection<Prisma.$ReviewThreadPayload>

export type AggregateReviewThread = {
  _count: ReviewThreadCountAggregateOutputType | null
  _avg: ReviewThreadAvgAggregateOutputType | null
  _sum: ReviewThreadSumAggregateOutputType | null
  _min: ReviewThreadMinAggregateOutputType | null
  _max: ReviewThreadMaxAggregateOutputType | null
}

export type ReviewThreadAvgAggregateOutputType = {
  version: number | null
}

export type ReviewThreadSumAggregateOutputType = {
  version: number | null
}

export type ReviewThreadMinAggregateOutputType = {
  id: string | null
  scopeKey: string | null
  subjectKey: string | null
  contextKey: string | null
  version: number | null
  createdAt: Date | null
  resolvedAt: Date | null
  resolvedBy: string | null
}

export type ReviewThreadMaxAggregateOutputType = {
  id: string | null
  scopeKey: string | null
  subjectKey: string | null
  contextKey: string | null
  version: number | null
  createdAt: Date | null
  resolvedAt: Date | null
  resolvedBy: string | null
}

export type ReviewThreadCountAggregateOutputType = {
  id: number
  scopeKey: number
  subjectKey: number
  contextKey: number
  context: number
  version: number
  createdAt: number
  resolvedAt: number
  resolvedBy: number
  _all: number
}


export type ReviewThreadAvgAggregateInputType = {
  version?: true
}

export type ReviewThreadSumAggregateInputType = {
  version?: true
}

export type ReviewThreadMinAggregateInputType = {
  id?: true
  scopeKey?: true
  subjectKey?: true
  contextKey?: true
  version?: true
  createdAt?: true
  resolvedAt?: true
  resolvedBy?: true
}

export type ReviewThreadMaxAggregateInputType = {
  id?: true
  scopeKey?: true
  subjectKey?: true
  contextKey?: true
  version?: true
  createdAt?: true
  resolvedAt?: true
  resolvedBy?: true
}

export type ReviewThreadCountAggregateInputType = {
  id?: true
  scopeKey?: true
  subjectKey?: true
  contextKey?: true
  context?: true
  version?: true
  createdAt?: true
  resolvedAt?: true
  resolvedBy?: true
  _all?: true
}

export type ReviewThreadAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReviewThread to aggregate.
   */
  where?: Prisma.ReviewThreadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReviewThreads to fetch.
   */
  orderBy?: Prisma.ReviewThreadOrderByWithRelationInput | Prisma.ReviewThreadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReviewThreadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReviewThreads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReviewThreads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReviewThreads
  **/
  _count?: true | ReviewThreadCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReviewThreadAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReviewThreadSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReviewThreadMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReviewThreadMaxAggregateInputType
}

export type GetReviewThreadAggregateType<T extends ReviewThreadAggregateArgs> = {
      [P in keyof T & keyof AggregateReviewThread]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReviewThread[P]>
    : Prisma.GetScalarType<T[P], AggregateReviewThread[P]>
}




export type ReviewThreadGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewThreadWhereInput
  orderBy?: Prisma.ReviewThreadOrderByWithAggregationInput | Prisma.ReviewThreadOrderByWithAggregationInput[]
  by: Prisma.ReviewThreadScalarFieldEnum[] | Prisma.ReviewThreadScalarFieldEnum
  having?: Prisma.ReviewThreadScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReviewThreadCountAggregateInputType | true
  _avg?: ReviewThreadAvgAggregateInputType
  _sum?: ReviewThreadSumAggregateInputType
  _min?: ReviewThreadMinAggregateInputType
  _max?: ReviewThreadMaxAggregateInputType
}

export type ReviewThreadGroupByOutputType = {
  id: string
  scopeKey: string
  subjectKey: string
  contextKey: string | null
  context: runtime.JsonValue
  version: number
  createdAt: Date
  resolvedAt: Date | null
  resolvedBy: string | null
  _count: ReviewThreadCountAggregateOutputType | null
  _avg: ReviewThreadAvgAggregateOutputType | null
  _sum: ReviewThreadSumAggregateOutputType | null
  _min: ReviewThreadMinAggregateOutputType | null
  _max: ReviewThreadMaxAggregateOutputType | null
}

export type GetReviewThreadGroupByPayload<T extends ReviewThreadGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReviewThreadGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReviewThreadGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReviewThreadGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReviewThreadGroupByOutputType[P]>
      }
    >
  >



export type ReviewThreadWhereInput = {
  AND?: Prisma.ReviewThreadWhereInput | Prisma.ReviewThreadWhereInput[]
  OR?: Prisma.ReviewThreadWhereInput[]
  NOT?: Prisma.ReviewThreadWhereInput | Prisma.ReviewThreadWhereInput[]
  id?: Prisma.StringFilter<"ReviewThread"> | string
  scopeKey?: Prisma.StringFilter<"ReviewThread"> | string
  subjectKey?: Prisma.StringFilter<"ReviewThread"> | string
  contextKey?: Prisma.StringNullableFilter<"ReviewThread"> | string | null
  context?: Prisma.JsonFilter<"ReviewThread">
  version?: Prisma.IntFilter<"ReviewThread"> | number
  createdAt?: Prisma.DateTimeFilter<"ReviewThread"> | Date | string
  resolvedAt?: Prisma.DateTimeNullableFilter<"ReviewThread"> | Date | string | null
  resolvedBy?: Prisma.StringNullableFilter<"ReviewThread"> | string | null
  messages?: Prisma.ReviewMessageListRelationFilter
}

export type ReviewThreadOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  scopeKey?: Prisma.SortOrder
  subjectKey?: Prisma.SortOrder
  contextKey?: Prisma.SortOrderInput | Prisma.SortOrder
  context?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  resolvedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  messages?: Prisma.ReviewMessageOrderByRelationAggregateInput
}

export type ReviewThreadWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ReviewThreadWhereInput | Prisma.ReviewThreadWhereInput[]
  OR?: Prisma.ReviewThreadWhereInput[]
  NOT?: Prisma.ReviewThreadWhereInput | Prisma.ReviewThreadWhereInput[]
  scopeKey?: Prisma.StringFilter<"ReviewThread"> | string
  subjectKey?: Prisma.StringFilter<"ReviewThread"> | string
  contextKey?: Prisma.StringNullableFilter<"ReviewThread"> | string | null
  context?: Prisma.JsonFilter<"ReviewThread">
  version?: Prisma.IntFilter<"ReviewThread"> | number
  createdAt?: Prisma.DateTimeFilter<"ReviewThread"> | Date | string
  resolvedAt?: Prisma.DateTimeNullableFilter<"ReviewThread"> | Date | string | null
  resolvedBy?: Prisma.StringNullableFilter<"ReviewThread"> | string | null
  messages?: Prisma.ReviewMessageListRelationFilter
}, "id">

export type ReviewThreadOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  scopeKey?: Prisma.SortOrder
  subjectKey?: Prisma.SortOrder
  contextKey?: Prisma.SortOrderInput | Prisma.SortOrder
  context?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  resolvedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ReviewThreadCountOrderByAggregateInput
  _avg?: Prisma.ReviewThreadAvgOrderByAggregateInput
  _max?: Prisma.ReviewThreadMaxOrderByAggregateInput
  _min?: Prisma.ReviewThreadMinOrderByAggregateInput
  _sum?: Prisma.ReviewThreadSumOrderByAggregateInput
}

export type ReviewThreadScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReviewThreadScalarWhereWithAggregatesInput | Prisma.ReviewThreadScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReviewThreadScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReviewThreadScalarWhereWithAggregatesInput | Prisma.ReviewThreadScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ReviewThread"> | string
  scopeKey?: Prisma.StringWithAggregatesFilter<"ReviewThread"> | string
  subjectKey?: Prisma.StringWithAggregatesFilter<"ReviewThread"> | string
  contextKey?: Prisma.StringNullableWithAggregatesFilter<"ReviewThread"> | string | null
  context?: Prisma.JsonWithAggregatesFilter<"ReviewThread">
  version?: Prisma.IntWithAggregatesFilter<"ReviewThread"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ReviewThread"> | Date | string
  resolvedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ReviewThread"> | Date | string | null
  resolvedBy?: Prisma.StringNullableWithAggregatesFilter<"ReviewThread"> | string | null
}

export type ReviewThreadCreateInput = {
  id: string
  scopeKey: string
  subjectKey: string
  contextKey?: string | null
  context: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  resolvedAt?: Date | string | null
  resolvedBy?: string | null
  messages?: Prisma.ReviewMessageCreateNestedManyWithoutThreadInput
}

export type ReviewThreadUncheckedCreateInput = {
  id: string
  scopeKey: string
  subjectKey: string
  contextKey?: string | null
  context: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  resolvedAt?: Date | string | null
  resolvedBy?: string | null
  messages?: Prisma.ReviewMessageUncheckedCreateNestedManyWithoutThreadInput
}

export type ReviewThreadUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scopeKey?: Prisma.StringFieldUpdateOperationsInput | string
  subjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  contextKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messages?: Prisma.ReviewMessageUpdateManyWithoutThreadNestedInput
}

export type ReviewThreadUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scopeKey?: Prisma.StringFieldUpdateOperationsInput | string
  subjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  contextKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messages?: Prisma.ReviewMessageUncheckedUpdateManyWithoutThreadNestedInput
}

export type ReviewThreadCreateManyInput = {
  id: string
  scopeKey: string
  subjectKey: string
  contextKey?: string | null
  context: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  resolvedAt?: Date | string | null
  resolvedBy?: string | null
}

export type ReviewThreadUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scopeKey?: Prisma.StringFieldUpdateOperationsInput | string
  subjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  contextKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ReviewThreadUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scopeKey?: Prisma.StringFieldUpdateOperationsInput | string
  subjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  contextKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ReviewThreadCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  scopeKey?: Prisma.SortOrder
  subjectKey?: Prisma.SortOrder
  contextKey?: Prisma.SortOrder
  context?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  resolvedBy?: Prisma.SortOrder
}

export type ReviewThreadAvgOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type ReviewThreadMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  scopeKey?: Prisma.SortOrder
  subjectKey?: Prisma.SortOrder
  contextKey?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  resolvedBy?: Prisma.SortOrder
}

export type ReviewThreadMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  scopeKey?: Prisma.SortOrder
  subjectKey?: Prisma.SortOrder
  contextKey?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  resolvedBy?: Prisma.SortOrder
}

export type ReviewThreadSumOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type ReviewThreadScalarRelationFilter = {
  is?: Prisma.ReviewThreadWhereInput
  isNot?: Prisma.ReviewThreadWhereInput
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ReviewThreadCreateNestedOneWithoutMessagesInput = {
  create?: Prisma.XOR<Prisma.ReviewThreadCreateWithoutMessagesInput, Prisma.ReviewThreadUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.ReviewThreadCreateOrConnectWithoutMessagesInput
  connect?: Prisma.ReviewThreadWhereUniqueInput
}

export type ReviewThreadUpdateOneRequiredWithoutMessagesNestedInput = {
  create?: Prisma.XOR<Prisma.ReviewThreadCreateWithoutMessagesInput, Prisma.ReviewThreadUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.ReviewThreadCreateOrConnectWithoutMessagesInput
  upsert?: Prisma.ReviewThreadUpsertWithoutMessagesInput
  connect?: Prisma.ReviewThreadWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ReviewThreadUpdateToOneWithWhereWithoutMessagesInput, Prisma.ReviewThreadUpdateWithoutMessagesInput>, Prisma.ReviewThreadUncheckedUpdateWithoutMessagesInput>
}

export type ReviewThreadCreateWithoutMessagesInput = {
  id: string
  scopeKey: string
  subjectKey: string
  contextKey?: string | null
  context: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  resolvedAt?: Date | string | null
  resolvedBy?: string | null
}

export type ReviewThreadUncheckedCreateWithoutMessagesInput = {
  id: string
  scopeKey: string
  subjectKey: string
  contextKey?: string | null
  context: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: number
  createdAt?: Date | string
  resolvedAt?: Date | string | null
  resolvedBy?: string | null
}

export type ReviewThreadCreateOrConnectWithoutMessagesInput = {
  where: Prisma.ReviewThreadWhereUniqueInput
  create: Prisma.XOR<Prisma.ReviewThreadCreateWithoutMessagesInput, Prisma.ReviewThreadUncheckedCreateWithoutMessagesInput>
}

export type ReviewThreadUpsertWithoutMessagesInput = {
  update: Prisma.XOR<Prisma.ReviewThreadUpdateWithoutMessagesInput, Prisma.ReviewThreadUncheckedUpdateWithoutMessagesInput>
  create: Prisma.XOR<Prisma.ReviewThreadCreateWithoutMessagesInput, Prisma.ReviewThreadUncheckedCreateWithoutMessagesInput>
  where?: Prisma.ReviewThreadWhereInput
}

export type ReviewThreadUpdateToOneWithWhereWithoutMessagesInput = {
  where?: Prisma.ReviewThreadWhereInput
  data: Prisma.XOR<Prisma.ReviewThreadUpdateWithoutMessagesInput, Prisma.ReviewThreadUncheckedUpdateWithoutMessagesInput>
}

export type ReviewThreadUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scopeKey?: Prisma.StringFieldUpdateOperationsInput | string
  subjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  contextKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ReviewThreadUncheckedUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scopeKey?: Prisma.StringFieldUpdateOperationsInput | string
  subjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  contextKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  context?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type ReviewThreadCountOutputType
 */

export type ReviewThreadCountOutputType = {
  messages: number
}

export type ReviewThreadCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  messages?: boolean | ReviewThreadCountOutputTypeCountMessagesArgs
}

/**
 * ReviewThreadCountOutputType without action
 */
export type ReviewThreadCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThreadCountOutputType
   */
  select?: Prisma.ReviewThreadCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ReviewThreadCountOutputType without action
 */
export type ReviewThreadCountOutputTypeCountMessagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewMessageWhereInput
}


export type ReviewThreadSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  scopeKey?: boolean
  subjectKey?: boolean
  contextKey?: boolean
  context?: boolean
  version?: boolean
  createdAt?: boolean
  resolvedAt?: boolean
  resolvedBy?: boolean
  messages?: boolean | Prisma.ReviewThread$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.ReviewThreadCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reviewThread"]>

export type ReviewThreadSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  scopeKey?: boolean
  subjectKey?: boolean
  contextKey?: boolean
  context?: boolean
  version?: boolean
  createdAt?: boolean
  resolvedAt?: boolean
  resolvedBy?: boolean
}, ExtArgs["result"]["reviewThread"]>

export type ReviewThreadSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  scopeKey?: boolean
  subjectKey?: boolean
  contextKey?: boolean
  context?: boolean
  version?: boolean
  createdAt?: boolean
  resolvedAt?: boolean
  resolvedBy?: boolean
}, ExtArgs["result"]["reviewThread"]>

export type ReviewThreadSelectScalar = {
  id?: boolean
  scopeKey?: boolean
  subjectKey?: boolean
  contextKey?: boolean
  context?: boolean
  version?: boolean
  createdAt?: boolean
  resolvedAt?: boolean
  resolvedBy?: boolean
}

export type ReviewThreadOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "scopeKey" | "subjectKey" | "contextKey" | "context" | "version" | "createdAt" | "resolvedAt" | "resolvedBy", ExtArgs["result"]["reviewThread"]>
export type ReviewThreadInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  messages?: boolean | Prisma.ReviewThread$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.ReviewThreadCountOutputTypeDefaultArgs<ExtArgs>
}
export type ReviewThreadIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ReviewThreadIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ReviewThreadPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReviewThread"
  objects: {
    messages: Prisma.$ReviewMessagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    scopeKey: string
    subjectKey: string
    contextKey: string | null
    context: runtime.JsonValue
    version: number
    createdAt: Date
    resolvedAt: Date | null
    resolvedBy: string | null
  }, ExtArgs["result"]["reviewThread"]>
  composites: {}
}

export type ReviewThreadGetPayload<S extends boolean | null | undefined | ReviewThreadDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload, S>

export type ReviewThreadCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReviewThreadFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReviewThreadCountAggregateInputType | true
  }

export interface ReviewThreadDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReviewThread'], meta: { name: 'ReviewThread' } }
  /**
   * Find zero or one ReviewThread that matches the filter.
   * @param {ReviewThreadFindUniqueArgs} args - Arguments to find a ReviewThread
   * @example
   * // Get one ReviewThread
   * const reviewThread = await prisma.reviewThread.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReviewThreadFindUniqueArgs>(args: Prisma.SelectSubset<T, ReviewThreadFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReviewThreadClient<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReviewThread that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReviewThreadFindUniqueOrThrowArgs} args - Arguments to find a ReviewThread
   * @example
   * // Get one ReviewThread
   * const reviewThread = await prisma.reviewThread.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReviewThreadFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReviewThreadFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReviewThreadClient<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReviewThread that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewThreadFindFirstArgs} args - Arguments to find a ReviewThread
   * @example
   * // Get one ReviewThread
   * const reviewThread = await prisma.reviewThread.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReviewThreadFindFirstArgs>(args?: Prisma.SelectSubset<T, ReviewThreadFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReviewThreadClient<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReviewThread that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewThreadFindFirstOrThrowArgs} args - Arguments to find a ReviewThread
   * @example
   * // Get one ReviewThread
   * const reviewThread = await prisma.reviewThread.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReviewThreadFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReviewThreadFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReviewThreadClient<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReviewThreads that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewThreadFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReviewThreads
   * const reviewThreads = await prisma.reviewThread.findMany()
   * 
   * // Get first 10 ReviewThreads
   * const reviewThreads = await prisma.reviewThread.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reviewThreadWithIdOnly = await prisma.reviewThread.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReviewThreadFindManyArgs>(args?: Prisma.SelectSubset<T, ReviewThreadFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReviewThread.
   * @param {ReviewThreadCreateArgs} args - Arguments to create a ReviewThread.
   * @example
   * // Create one ReviewThread
   * const ReviewThread = await prisma.reviewThread.create({
   *   data: {
   *     // ... data to create a ReviewThread
   *   }
   * })
   * 
   */
  create<T extends ReviewThreadCreateArgs>(args: Prisma.SelectSubset<T, ReviewThreadCreateArgs<ExtArgs>>): Prisma.Prisma__ReviewThreadClient<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReviewThreads.
   * @param {ReviewThreadCreateManyArgs} args - Arguments to create many ReviewThreads.
   * @example
   * // Create many ReviewThreads
   * const reviewThread = await prisma.reviewThread.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReviewThreadCreateManyArgs>(args?: Prisma.SelectSubset<T, ReviewThreadCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReviewThreads and returns the data saved in the database.
   * @param {ReviewThreadCreateManyAndReturnArgs} args - Arguments to create many ReviewThreads.
   * @example
   * // Create many ReviewThreads
   * const reviewThread = await prisma.reviewThread.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReviewThreads and only return the `id`
   * const reviewThreadWithIdOnly = await prisma.reviewThread.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReviewThreadCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReviewThreadCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReviewThread.
   * @param {ReviewThreadDeleteArgs} args - Arguments to delete one ReviewThread.
   * @example
   * // Delete one ReviewThread
   * const ReviewThread = await prisma.reviewThread.delete({
   *   where: {
   *     // ... filter to delete one ReviewThread
   *   }
   * })
   * 
   */
  delete<T extends ReviewThreadDeleteArgs>(args: Prisma.SelectSubset<T, ReviewThreadDeleteArgs<ExtArgs>>): Prisma.Prisma__ReviewThreadClient<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReviewThread.
   * @param {ReviewThreadUpdateArgs} args - Arguments to update one ReviewThread.
   * @example
   * // Update one ReviewThread
   * const reviewThread = await prisma.reviewThread.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReviewThreadUpdateArgs>(args: Prisma.SelectSubset<T, ReviewThreadUpdateArgs<ExtArgs>>): Prisma.Prisma__ReviewThreadClient<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReviewThreads.
   * @param {ReviewThreadDeleteManyArgs} args - Arguments to filter ReviewThreads to delete.
   * @example
   * // Delete a few ReviewThreads
   * const { count } = await prisma.reviewThread.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReviewThreadDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReviewThreadDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReviewThreads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewThreadUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReviewThreads
   * const reviewThread = await prisma.reviewThread.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReviewThreadUpdateManyArgs>(args: Prisma.SelectSubset<T, ReviewThreadUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReviewThreads and returns the data updated in the database.
   * @param {ReviewThreadUpdateManyAndReturnArgs} args - Arguments to update many ReviewThreads.
   * @example
   * // Update many ReviewThreads
   * const reviewThread = await prisma.reviewThread.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReviewThreads and only return the `id`
   * const reviewThreadWithIdOnly = await prisma.reviewThread.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReviewThreadUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReviewThreadUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReviewThread.
   * @param {ReviewThreadUpsertArgs} args - Arguments to update or create a ReviewThread.
   * @example
   * // Update or create a ReviewThread
   * const reviewThread = await prisma.reviewThread.upsert({
   *   create: {
   *     // ... data to create a ReviewThread
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReviewThread we want to update
   *   }
   * })
   */
  upsert<T extends ReviewThreadUpsertArgs>(args: Prisma.SelectSubset<T, ReviewThreadUpsertArgs<ExtArgs>>): Prisma.Prisma__ReviewThreadClient<runtime.Types.Result.GetResult<Prisma.$ReviewThreadPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReviewThreads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewThreadCountArgs} args - Arguments to filter ReviewThreads to count.
   * @example
   * // Count the number of ReviewThreads
   * const count = await prisma.reviewThread.count({
   *   where: {
   *     // ... the filter for the ReviewThreads we want to count
   *   }
   * })
  **/
  count<T extends ReviewThreadCountArgs>(
    args?: Prisma.Subset<T, ReviewThreadCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReviewThreadCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReviewThread.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewThreadAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReviewThreadAggregateArgs>(args: Prisma.Subset<T, ReviewThreadAggregateArgs>): Prisma.PrismaPromise<GetReviewThreadAggregateType<T>>

  /**
   * Group by ReviewThread.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReviewThreadGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReviewThreadGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReviewThreadGroupByArgs['orderBy'] }
      : { orderBy?: ReviewThreadGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReviewThreadGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReviewThreadGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReviewThread model
 */
readonly fields: ReviewThreadFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReviewThread.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReviewThreadClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  messages<T extends Prisma.ReviewThread$messagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ReviewThread$messagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReviewThread model
 */
export interface ReviewThreadFieldRefs {
  readonly id: Prisma.FieldRef<"ReviewThread", 'String'>
  readonly scopeKey: Prisma.FieldRef<"ReviewThread", 'String'>
  readonly subjectKey: Prisma.FieldRef<"ReviewThread", 'String'>
  readonly contextKey: Prisma.FieldRef<"ReviewThread", 'String'>
  readonly context: Prisma.FieldRef<"ReviewThread", 'Json'>
  readonly version: Prisma.FieldRef<"ReviewThread", 'Int'>
  readonly createdAt: Prisma.FieldRef<"ReviewThread", 'DateTime'>
  readonly resolvedAt: Prisma.FieldRef<"ReviewThread", 'DateTime'>
  readonly resolvedBy: Prisma.FieldRef<"ReviewThread", 'String'>
}
    

// Custom InputTypes
/**
 * ReviewThread findUnique
 */
export type ReviewThreadFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
  /**
   * Filter, which ReviewThread to fetch.
   */
  where: Prisma.ReviewThreadWhereUniqueInput
}

/**
 * ReviewThread findUniqueOrThrow
 */
export type ReviewThreadFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
  /**
   * Filter, which ReviewThread to fetch.
   */
  where: Prisma.ReviewThreadWhereUniqueInput
}

/**
 * ReviewThread findFirst
 */
export type ReviewThreadFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
  /**
   * Filter, which ReviewThread to fetch.
   */
  where?: Prisma.ReviewThreadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReviewThreads to fetch.
   */
  orderBy?: Prisma.ReviewThreadOrderByWithRelationInput | Prisma.ReviewThreadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReviewThreads.
   */
  cursor?: Prisma.ReviewThreadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReviewThreads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReviewThreads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReviewThreads.
   */
  distinct?: Prisma.ReviewThreadScalarFieldEnum | Prisma.ReviewThreadScalarFieldEnum[]
}

/**
 * ReviewThread findFirstOrThrow
 */
export type ReviewThreadFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
  /**
   * Filter, which ReviewThread to fetch.
   */
  where?: Prisma.ReviewThreadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReviewThreads to fetch.
   */
  orderBy?: Prisma.ReviewThreadOrderByWithRelationInput | Prisma.ReviewThreadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReviewThreads.
   */
  cursor?: Prisma.ReviewThreadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReviewThreads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReviewThreads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReviewThreads.
   */
  distinct?: Prisma.ReviewThreadScalarFieldEnum | Prisma.ReviewThreadScalarFieldEnum[]
}

/**
 * ReviewThread findMany
 */
export type ReviewThreadFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
  /**
   * Filter, which ReviewThreads to fetch.
   */
  where?: Prisma.ReviewThreadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReviewThreads to fetch.
   */
  orderBy?: Prisma.ReviewThreadOrderByWithRelationInput | Prisma.ReviewThreadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReviewThreads.
   */
  cursor?: Prisma.ReviewThreadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReviewThreads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReviewThreads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReviewThreads.
   */
  distinct?: Prisma.ReviewThreadScalarFieldEnum | Prisma.ReviewThreadScalarFieldEnum[]
}

/**
 * ReviewThread create
 */
export type ReviewThreadCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
  /**
   * The data needed to create a ReviewThread.
   */
  data: Prisma.XOR<Prisma.ReviewThreadCreateInput, Prisma.ReviewThreadUncheckedCreateInput>
}

/**
 * ReviewThread createMany
 */
export type ReviewThreadCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReviewThreads.
   */
  data: Prisma.ReviewThreadCreateManyInput | Prisma.ReviewThreadCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReviewThread createManyAndReturn
 */
export type ReviewThreadCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * The data used to create many ReviewThreads.
   */
  data: Prisma.ReviewThreadCreateManyInput | Prisma.ReviewThreadCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReviewThread update
 */
export type ReviewThreadUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
  /**
   * The data needed to update a ReviewThread.
   */
  data: Prisma.XOR<Prisma.ReviewThreadUpdateInput, Prisma.ReviewThreadUncheckedUpdateInput>
  /**
   * Choose, which ReviewThread to update.
   */
  where: Prisma.ReviewThreadWhereUniqueInput
}

/**
 * ReviewThread updateMany
 */
export type ReviewThreadUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReviewThreads.
   */
  data: Prisma.XOR<Prisma.ReviewThreadUpdateManyMutationInput, Prisma.ReviewThreadUncheckedUpdateManyInput>
  /**
   * Filter which ReviewThreads to update
   */
  where?: Prisma.ReviewThreadWhereInput
  /**
   * Limit how many ReviewThreads to update.
   */
  limit?: number
}

/**
 * ReviewThread updateManyAndReturn
 */
export type ReviewThreadUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * The data used to update ReviewThreads.
   */
  data: Prisma.XOR<Prisma.ReviewThreadUpdateManyMutationInput, Prisma.ReviewThreadUncheckedUpdateManyInput>
  /**
   * Filter which ReviewThreads to update
   */
  where?: Prisma.ReviewThreadWhereInput
  /**
   * Limit how many ReviewThreads to update.
   */
  limit?: number
}

/**
 * ReviewThread upsert
 */
export type ReviewThreadUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
  /**
   * The filter to search for the ReviewThread to update in case it exists.
   */
  where: Prisma.ReviewThreadWhereUniqueInput
  /**
   * In case the ReviewThread found by the `where` argument doesn't exist, create a new ReviewThread with this data.
   */
  create: Prisma.XOR<Prisma.ReviewThreadCreateInput, Prisma.ReviewThreadUncheckedCreateInput>
  /**
   * In case the ReviewThread was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReviewThreadUpdateInput, Prisma.ReviewThreadUncheckedUpdateInput>
}

/**
 * ReviewThread delete
 */
export type ReviewThreadDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
  /**
   * Filter which ReviewThread to delete.
   */
  where: Prisma.ReviewThreadWhereUniqueInput
}

/**
 * ReviewThread deleteMany
 */
export type ReviewThreadDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReviewThreads to delete
   */
  where?: Prisma.ReviewThreadWhereInput
  /**
   * Limit how many ReviewThreads to delete.
   */
  limit?: number
}

/**
 * ReviewThread.messages
 */
export type ReviewThread$messagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewMessage
   */
  select?: Prisma.ReviewMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewMessage
   */
  omit?: Prisma.ReviewMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewMessageInclude<ExtArgs> | null
  where?: Prisma.ReviewMessageWhereInput
  orderBy?: Prisma.ReviewMessageOrderByWithRelationInput | Prisma.ReviewMessageOrderByWithRelationInput[]
  cursor?: Prisma.ReviewMessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReviewMessageScalarFieldEnum | Prisma.ReviewMessageScalarFieldEnum[]
}

/**
 * ReviewThread without action
 */
export type ReviewThreadDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReviewThread
   */
  select?: Prisma.ReviewThreadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReviewThread
   */
  omit?: Prisma.ReviewThreadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewThreadInclude<ExtArgs> | null
}
