
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Row` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Row
 * 
 */
export type RowModel = runtime.Types.Result.DefaultSelection<Prisma.$RowPayload>

export type AggregateRow = {
  _count: RowCountAggregateOutputType | null
  _min: RowMinAggregateOutputType | null
  _max: RowMaxAggregateOutputType | null
}

export type RowMinAggregateOutputType = {
  versionId: string | null
  createdId: string | null
  id: string | null
  readonly: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  publishedAt: Date | null
  hash: string | null
  schemaHash: string | null
}

export type RowMaxAggregateOutputType = {
  versionId: string | null
  createdId: string | null
  id: string | null
  readonly: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  publishedAt: Date | null
  hash: string | null
  schemaHash: string | null
}

export type RowCountAggregateOutputType = {
  versionId: number
  createdId: number
  id: number
  readonly: number
  createdAt: number
  updatedAt: number
  publishedAt: number
  data: number
  meta: number
  hash: number
  schemaHash: number
  _all: number
}


export type RowMinAggregateInputType = {
  versionId?: true
  createdId?: true
  id?: true
  readonly?: true
  createdAt?: true
  updatedAt?: true
  publishedAt?: true
  hash?: true
  schemaHash?: true
}

export type RowMaxAggregateInputType = {
  versionId?: true
  createdId?: true
  id?: true
  readonly?: true
  createdAt?: true
  updatedAt?: true
  publishedAt?: true
  hash?: true
  schemaHash?: true
}

export type RowCountAggregateInputType = {
  versionId?: true
  createdId?: true
  id?: true
  readonly?: true
  createdAt?: true
  updatedAt?: true
  publishedAt?: true
  data?: true
  meta?: true
  hash?: true
  schemaHash?: true
  _all?: true
}

export type RowAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Row to aggregate.
   */
  where?: Prisma.RowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rows to fetch.
   */
  orderBy?: Prisma.RowOrderByWithRelationInput | Prisma.RowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Rows
  **/
  _count?: true | RowCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RowMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RowMaxAggregateInputType
}

export type GetRowAggregateType<T extends RowAggregateArgs> = {
      [P in keyof T & keyof AggregateRow]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRow[P]>
    : Prisma.GetScalarType<T[P], AggregateRow[P]>
}




export type RowGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RowWhereInput
  orderBy?: Prisma.RowOrderByWithAggregationInput | Prisma.RowOrderByWithAggregationInput[]
  by: Prisma.RowScalarFieldEnum[] | Prisma.RowScalarFieldEnum
  having?: Prisma.RowScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RowCountAggregateInputType | true
  _min?: RowMinAggregateInputType
  _max?: RowMaxAggregateInputType
}

export type RowGroupByOutputType = {
  versionId: string
  createdId: string
  id: string
  readonly: boolean
  createdAt: Date
  updatedAt: Date
  publishedAt: Date
  data: runtime.JsonValue
  meta: runtime.JsonValue
  hash: string
  schemaHash: string
  _count: RowCountAggregateOutputType | null
  _min: RowMinAggregateOutputType | null
  _max: RowMaxAggregateOutputType | null
}

export type GetRowGroupByPayload<T extends RowGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RowGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RowGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RowGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RowGroupByOutputType[P]>
      }
    >
  >



export type RowWhereInput = {
  AND?: Prisma.RowWhereInput | Prisma.RowWhereInput[]
  OR?: Prisma.RowWhereInput[]
  NOT?: Prisma.RowWhereInput | Prisma.RowWhereInput[]
  versionId?: Prisma.StringFilter<"Row"> | string
  createdId?: Prisma.StringFilter<"Row"> | string
  id?: Prisma.StringFilter<"Row"> | string
  readonly?: Prisma.BoolFilter<"Row"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Row"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Row"> | Date | string
  publishedAt?: Prisma.DateTimeFilter<"Row"> | Date | string
  data?: Prisma.JsonFilter<"Row">
  meta?: Prisma.JsonFilter<"Row">
  hash?: Prisma.StringFilter<"Row"> | string
  schemaHash?: Prisma.StringFilter<"Row"> | string
  tables?: Prisma.TableListRelationFilter
  fileBlobs?: Prisma.FileBlobListRelationFilter
}

export type RowOrderByWithRelationInput = {
  versionId?: Prisma.SortOrder
  createdId?: Prisma.SortOrder
  id?: Prisma.SortOrder
  readonly?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  data?: Prisma.SortOrder
  meta?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  schemaHash?: Prisma.SortOrder
  tables?: Prisma.TableOrderByRelationAggregateInput
  fileBlobs?: Prisma.FileBlobOrderByRelationAggregateInput
}

export type RowWhereUniqueInput = Prisma.AtLeast<{
  versionId?: string
  AND?: Prisma.RowWhereInput | Prisma.RowWhereInput[]
  OR?: Prisma.RowWhereInput[]
  NOT?: Prisma.RowWhereInput | Prisma.RowWhereInput[]
  createdId?: Prisma.StringFilter<"Row"> | string
  id?: Prisma.StringFilter<"Row"> | string
  readonly?: Prisma.BoolFilter<"Row"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Row"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Row"> | Date | string
  publishedAt?: Prisma.DateTimeFilter<"Row"> | Date | string
  data?: Prisma.JsonFilter<"Row">
  meta?: Prisma.JsonFilter<"Row">
  hash?: Prisma.StringFilter<"Row"> | string
  schemaHash?: Prisma.StringFilter<"Row"> | string
  tables?: Prisma.TableListRelationFilter
  fileBlobs?: Prisma.FileBlobListRelationFilter
}, "versionId">

export type RowOrderByWithAggregationInput = {
  versionId?: Prisma.SortOrder
  createdId?: Prisma.SortOrder
  id?: Prisma.SortOrder
  readonly?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  data?: Prisma.SortOrder
  meta?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  schemaHash?: Prisma.SortOrder
  _count?: Prisma.RowCountOrderByAggregateInput
  _max?: Prisma.RowMaxOrderByAggregateInput
  _min?: Prisma.RowMinOrderByAggregateInput
}

export type RowScalarWhereWithAggregatesInput = {
  AND?: Prisma.RowScalarWhereWithAggregatesInput | Prisma.RowScalarWhereWithAggregatesInput[]
  OR?: Prisma.RowScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RowScalarWhereWithAggregatesInput | Prisma.RowScalarWhereWithAggregatesInput[]
  versionId?: Prisma.StringWithAggregatesFilter<"Row"> | string
  createdId?: Prisma.StringWithAggregatesFilter<"Row"> | string
  id?: Prisma.StringWithAggregatesFilter<"Row"> | string
  readonly?: Prisma.BoolWithAggregatesFilter<"Row"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Row"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Row"> | Date | string
  publishedAt?: Prisma.DateTimeWithAggregatesFilter<"Row"> | Date | string
  data?: Prisma.JsonWithAggregatesFilter<"Row">
  meta?: Prisma.JsonWithAggregatesFilter<"Row">
  hash?: Prisma.StringWithAggregatesFilter<"Row"> | string
  schemaHash?: Prisma.StringWithAggregatesFilter<"Row"> | string
}

export type RowCreateInput = {
  versionId: string
  createdId: string
  id: string
  readonly?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash: string
  schemaHash: string
  tables?: Prisma.TableCreateNestedManyWithoutRowsInput
  fileBlobs?: Prisma.FileBlobCreateNestedManyWithoutRowsInput
}

export type RowUncheckedCreateInput = {
  versionId: string
  createdId: string
  id: string
  readonly?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash: string
  schemaHash: string
  tables?: Prisma.TableUncheckedCreateNestedManyWithoutRowsInput
  fileBlobs?: Prisma.FileBlobUncheckedCreateNestedManyWithoutRowsInput
}

export type RowUpdateInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
  tables?: Prisma.TableUpdateManyWithoutRowsNestedInput
  fileBlobs?: Prisma.FileBlobUpdateManyWithoutRowsNestedInput
}

export type RowUncheckedUpdateInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
  tables?: Prisma.TableUncheckedUpdateManyWithoutRowsNestedInput
  fileBlobs?: Prisma.FileBlobUncheckedUpdateManyWithoutRowsNestedInput
}

export type RowCreateManyInput = {
  versionId: string
  createdId: string
  id: string
  readonly?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash: string
  schemaHash: string
}

export type RowUpdateManyMutationInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RowUncheckedUpdateManyInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RowListRelationFilter = {
  every?: Prisma.RowWhereInput
  some?: Prisma.RowWhereInput
  none?: Prisma.RowWhereInput
}

export type RowOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RowCountOrderByAggregateInput = {
  versionId?: Prisma.SortOrder
  createdId?: Prisma.SortOrder
  id?: Prisma.SortOrder
  readonly?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  data?: Prisma.SortOrder
  meta?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  schemaHash?: Prisma.SortOrder
}

export type RowMaxOrderByAggregateInput = {
  versionId?: Prisma.SortOrder
  createdId?: Prisma.SortOrder
  id?: Prisma.SortOrder
  readonly?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  schemaHash?: Prisma.SortOrder
}

export type RowMinOrderByAggregateInput = {
  versionId?: Prisma.SortOrder
  createdId?: Prisma.SortOrder
  id?: Prisma.SortOrder
  readonly?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  schemaHash?: Prisma.SortOrder
}

export type RowCreateNestedManyWithoutTablesInput = {
  create?: Prisma.XOR<Prisma.RowCreateWithoutTablesInput, Prisma.RowUncheckedCreateWithoutTablesInput> | Prisma.RowCreateWithoutTablesInput[] | Prisma.RowUncheckedCreateWithoutTablesInput[]
  connectOrCreate?: Prisma.RowCreateOrConnectWithoutTablesInput | Prisma.RowCreateOrConnectWithoutTablesInput[]
  connect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
}

export type RowUncheckedCreateNestedManyWithoutTablesInput = {
  create?: Prisma.XOR<Prisma.RowCreateWithoutTablesInput, Prisma.RowUncheckedCreateWithoutTablesInput> | Prisma.RowCreateWithoutTablesInput[] | Prisma.RowUncheckedCreateWithoutTablesInput[]
  connectOrCreate?: Prisma.RowCreateOrConnectWithoutTablesInput | Prisma.RowCreateOrConnectWithoutTablesInput[]
  connect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
}

export type RowUpdateManyWithoutTablesNestedInput = {
  create?: Prisma.XOR<Prisma.RowCreateWithoutTablesInput, Prisma.RowUncheckedCreateWithoutTablesInput> | Prisma.RowCreateWithoutTablesInput[] | Prisma.RowUncheckedCreateWithoutTablesInput[]
  connectOrCreate?: Prisma.RowCreateOrConnectWithoutTablesInput | Prisma.RowCreateOrConnectWithoutTablesInput[]
  upsert?: Prisma.RowUpsertWithWhereUniqueWithoutTablesInput | Prisma.RowUpsertWithWhereUniqueWithoutTablesInput[]
  set?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  disconnect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  delete?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  connect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  update?: Prisma.RowUpdateWithWhereUniqueWithoutTablesInput | Prisma.RowUpdateWithWhereUniqueWithoutTablesInput[]
  updateMany?: Prisma.RowUpdateManyWithWhereWithoutTablesInput | Prisma.RowUpdateManyWithWhereWithoutTablesInput[]
  deleteMany?: Prisma.RowScalarWhereInput | Prisma.RowScalarWhereInput[]
}

export type RowUncheckedUpdateManyWithoutTablesNestedInput = {
  create?: Prisma.XOR<Prisma.RowCreateWithoutTablesInput, Prisma.RowUncheckedCreateWithoutTablesInput> | Prisma.RowCreateWithoutTablesInput[] | Prisma.RowUncheckedCreateWithoutTablesInput[]
  connectOrCreate?: Prisma.RowCreateOrConnectWithoutTablesInput | Prisma.RowCreateOrConnectWithoutTablesInput[]
  upsert?: Prisma.RowUpsertWithWhereUniqueWithoutTablesInput | Prisma.RowUpsertWithWhereUniqueWithoutTablesInput[]
  set?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  disconnect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  delete?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  connect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  update?: Prisma.RowUpdateWithWhereUniqueWithoutTablesInput | Prisma.RowUpdateWithWhereUniqueWithoutTablesInput[]
  updateMany?: Prisma.RowUpdateManyWithWhereWithoutTablesInput | Prisma.RowUpdateManyWithWhereWithoutTablesInput[]
  deleteMany?: Prisma.RowScalarWhereInput | Prisma.RowScalarWhereInput[]
}

export type RowCreateNestedManyWithoutFileBlobsInput = {
  create?: Prisma.XOR<Prisma.RowCreateWithoutFileBlobsInput, Prisma.RowUncheckedCreateWithoutFileBlobsInput> | Prisma.RowCreateWithoutFileBlobsInput[] | Prisma.RowUncheckedCreateWithoutFileBlobsInput[]
  connectOrCreate?: Prisma.RowCreateOrConnectWithoutFileBlobsInput | Prisma.RowCreateOrConnectWithoutFileBlobsInput[]
  connect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
}

export type RowUncheckedCreateNestedManyWithoutFileBlobsInput = {
  create?: Prisma.XOR<Prisma.RowCreateWithoutFileBlobsInput, Prisma.RowUncheckedCreateWithoutFileBlobsInput> | Prisma.RowCreateWithoutFileBlobsInput[] | Prisma.RowUncheckedCreateWithoutFileBlobsInput[]
  connectOrCreate?: Prisma.RowCreateOrConnectWithoutFileBlobsInput | Prisma.RowCreateOrConnectWithoutFileBlobsInput[]
  connect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
}

export type RowUpdateManyWithoutFileBlobsNestedInput = {
  create?: Prisma.XOR<Prisma.RowCreateWithoutFileBlobsInput, Prisma.RowUncheckedCreateWithoutFileBlobsInput> | Prisma.RowCreateWithoutFileBlobsInput[] | Prisma.RowUncheckedCreateWithoutFileBlobsInput[]
  connectOrCreate?: Prisma.RowCreateOrConnectWithoutFileBlobsInput | Prisma.RowCreateOrConnectWithoutFileBlobsInput[]
  upsert?: Prisma.RowUpsertWithWhereUniqueWithoutFileBlobsInput | Prisma.RowUpsertWithWhereUniqueWithoutFileBlobsInput[]
  set?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  disconnect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  delete?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  connect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  update?: Prisma.RowUpdateWithWhereUniqueWithoutFileBlobsInput | Prisma.RowUpdateWithWhereUniqueWithoutFileBlobsInput[]
  updateMany?: Prisma.RowUpdateManyWithWhereWithoutFileBlobsInput | Prisma.RowUpdateManyWithWhereWithoutFileBlobsInput[]
  deleteMany?: Prisma.RowScalarWhereInput | Prisma.RowScalarWhereInput[]
}

export type RowUncheckedUpdateManyWithoutFileBlobsNestedInput = {
  create?: Prisma.XOR<Prisma.RowCreateWithoutFileBlobsInput, Prisma.RowUncheckedCreateWithoutFileBlobsInput> | Prisma.RowCreateWithoutFileBlobsInput[] | Prisma.RowUncheckedCreateWithoutFileBlobsInput[]
  connectOrCreate?: Prisma.RowCreateOrConnectWithoutFileBlobsInput | Prisma.RowCreateOrConnectWithoutFileBlobsInput[]
  upsert?: Prisma.RowUpsertWithWhereUniqueWithoutFileBlobsInput | Prisma.RowUpsertWithWhereUniqueWithoutFileBlobsInput[]
  set?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  disconnect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  delete?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  connect?: Prisma.RowWhereUniqueInput | Prisma.RowWhereUniqueInput[]
  update?: Prisma.RowUpdateWithWhereUniqueWithoutFileBlobsInput | Prisma.RowUpdateWithWhereUniqueWithoutFileBlobsInput[]
  updateMany?: Prisma.RowUpdateManyWithWhereWithoutFileBlobsInput | Prisma.RowUpdateManyWithWhereWithoutFileBlobsInput[]
  deleteMany?: Prisma.RowScalarWhereInput | Prisma.RowScalarWhereInput[]
}

export type RowCreateWithoutTablesInput = {
  versionId: string
  createdId: string
  id: string
  readonly?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash: string
  schemaHash: string
  fileBlobs?: Prisma.FileBlobCreateNestedManyWithoutRowsInput
}

export type RowUncheckedCreateWithoutTablesInput = {
  versionId: string
  createdId: string
  id: string
  readonly?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash: string
  schemaHash: string
  fileBlobs?: Prisma.FileBlobUncheckedCreateNestedManyWithoutRowsInput
}

export type RowCreateOrConnectWithoutTablesInput = {
  where: Prisma.RowWhereUniqueInput
  create: Prisma.XOR<Prisma.RowCreateWithoutTablesInput, Prisma.RowUncheckedCreateWithoutTablesInput>
}

export type RowUpsertWithWhereUniqueWithoutTablesInput = {
  where: Prisma.RowWhereUniqueInput
  update: Prisma.XOR<Prisma.RowUpdateWithoutTablesInput, Prisma.RowUncheckedUpdateWithoutTablesInput>
  create: Prisma.XOR<Prisma.RowCreateWithoutTablesInput, Prisma.RowUncheckedCreateWithoutTablesInput>
}

export type RowUpdateWithWhereUniqueWithoutTablesInput = {
  where: Prisma.RowWhereUniqueInput
  data: Prisma.XOR<Prisma.RowUpdateWithoutTablesInput, Prisma.RowUncheckedUpdateWithoutTablesInput>
}

export type RowUpdateManyWithWhereWithoutTablesInput = {
  where: Prisma.RowScalarWhereInput
  data: Prisma.XOR<Prisma.RowUpdateManyMutationInput, Prisma.RowUncheckedUpdateManyWithoutTablesInput>
}

export type RowScalarWhereInput = {
  AND?: Prisma.RowScalarWhereInput | Prisma.RowScalarWhereInput[]
  OR?: Prisma.RowScalarWhereInput[]
  NOT?: Prisma.RowScalarWhereInput | Prisma.RowScalarWhereInput[]
  versionId?: Prisma.StringFilter<"Row"> | string
  createdId?: Prisma.StringFilter<"Row"> | string
  id?: Prisma.StringFilter<"Row"> | string
  readonly?: Prisma.BoolFilter<"Row"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Row"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Row"> | Date | string
  publishedAt?: Prisma.DateTimeFilter<"Row"> | Date | string
  data?: Prisma.JsonFilter<"Row">
  meta?: Prisma.JsonFilter<"Row">
  hash?: Prisma.StringFilter<"Row"> | string
  schemaHash?: Prisma.StringFilter<"Row"> | string
}

export type RowCreateWithoutFileBlobsInput = {
  versionId: string
  createdId: string
  id: string
  readonly?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash: string
  schemaHash: string
  tables?: Prisma.TableCreateNestedManyWithoutRowsInput
}

export type RowUncheckedCreateWithoutFileBlobsInput = {
  versionId: string
  createdId: string
  id: string
  readonly?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  publishedAt?: Date | string
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash: string
  schemaHash: string
  tables?: Prisma.TableUncheckedCreateNestedManyWithoutRowsInput
}

export type RowCreateOrConnectWithoutFileBlobsInput = {
  where: Prisma.RowWhereUniqueInput
  create: Prisma.XOR<Prisma.RowCreateWithoutFileBlobsInput, Prisma.RowUncheckedCreateWithoutFileBlobsInput>
}

export type RowUpsertWithWhereUniqueWithoutFileBlobsInput = {
  where: Prisma.RowWhereUniqueInput
  update: Prisma.XOR<Prisma.RowUpdateWithoutFileBlobsInput, Prisma.RowUncheckedUpdateWithoutFileBlobsInput>
  create: Prisma.XOR<Prisma.RowCreateWithoutFileBlobsInput, Prisma.RowUncheckedCreateWithoutFileBlobsInput>
}

export type RowUpdateWithWhereUniqueWithoutFileBlobsInput = {
  where: Prisma.RowWhereUniqueInput
  data: Prisma.XOR<Prisma.RowUpdateWithoutFileBlobsInput, Prisma.RowUncheckedUpdateWithoutFileBlobsInput>
}

export type RowUpdateManyWithWhereWithoutFileBlobsInput = {
  where: Prisma.RowScalarWhereInput
  data: Prisma.XOR<Prisma.RowUpdateManyMutationInput, Prisma.RowUncheckedUpdateManyWithoutFileBlobsInput>
}

export type RowUpdateWithoutTablesInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
  fileBlobs?: Prisma.FileBlobUpdateManyWithoutRowsNestedInput
}

export type RowUncheckedUpdateWithoutTablesInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
  fileBlobs?: Prisma.FileBlobUncheckedUpdateManyWithoutRowsNestedInput
}

export type RowUncheckedUpdateManyWithoutTablesInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RowUpdateWithoutFileBlobsInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
  tables?: Prisma.TableUpdateManyWithoutRowsNestedInput
}

export type RowUncheckedUpdateWithoutFileBlobsInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
  tables?: Prisma.TableUncheckedUpdateManyWithoutRowsNestedInput
}

export type RowUncheckedUpdateManyWithoutFileBlobsInput = {
  versionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdId?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  readonly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  meta?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  schemaHash?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type RowCountOutputType
 */

export type RowCountOutputType = {
  tables: number
  fileBlobs: number
}

export type RowCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tables?: boolean | RowCountOutputTypeCountTablesArgs
  fileBlobs?: boolean | RowCountOutputTypeCountFileBlobsArgs
}

/**
 * RowCountOutputType without action
 */
export type RowCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RowCountOutputType
   */
  select?: Prisma.RowCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RowCountOutputType without action
 */
export type RowCountOutputTypeCountTablesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TableWhereInput
}

/**
 * RowCountOutputType without action
 */
export type RowCountOutputTypeCountFileBlobsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileBlobWhereInput
}


export type RowSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  versionId?: boolean
  createdId?: boolean
  id?: boolean
  readonly?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publishedAt?: boolean
  data?: boolean
  meta?: boolean
  hash?: boolean
  schemaHash?: boolean
  tables?: boolean | Prisma.Row$tablesArgs<ExtArgs>
  fileBlobs?: boolean | Prisma.Row$fileBlobsArgs<ExtArgs>
  _count?: boolean | Prisma.RowCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["row"]>

export type RowSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  versionId?: boolean
  createdId?: boolean
  id?: boolean
  readonly?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publishedAt?: boolean
  data?: boolean
  meta?: boolean
  hash?: boolean
  schemaHash?: boolean
}, ExtArgs["result"]["row"]>

export type RowSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  versionId?: boolean
  createdId?: boolean
  id?: boolean
  readonly?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publishedAt?: boolean
  data?: boolean
  meta?: boolean
  hash?: boolean
  schemaHash?: boolean
}, ExtArgs["result"]["row"]>

export type RowSelectScalar = {
  versionId?: boolean
  createdId?: boolean
  id?: boolean
  readonly?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publishedAt?: boolean
  data?: boolean
  meta?: boolean
  hash?: boolean
  schemaHash?: boolean
}

export type RowOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"versionId" | "createdId" | "id" | "readonly" | "createdAt" | "updatedAt" | "publishedAt" | "data" | "meta" | "hash" | "schemaHash", ExtArgs["result"]["row"]>
export type RowInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tables?: boolean | Prisma.Row$tablesArgs<ExtArgs>
  fileBlobs?: boolean | Prisma.Row$fileBlobsArgs<ExtArgs>
  _count?: boolean | Prisma.RowCountOutputTypeDefaultArgs<ExtArgs>
}
export type RowIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type RowIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $RowPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Row"
  objects: {
    tables: Prisma.$TablePayload<ExtArgs>[]
    fileBlobs: Prisma.$FileBlobPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    versionId: string
    createdId: string
    id: string
    readonly: boolean
    createdAt: Date
    updatedAt: Date
    publishedAt: Date
    data: runtime.JsonValue
    meta: runtime.JsonValue
    hash: string
    schemaHash: string
  }, ExtArgs["result"]["row"]>
  composites: {}
}

export type RowGetPayload<S extends boolean | null | undefined | RowDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RowPayload, S>

export type RowCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RowFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RowCountAggregateInputType | true
  }

export interface RowDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Row'], meta: { name: 'Row' } }
  /**
   * Find zero or one Row that matches the filter.
   * @param {RowFindUniqueArgs} args - Arguments to find a Row
   * @example
   * // Get one Row
   * const row = await prisma.row.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RowFindUniqueArgs>(args: Prisma.SelectSubset<T, RowFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RowClient<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Row that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RowFindUniqueOrThrowArgs} args - Arguments to find a Row
   * @example
   * // Get one Row
   * const row = await prisma.row.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RowFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RowFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RowClient<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Row that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RowFindFirstArgs} args - Arguments to find a Row
   * @example
   * // Get one Row
   * const row = await prisma.row.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RowFindFirstArgs>(args?: Prisma.SelectSubset<T, RowFindFirstArgs<ExtArgs>>): Prisma.Prisma__RowClient<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Row that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RowFindFirstOrThrowArgs} args - Arguments to find a Row
   * @example
   * // Get one Row
   * const row = await prisma.row.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RowFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RowFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RowClient<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Rows that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RowFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Rows
   * const rows = await prisma.row.findMany()
   * 
   * // Get first 10 Rows
   * const rows = await prisma.row.findMany({ take: 10 })
   * 
   * // Only select the `versionId`
   * const rowWithVersionIdOnly = await prisma.row.findMany({ select: { versionId: true } })
   * 
   */
  findMany<T extends RowFindManyArgs>(args?: Prisma.SelectSubset<T, RowFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Row.
   * @param {RowCreateArgs} args - Arguments to create a Row.
   * @example
   * // Create one Row
   * const Row = await prisma.row.create({
   *   data: {
   *     // ... data to create a Row
   *   }
   * })
   * 
   */
  create<T extends RowCreateArgs>(args: Prisma.SelectSubset<T, RowCreateArgs<ExtArgs>>): Prisma.Prisma__RowClient<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Rows.
   * @param {RowCreateManyArgs} args - Arguments to create many Rows.
   * @example
   * // Create many Rows
   * const row = await prisma.row.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RowCreateManyArgs>(args?: Prisma.SelectSubset<T, RowCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Rows and returns the data saved in the database.
   * @param {RowCreateManyAndReturnArgs} args - Arguments to create many Rows.
   * @example
   * // Create many Rows
   * const row = await prisma.row.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Rows and only return the `versionId`
   * const rowWithVersionIdOnly = await prisma.row.createManyAndReturn({
   *   select: { versionId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RowCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RowCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Row.
   * @param {RowDeleteArgs} args - Arguments to delete one Row.
   * @example
   * // Delete one Row
   * const Row = await prisma.row.delete({
   *   where: {
   *     // ... filter to delete one Row
   *   }
   * })
   * 
   */
  delete<T extends RowDeleteArgs>(args: Prisma.SelectSubset<T, RowDeleteArgs<ExtArgs>>): Prisma.Prisma__RowClient<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Row.
   * @param {RowUpdateArgs} args - Arguments to update one Row.
   * @example
   * // Update one Row
   * const row = await prisma.row.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RowUpdateArgs>(args: Prisma.SelectSubset<T, RowUpdateArgs<ExtArgs>>): Prisma.Prisma__RowClient<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Rows.
   * @param {RowDeleteManyArgs} args - Arguments to filter Rows to delete.
   * @example
   * // Delete a few Rows
   * const { count } = await prisma.row.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RowDeleteManyArgs>(args?: Prisma.SelectSubset<T, RowDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Rows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RowUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Rows
   * const row = await prisma.row.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RowUpdateManyArgs>(args: Prisma.SelectSubset<T, RowUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Rows and returns the data updated in the database.
   * @param {RowUpdateManyAndReturnArgs} args - Arguments to update many Rows.
   * @example
   * // Update many Rows
   * const row = await prisma.row.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Rows and only return the `versionId`
   * const rowWithVersionIdOnly = await prisma.row.updateManyAndReturn({
   *   select: { versionId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RowUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RowUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Row.
   * @param {RowUpsertArgs} args - Arguments to update or create a Row.
   * @example
   * // Update or create a Row
   * const row = await prisma.row.upsert({
   *   create: {
   *     // ... data to create a Row
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Row we want to update
   *   }
   * })
   */
  upsert<T extends RowUpsertArgs>(args: Prisma.SelectSubset<T, RowUpsertArgs<ExtArgs>>): Prisma.Prisma__RowClient<runtime.Types.Result.GetResult<Prisma.$RowPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Rows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RowCountArgs} args - Arguments to filter Rows to count.
   * @example
   * // Count the number of Rows
   * const count = await prisma.row.count({
   *   where: {
   *     // ... the filter for the Rows we want to count
   *   }
   * })
  **/
  count<T extends RowCountArgs>(
    args?: Prisma.Subset<T, RowCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RowCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Row.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RowAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RowAggregateArgs>(args: Prisma.Subset<T, RowAggregateArgs>): Prisma.PrismaPromise<GetRowAggregateType<T>>

  /**
   * Group by Row.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RowGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RowGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RowGroupByArgs['orderBy'] }
      : { orderBy?: RowGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RowGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRowGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Row model
 */
readonly fields: RowFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Row.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RowClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tables<T extends Prisma.Row$tablesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Row$tablesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TablePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  fileBlobs<T extends Prisma.Row$fileBlobsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Row$fileBlobsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileBlobPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Row model
 */
export interface RowFieldRefs {
  readonly versionId: Prisma.FieldRef<"Row", 'String'>
  readonly createdId: Prisma.FieldRef<"Row", 'String'>
  readonly id: Prisma.FieldRef<"Row", 'String'>
  readonly readonly: Prisma.FieldRef<"Row", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Row", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Row", 'DateTime'>
  readonly publishedAt: Prisma.FieldRef<"Row", 'DateTime'>
  readonly data: Prisma.FieldRef<"Row", 'Json'>
  readonly meta: Prisma.FieldRef<"Row", 'Json'>
  readonly hash: Prisma.FieldRef<"Row", 'String'>
  readonly schemaHash: Prisma.FieldRef<"Row", 'String'>
}
    

// Custom InputTypes
/**
 * Row findUnique
 */
export type RowFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
  /**
   * Filter, which Row to fetch.
   */
  where: Prisma.RowWhereUniqueInput
}

/**
 * Row findUniqueOrThrow
 */
export type RowFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
  /**
   * Filter, which Row to fetch.
   */
  where: Prisma.RowWhereUniqueInput
}

/**
 * Row findFirst
 */
export type RowFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
  /**
   * Filter, which Row to fetch.
   */
  where?: Prisma.RowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rows to fetch.
   */
  orderBy?: Prisma.RowOrderByWithRelationInput | Prisma.RowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Rows.
   */
  cursor?: Prisma.RowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Rows.
   */
  distinct?: Prisma.RowScalarFieldEnum | Prisma.RowScalarFieldEnum[]
}

/**
 * Row findFirstOrThrow
 */
export type RowFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
  /**
   * Filter, which Row to fetch.
   */
  where?: Prisma.RowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rows to fetch.
   */
  orderBy?: Prisma.RowOrderByWithRelationInput | Prisma.RowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Rows.
   */
  cursor?: Prisma.RowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Rows.
   */
  distinct?: Prisma.RowScalarFieldEnum | Prisma.RowScalarFieldEnum[]
}

/**
 * Row findMany
 */
export type RowFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
  /**
   * Filter, which Rows to fetch.
   */
  where?: Prisma.RowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rows to fetch.
   */
  orderBy?: Prisma.RowOrderByWithRelationInput | Prisma.RowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Rows.
   */
  cursor?: Prisma.RowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Rows.
   */
  distinct?: Prisma.RowScalarFieldEnum | Prisma.RowScalarFieldEnum[]
}

/**
 * Row create
 */
export type RowCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
  /**
   * The data needed to create a Row.
   */
  data: Prisma.XOR<Prisma.RowCreateInput, Prisma.RowUncheckedCreateInput>
}

/**
 * Row createMany
 */
export type RowCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Rows.
   */
  data: Prisma.RowCreateManyInput | Prisma.RowCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Row createManyAndReturn
 */
export type RowCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * The data used to create many Rows.
   */
  data: Prisma.RowCreateManyInput | Prisma.RowCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Row update
 */
export type RowUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
  /**
   * The data needed to update a Row.
   */
  data: Prisma.XOR<Prisma.RowUpdateInput, Prisma.RowUncheckedUpdateInput>
  /**
   * Choose, which Row to update.
   */
  where: Prisma.RowWhereUniqueInput
}

/**
 * Row updateMany
 */
export type RowUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Rows.
   */
  data: Prisma.XOR<Prisma.RowUpdateManyMutationInput, Prisma.RowUncheckedUpdateManyInput>
  /**
   * Filter which Rows to update
   */
  where?: Prisma.RowWhereInput
  /**
   * Limit how many Rows to update.
   */
  limit?: number
}

/**
 * Row updateManyAndReturn
 */
export type RowUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * The data used to update Rows.
   */
  data: Prisma.XOR<Prisma.RowUpdateManyMutationInput, Prisma.RowUncheckedUpdateManyInput>
  /**
   * Filter which Rows to update
   */
  where?: Prisma.RowWhereInput
  /**
   * Limit how many Rows to update.
   */
  limit?: number
}

/**
 * Row upsert
 */
export type RowUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
  /**
   * The filter to search for the Row to update in case it exists.
   */
  where: Prisma.RowWhereUniqueInput
  /**
   * In case the Row found by the `where` argument doesn't exist, create a new Row with this data.
   */
  create: Prisma.XOR<Prisma.RowCreateInput, Prisma.RowUncheckedCreateInput>
  /**
   * In case the Row was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RowUpdateInput, Prisma.RowUncheckedUpdateInput>
}

/**
 * Row delete
 */
export type RowDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
  /**
   * Filter which Row to delete.
   */
  where: Prisma.RowWhereUniqueInput
}

/**
 * Row deleteMany
 */
export type RowDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Rows to delete
   */
  where?: Prisma.RowWhereInput
  /**
   * Limit how many Rows to delete.
   */
  limit?: number
}

/**
 * Row.tables
 */
export type Row$tablesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Table
   */
  select?: Prisma.TableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Table
   */
  omit?: Prisma.TableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TableInclude<ExtArgs> | null
  where?: Prisma.TableWhereInput
  orderBy?: Prisma.TableOrderByWithRelationInput | Prisma.TableOrderByWithRelationInput[]
  cursor?: Prisma.TableWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TableScalarFieldEnum | Prisma.TableScalarFieldEnum[]
}

/**
 * Row.fileBlobs
 */
export type Row$fileBlobsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileBlob
   */
  select?: Prisma.FileBlobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileBlob
   */
  omit?: Prisma.FileBlobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileBlobInclude<ExtArgs> | null
  where?: Prisma.FileBlobWhereInput
  orderBy?: Prisma.FileBlobOrderByWithRelationInput | Prisma.FileBlobOrderByWithRelationInput[]
  cursor?: Prisma.FileBlobWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FileBlobScalarFieldEnum | Prisma.FileBlobScalarFieldEnum[]
}

/**
 * Row without action
 */
export type RowDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Row
   */
  select?: Prisma.RowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Row
   */
  omit?: Prisma.RowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RowInclude<ExtArgs> | null
}
