"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type Mutation {
  startRun(data: StartRunInput!): StartRunResultModel!
}

type Query {
  run(id: ID!): RunModel
  systemInfo: SystemInfoModel!
}

type RunErrorModel {
  code: String!
  message: String!
}

type RunModel {
  createdAt: DateTime!
  error: RunErrorModel
  executionPlan: JSON!
  id: ID!
  input: JSON!
  result: JSON
  status: String!
  updatedAt: DateTime!
}

input StartRunInput {
  input: JSON!
  pipeline: JSON!
}

type StartRunResultModel {
  runId: ID!
}

type SystemInfoModel {
  name: String!
  status: String!
}
